Cargo.toml, sqlx-core/Cargo.toml, sqlx-macros/Cargo.toml
=> Build docs for all features

README.md
A user on reddit figured out the right incantation for making `rustc` happy, I've confirmed it compiles on my machine with this change in my project that threw all the errors.
=> Fix instructions for using tokio

sqlx-core/src/postgres/types/mod.rs
=> Add PgTypeInfo::with_oid

Cargo.lock, sqlx-core/Cargo.toml, sqlx-core/src/mysql/connection.rs, sqlx-core/src/postgres/connection.rs, sqlx-core/src/url.rs
=> Fix passwords not being percent decoded

sqlx-core/src/mysql/protocol/row.rs, sqlx-core/src/mysql/types/float.rs, tests/mysql-types.rs
=> fix and test floats in MySQL

Cargo.toml, sqlx-macros/src/derives/type.rs, tests/sqlite-derives.rs
I added the missing pieces to support derives for sqlite types
=> support derives for sqlite

tests/mysql.rs
this test currently causes as hang
=> add test for fetch one messing up stream states

.github/workflows/rust.yml, Cargo.lock, Cargo.toml, README.md, sqlx-core/Cargo.toml, sqlx-core/src/mysql/types/mod.rs, sqlx-core/src/mysql/types/time.rs, sqlx-core/src/postgres/types/chrono.rs, sqlx-core/src/postgres/types/mod.rs, sqlx-core/src/postgres/types/time.rs, sqlx-core/src/types.rs, sqlx-macros/Cargo.toml, sqlx-macros/src/database/mysql.rs, sqlx-macros/src/database/postgres.rs, tests/mysql-types-chrono.rs, tests/mysql-types-time.rs, tests/postgres-types-chrono.rs, tests/postgres-types-time.rs
Fixes #115
* added new `time` feature
* Implementation currently passing all tests (but there is one strange thing, look for `FIXME`) comment
* old `chrono` feature is working
=> #115: implement time-rs support

CONTRIBUTING.md
Closes https://github.com/launchbadge/sqlx/issues/209
I tried to keep it simple and basic for now, based on what I know. Feel free to suggest changes!
=> Add a basic CONTRIBUTING doc

Cargo.lock, sqlx-core/Cargo.toml, sqlx-core/src/mysql/protocol/handshake.rs, sqlx-core/src/postgres/protocol/authentication.rs, sqlx-core/src/postgres/protocol/ready_for_query.rs, sqlx-core/src/postgres/protocol/response.rs
=> [Refactor] Remove matches dependency and use matches macro from std

sqlx-core/src/postgres/executor.rs
=> Make postgres type name resolution case-insensitive

cargo-sqlx/Cargo.toml, cargo-sqlx/src/database_migrator.rs, cargo-sqlx/src/main.rs, cargo-sqlx/src/postgres.rs, cargo-sqlx/src/sqlite.rs
Show list of applied and not applied migrations. This is something I miss from other migrators :)
=> List migrations

sqlx-core/src/mysql/protocol/handshake.rs
=> mysql: Advance buffer to comply with protocol

sqlx-core/src/postgres/types/bigdecimal.rs, tests/mysql-types.rs, tests/postgres-types.rs
=> fix and test handling of 0 for BigDecimal in Postgres/MySQL

Cargo.lock, examples/postgres/todo-api/.env-example, examples/postgres/todo-api/.gitignore, examples/postgres/todo-api/Cargo.toml, examples/postgres/todo-api/README.md, examples/postgres/todo-api/schema.sql, examples/postgres/todo-api/src/main.rs, examples/postgres/todo-api/src/todo/mod.rs, examples/postgres/todo-api/src/todo/model.rs, examples/postgres/todo-api/src/todo/routes.rs
I was looking for an example of using Actix-web and SQLx and didn't find any. So here is one :)
=> Todo API example using Actix-web and SQLx with PostgreSQL database

sqlx-core/src/types.rs
Forgot about these traits last time :panda_face:
=> Derive Serialize and Deserialize for Json

examples/mysql/todos/src/main.rs, examples/postgres/todos/src/main.rs, examples/sqlite/todos/src/main.rs
=> Add meaningful errors to examples at env::var

cargo-sqlx/README.md, cargo-sqlx/src/main.rs, cargo-sqlx/src/mysql.rs
Couldn't get database name quoting working correctly. Does seems strongly discouraged to use special characters in mysql db names. See: [Mysql Create Database with special characters in the name](https://stackoverflow.com/questions/925696/mysql-create-database-with-special-characters-in-the-name/925730#925730)
=> Add support for mysql to cargo sqlx

cargo-sqlx/.gitignore, cargo-sqlx/src/postgres.rs
=> Quote postgres drop/create database

sqlx-core/src/postgres/connection/mod.rs, tests/postgres/postgres.rs
=> PgConnection: use more obvious query for `ping()`

sqlx-macros/src/derives/encode.rs
=> fix(macros): fix derive for Encode

sqlx-core/src/sqlite/statement/mod.rs
=> Allow queries on virtual tables

sqlx-core/src/transaction.rs
=> Don't leak transactions on explicit commit/rollback

sqlx-core/src/mssql/protocol/type_info.rs, sqlx-core/src/mssql/types/bool.rs, sqlx-core/src/mssql/types/mod.rs, tests/mssql/types.rs
=> Feature: implement `BIT` support in MSSQL

sqlx-core/src/postgres/connection/establish.rs, sqlx-core/src/postgres/connection/stream.rs, tests/postgres/postgres.rs
Fixes https://github.com/launchbadge/sqlx/issues/484
=> Handle `ParameterStatus` in `PgStream`

sqlx-macros/src/query/input.rs, src/macros.rs, tests/sqlite/macros.rs
=> Allow queries string literals to be concatenated

sqlx-cli/README.md, sqlx-macros/src/query/mod.rs
=> Add SQLX_OFFLINE env variable to force metadata usage

sqlx-core/src/postgres/types/money.rs
Quite useful and tedious method to write, so better to have it in SQLx...
=> Conversion from `BigDecimal` to `PgMoney`

Cargo.lock, sqlx-cli/Cargo.toml
… to allow building for musl targets.
=> Add an openssl-vendored feature to sqlx-cli

Cargo.lock, Cargo.toml, sqlx-core/Cargo.toml, sqlx-core/src/postgres/types/bit_vec.rs, sqlx-core/src/postgres/types/mod.rs, sqlx-core/src/types/mod.rs, sqlx-macros/Cargo.toml, sqlx-macros/src/database/postgres.rs, tests/postgres/types.rs
=> Pg: Implementing `BIT` and `VARBIT` using BitVec

examples/postgres/listen/src/main.rs
I think `select pg_notify()` is more flexible and consistent since it takes bind parameters and the channel name is always a string so it's not folded to lowercase as with using an unquoted identifier with `NOTIFY`.
We can also demonstrate `json_build_object()` rather than quasi-quoting JSON directly.
=> refactor(examples): use `select pg_notify` in postgres/listen

sqlx-core/src/postgres/connection/mod.rs, tests/postgres/postgres.rs
Fixes dropping transactions (#580) + Add test to make sure it works.
I am quite sure the fix is correct, not so sure if the test is well named/written.
=> Fix handle pending ready querys (postgres)

sqlx-cli/README.md
=> Fix incorrect bash command within sqlx-cli README

sqlx-cli/README.md, sqlx-cli/src/lib.rs, sqlx-cli/src/opt.rs
Addresses https://github.com/launchbadge/sqlx/issues/354
=> Add --database-url to command line

sqlx-core/src/postgres/connection/establish.rs, sqlx-core/src/postgres/options/mod.rs, sqlx-core/src/postgres/options/parse.rs, tests/postgres/postgres.rs
Support for postgres `application_name`
Addresses https://github.com/launchbadge/sqlx/issues/180
=> Set pg application_name

sqlx-cli/src/lib.rs
- check the existance of `Cargo.toml` at current working directory
before checking 'DATABASE_URL' environment variable
=> fix(issue #558)

sqlx-core/src/query.rs
Should fix #641. Can somebody verify?
=> Fix Query::map

Cargo.lock, sqlx-cli/Cargo.toml, sqlx-cli/src/prepare.rs
=> Delete target/sqlx before invoking cargo in `cargo sqlx prepare`

sqlx-core/src/mysql/options/parse.rs
Fixes #603.
Adds percent decoding for MySQL passwords for when they contain non-URL
safe passwords, along with a regression test to prevent further
instances of this issue.
=> Percent decode MySQL passwords from URL string

Cargo.lock, Cargo.toml
Adds the example project to the workspace manifest, resolves #380
=> Fix pg todos example

sqlx-core/src/pool/mod.rs
Closes https://github.com/launchbadge/sqlx/issues/700
=> Add `Pool::size()` and `num_idle()`

sqlx-core/Cargo.toml
Fixed version of #697. I tested that this compiles, although not that it fixes the broken links.
r? @mehcode
=> Enable all features for `sqlx-core` on docs.rs

sqlx-macros/src/database/postgres.rs
I think the TODO blocking this is stale...
=> Enable support for Vec<DateTime<Utc>> w/ postgres, chrono

sqlx-core/src/sqlite/types/json.rs, sqlx-core/src/sqlite/types/mod.rs, tests/sqlite/types.rs
=> sqlite: Add basic json implementation

Cargo.lock, sqlx-cli/Cargo.toml, sqlx-cli/src/database.rs
=> fix(cli): wait for newlines for confirmations

sqlx-core/src/from_row.rs, sqlx-core/src/types/mod.rs
=> doc: improve docs for `Type` and `FromRow` derives

sqlx-cli/src/lib.rs, sqlx-cli/src/migrate.rs, sqlx-cli/src/opt.rs
=> Add source param to command line

sqlx-core/src/pool/mod.rs
Signed-off-by: Austin Bonander <austin@launchbadge.com>
=> WIP improve docs about Pool

Cargo.lock, Cargo.toml, examples/postgres/json/Cargo.toml, examples/postgres/json/README.md, examples/postgres/json/migrations/20200824190010_json.sql, examples/postgres/json/src/main.rs
Simple example of the usage of macro overrides with JSON data, following the same pattern as the todos example.
=> JSON+macros example using overrides

sqlx-core/src/migrate/mod.rs, sqlx-core/src/sqlite/arguments.rs, sqlx-core/src/sqlite/connection/executor.rs, sqlx-core/src/sqlite/connection/explain.rs, sqlx-core/src/sqlite/migrate.rs, sqlx-core/src/sqlite/row.rs, sqlx-core/src/sqlite/statement/mod.rs, sqlx-core/src/sqlite/statement/virtual.rs, sqlx-macros/src/derives/attributes.rs, src/ty_match.rs
This commit fixes clippy warnings, mostly related to sqlite feature.
=> fix clippy warnings

sqlx-core/Cargo.toml, sqlx-core/src/common/statement_cache.rs
fix https://github.com/launchbadge/sqlx/issues/747
=> Replace lru-cache with hashlink

sqlx-macros/src/query/mod.rs
=> add 1 as true for SQLX_OFFLINE env variable

sqlx-core/src/sqlite/connection/collation.rs
=> sqlite: fix memory leak

README.md
=> Make quickstart actually quick

sqlx-core/src/migrate/migrator.rs
=> Add new example for migration

examples/mysql/todos/Cargo.toml
This gets the MySQL example compiling again :)
=> examples/mysql/todos/Cargo.toml:  Add runtime feature

Cargo.lock, contrib/ide/vscode/settings.json, sqlx-cli/Cargo.toml, sqlx-cli/src/opt.rs, sqlx-cli/src/prepare.rs, sqlx-macros/Cargo.toml, sqlx-macros/src/query/data.rs, sqlx-macros/src/query/mod.rs
Extracted from #941 because it looks like actix-rt 2.0 is imminent and so that will likely not make it for SQLx 0.5.
=> Some improvements to offline support code

sqlx-macros/Cargo.toml, sqlx-macros/src/query/mod.rs, tests/postgres/postgres.rs
Seems like #1001 isn't *that* easy to trigger (maybe it needs nested `Map`s). Posting this now though to make sure the tests pass in CI (they do locally).
=> Refactor / add tests for `Query::map`

sqlx-core/src/migrate/migrator.rs, sqlx-core/src/migrate/source.rs
Adds the documentation that would be helpful to answer #1050.
=> doc: Add information on the required structure of the migration scripts

sqlx-core/src/types/bstr.rs, sqlx-core/src/types/git2.rs, sqlx-core/src/types/mod.rs
=> Make re-exports from other crates show up as such

sqlx-core/src/any/types.rs
Hello,
This PR would add  impl of AnyEncode, AnyDecode, and Type<crate::any::Any> for chrono time types when all the SQL types included in compilation features support these types.
=> Adding Any Type, Encode, and Decode impl for chrono time types

sqlx-core/src/postgres/message/parse.rs, tests/sqlite/derives.rs
https://github.com/launchbadge/sqlx/issues/671
=> Correct Postgres' Length Limit for Bind Parameters

sqlx-macros/src/derives/type.rs
=> Remove redunant braces in type_name

sqlx-cli/Cargo.toml, sqlx-cli/src/prepare.rs
* Removed unnecessarey preserve_order feature for serde_json
* More reliable serialization-desetislization of sqlx-data.json
* Added unit tests for sqlx-data.json serialization-deserialization
=> Fix for #935:  Removed unnecessarey preserve_order feature for serde_json in sqlx-cli

tests/sqlite/sqlite.rs
Test that initial PRAGMA statements and &str statements are not
cached, but sqlx::query() statements are cached by default.
=> test(sqlite): extend it_caches_statements() test

sqlx-macros/src/database/postgres.rs
I was looking into this [issue](https://github.com/launchbadge/sqlx/issues/1206), so i decided to work on it.
Need a little help in creating test cases for this change. @abonander
=> PgMoney type for sqlx macros

examples/mysql/todos/Cargo.toml, sqlx-macros/Cargo.toml, sqlx-macros/src/query/mod.rs
Some small improvements I did while working on #1183, as a separate PR so it can be reviewed and merged before that PR is ready.
=> sqlx-data.json removal prep work

sqlx-core/src/error/database.rs
Most of the code here just came directly from the master branch
=> feat(core): Added error downcasting in the style of the master branch

README.md, sqlx-cli/README.md
=> Improve root README.md and sqlx-cli/README.md

FAQ.md, README.md
[Rendered](https://github.com/launchbadge/sqlx/blob/ab/faq/FAQ.md)
=> feat(docs): add an FAQ

sqlx-core/src/postgres/type_info.rs
Sbd. recently ran into this and asked about it on Discord, this additional debug info helped debug a bit.
=> Add more debugging info to unresolved type declaration panic

Cargo.lock, sqlx-core/Cargo.toml, sqlx-core/src/postgres/connection/sasl.rs
Changelog: https://github.com/RustCrypto/MACs/blob/master/hmac/CHANGELOG.md#0110-2021-04-29
=> Upgrade hmac to 0.11

CHANGELOG.md, Cargo.lock, Cargo.toml, prep-release.sh, sqlx-cli/Cargo.toml, sqlx-core/Cargo.toml, sqlx-macros/Cargo.toml, sqlx-rt/Cargo.toml
Added a shell script to make this easier in the future.
=> prepare 0.5.9 hotfix release

sqlx-core/src/any/kind.rs
resolves https://github.com/launchbadge/sqlx/issues/1383
*Comment: I'm a newcomer to this repo. If I had anything inappropriate, it would be great if you point it out.*
=> derive Clone, Copy for AnyKind

sqlx-cli/README.md
I ran into this and found the solution inside of this issue https://github.com/launchbadge/sqlx/issues/1593
Fixes #1593
=> Document Offline mode with feature flags

src/macros.rs
This patch fixes the broken link.
=> Address #1718

sqlx-core/src/mssql/arguments.rs, sqlx-core/src/mysql/arguments.rs
This allows to reuse them in retry loops with query_with
=> Derive clone for mysql and mssql arguments

sqlx-cli/README.md, sqlx-cli/src/lib.rs, sqlx-cli/src/opt.rs
=> Add --source for migration subcommands

sqlx-core/Cargo.toml, sqlx-core/src/mysql/arguments.rs, sqlx-core/src/query_builder.rs, src/lib.rs
elaborates on the API introduced in #1780
closes #291
=> feat: document and expand query builder

sqlx-core/src/postgres/value.rs
=> make methods pub

sqlx-core/src/mssql/protocol/return_value.rs, sqlx-core/src/mssql/protocol/type_info.rs
similar to https://github.com/launchbadge/sqlx/pull/1891, https://github.com/launchbadge/sqlx/pull/1890
=> added test for mssql ReturnValue

FAQ.md
=> fix: typo in FAQ.md

sqlx-core/src/postgres/listener.rs
=> fix: ensure PG connection is established before using it

sqlx-core/Cargo.toml
=> Bump sqlformat to 0.2.0

sqlx-core/src/from_row.rs
=> Fix typo in FromRow docs

sqlx-core/src/sqlite/options/mod.rs
Just a drive-by, don't mind me
=> SqliteConnectOptions typo

sqlx-core/src/sqlite/connection/explain.rs
Avoid improper branch merges if a pseudocursors backing register, or a cursor emptiness state is different than the previous evaluation.
=> fix logical merge conflict

.github/workflows/sqlx.yml
=> Run CI on *-dev branch

Cargo.lock, sqlx-core/Cargo.toml
I close #2356 and create new up to date
=> Disable rustls crate logging feature by default up to date

sqlx-macros-core/src/lib.rs, sqlx-macros-core/src/migrate.rs
=> fix(macros-core): use of undeclared `tracked_path`

sqlx-sqlite/src/connection/explain.rs, tests/sqlite/describe.rs
Add tests & fix issues with basic analytic function support.
=> Sqlite analytical

Cargo.lock, sqlx-core/Cargo.toml
=> Bump indexmap and ahash

sqlx-mysql/src/options/mod.rs, sqlx-postgres/src/options/mod.rs, sqlx-sqlite/src/options/mod.rs
=> doc: make it clear that `ConnectOptions` types impl `FromStr`

Cargo.lock, sqlx-sqlite/Cargo.toml
=> Fix #2384, bump flume to v0.11.0

sqlx-mysql/src/types/mod.rs, src/macros/mod.rs
=> doc(mysql): document behavior regarding `BOOLEAN` and the query macros

Cargo.lock, sqlx-sqlite/Cargo.toml, sqlx-sqlite/src/connection/establish.rs
=> [fix] Urlencode when passing filenames to sqlite3

sqlx-core/src/logger.rs
=> feat: use specific message for slow query logs

Cargo.lock, sqlx-core/src/row.rs, sqlx-core/src/statement.rs
=> Fixed docs

sqlx-cli/src/migrate.rs, sqlx-core/src/migrate/migrator.rs
- Documentation link fix
- Moved variable declaration for readability
- Added an abstraction to check if a migration version exists for better readability
=> Minor fixes

sqlx-postgres/src/options/mod.rs
This PR updates the example for `PgConnectOptions`
=> docs: update example for `PgConnectOptions`

sqlx-postgres/src/any.rs
=> fix: AnyRow not support PgType::Varchar

sqlx-macros-core/src/test_attr.rs
=> Reorder attrs in sqlx::test macro

sqlx-core/src/net/tls/tls_rustls.rs
=> Fix unclean TLS shutdown

src/any/install_drivers_note.md, src/any/mod.rs, src/lib.rs, src/macros/mod.rs
Fix several inter doc links.
Might fix more while looking though the documentation.
=> Fix several inter doc links

.github/workflows/sqlx.yml
Correct:
Invalid workflow file: .github/workflows/sqlx.yml#L207 You have an error in your yaml syntax on line 207
=> ci: syntax fix

sqlx-cli/LICENSE-APACHE, sqlx-cli/LICENSE-MIT, sqlx-core/LICENSE-APACHE, sqlx-core/LICENSE-MIT, sqlx-macros-core/LICENSE-APACHE, sqlx-macros-core/LICENSE-MIT, sqlx-macros/LICENSE-APACHE, sqlx-macros/LICENSE-MIT, sqlx-mysql/LICENSE-APACHE, sqlx-mysql/LICENSE-MIT, sqlx-postgres/LICENSE-APACHE, sqlx-postgres/LICENSE-MIT, sqlx-sqlite/LICENSE-APACHE, sqlx-sqlite/LICENSE-MIT, sqlx-test/LICENSE-APACHE, sqlx-test/LICENSE-MIT
=> Add LICENSE-* files to crates

sqlx-macros-core/src/derives/row.rs
=> allow rename with rename_all (close #2896)

.github/workflows/sqlx.yml
=> fix: usage of `node12` in `SQLx` action

README.md
Changed version from 0.7 to 0.8
=> Update version to 0.8 in README

sqlx-macros-core/src/derives/attributes.rs, tests/postgres/derives.rs
Fixes an issue with PgHasArrayType.
Fixes: #3445
=> fix(#3445): PgHasArrayType

Cargo.lock, Cargo.toml
This removes a lot of old dependencies in the tree.
c.f. https://github.com/async-rs/async-std/issues/1081 - two years in the works.
=> chore: Update async-std v1.13

sqlx-postgres/src/migrate.rs
=> fix: obey `no-transaction` flag in down migrations

src/any/mod.rs
Its currently not very easy to create generic data types, reexporting this will make it a better experience
fixes #3578 (see end of conversation)
=> Reexport AnyTypeInfoKind

src/macros/test.md
Alternative option for the sqlx::test fixtures referenced the same fixture twice
=> Fix mistake in sqlx::test fixtures docs

Cargo.lock, sqlx-core/Cargo.toml
https://github.com/kyren/hashlink/releases/tag/v0.10
=> Bump hashlink to v0.10

Cargo.lock, sqlx-cli/Cargo.toml
async-trait seems not to be used.
=> chore(cli): remove unused async-trait crate from dependencies

sqlx-core/src/pool/options.rs
Don't know if this fixes an issue, just noticed that the example was wrong.
Cheers Stefan
=> Fix example calculation in docs

sqlx-mysql/src/protocol/text/row.rs
Previously, `TextRow::decode_with` would read a length-encoded field size and attempt to advance the buffer by that amount. If the server sent a malformed packet containing a length value larger than the remaining data in the buffer, the call to `buf.advance(size)` would panic.
eg: 
```
thread 'main' panicked at /home/user/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bytes-1.10.1/src/bytes.rs:711:9:
cannot advance past remaining: 8590116092 <= 0
stack backtrace:
0:     0x56119b657e00 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h6d42cc84fc840290
1:     0x56119b67edd3 - core::fmt::write::h5af61a909e3ec64d
2:     0x56119b653ee3 - std::io::Write::write_fmt::h5a7b54aa6e4a315d
3:     0x56119b657c52 - …
```
=> mysql: Fix panic on invalid text row length field

.github/workflows/sqlx-cli.yml, .github/workflows/sqlx.yml, CHANGELOG.md, Cargo.lock, Cargo.toml, sqlx-cli/src/bin/cargo-sqlx.rs, sqlx-cli/src/bin/sqlx.rs, sqlx-cli/src/lib.rs, sqlx-cli/src/opt.rs, sqlx-mysql/src/testing/mod.rs, tests/mysql/test-attr.rs
=> Hotfix 0.8.5

sqlx-core/src/sync.rs
=> chore: clean up no longer used imports
