sqlx-core/src/pool/inner.rs
sqlx-core/src/pool/mod.rs
sqlx-core/src/pool/options.rs

In some frameworks `Debug` is required to put `Pool` in app state's context structs which define Debug by default.

derive Debug for Pool

---

Cargo.lock
Cargo.toml
sqlx-core/src/arguments.rs
sqlx-core/src/mysql/database.rs
sqlx-core/src/postgres/arguments.rs
sqlx-core/src/postgres/database.rs
sqlx-core/src/query_as.rs
sqlx-macros/Cargo.toml
sqlx-macros/src/lib.rs
sqlx-macros/src/query_macros/args.rs
sqlx-macros/src/query_macros/input.rs
sqlx-macros/src/query_macros/mod.rs
sqlx-macros/src/query_macros/query.rs
src/lib.rs
src/macros.rs
tests/mysql.rs
tests/postgres-macros.rs

closes #46
closes #47
This technically makes our MSRV 1.40 but we're only testing on latest stable and newer anyway.

WIP: strip out `proc-macro-hack`

---

examples/realworld-postgres/src/main.rs
sqlx-core/src/lib.rs
sqlx-core/src/mysql/connection.rs
sqlx-core/src/mysql/mod.rs
sqlx-core/src/pool/executor.rs
sqlx-core/src/pool/mod.rs
sqlx-core/src/postgres/connection.rs
sqlx-core/src/postgres/mod.rs
sqlx-core/src/transaction.rs
sqlx-macros/src/lib.rs

Add a Transaction type to simplify dealing with Transactions

---

Cargo.lock
sqlx-macros/Cargo.toml
sqlx-macros/src/lib.rs

Sets up a runtime in a lazy_static for blocking on current thread, and makes use of [`Builder::basic_scheduler`](https://docs.rs/tokio/0.2.9/tokio/runtime/struct.Builder.html#method.basic_scheduler) to _definitely_ avoid spinning up a thread pool for blocking the current thread.
Even if you don't want this particular PR, we should probably still make use of `basic_scheduler`.

Only create tokio runtime once for block_on

---

.github/workflows/rust.yml
Cargo.lock
Cargo.toml
sqlx-core/src/io/tls.rs
sqlx-core/src/postgres/arguments.rs
sqlx-core/src/postgres/protocol/close.rs
sqlx-core/src/postgres/protocol/mod.rs
sqlx-core/src/postgres/protocol/ssl_request.rs
sqlx-macros/src/lib.rs
sqlx-macros/src/query_macros/args.rs
sqlx-macros/src/query_macros/input.rs
sqlx-macros/src/query_macros/output.rs
src/lib.rs
tests/ui-tests.rs
tests/ui/postgres/issue_30.rs
tests/ui/postgres/issue_30.stderr

add regression test with Trybuild
fix lint warnings as otherwise Trybuild wanted to include them
closes #53

sqlx-macros: fix handling of invalid idents

---

Cargo.toml
sqlx-macros/src/derives.rs
sqlx-macros/src/lib.rs
src/decode.rs
src/encode.rs
src/lib.rs
tests/derives.rs

add derives for Encode and Decode

---

Cargo.toml
sqlx-macros/src/query_macros/output.rs
tests/mysql-macros.rs
tests/mysql.rs
tests/postgres-macros.rs

This change makes it so the sqlx macros generate every ident as raw identifiers so that it will support the field if its name happens to coincide with a rust identifier.
closes #95

Enable raw ident support

---

src/macros.rs
tests/postgres-macros.rs

Fix #105, allow trailing commas in query macros

---

CHANGELOG.md
src/lib.rs

@mehcode per our convo on Discord, I figured I would go ahead and pop a PR for this. About as easy as it gets `:)`

Export sqlx_core::Transaction.

---

sqlx-core/src/mysql/arguments.rs

Fixes #125.
The cause was the bitmap bytes being cleared by the `&=`, only if the very last bit of that byte would ever be set (if it was null), all others would be `AND`'d away to zero

Fix null bitmap bytes being cleared

---

sqlx-core/src/postgres/connection.rs

This way SQLx can support more server versions, including CockroachDB, which only supports the `postgres` style.
Of note: If we wanted to support conversion of PostgresSQL's `INTERVAL`s to a special type, we'd have to support all IntervalStyles anyway, in case somebody used `SET SESSION IntervalStyle` to change it after connection is established.
Fixes #130.
I believe the current `master` struggles with Postgres tests a little so CI might fail.
Thanks for the immediate response y'all!

postgres: remove IntervalStyle to fix #130

---

Cargo.lock
Cargo.toml
sqlx-core/Cargo.toml
sqlx-core/src/postgres/protocol/type_id.rs
sqlx-core/src/postgres/types/ipnetwork.rs
sqlx-core/src/postgres/types/mod.rs
sqlx-core/src/postgres/types/network.rs
sqlx-core/src/types.rs
sqlx-macros/Cargo.toml
sqlx-macros/src/database/postgres.rs
tests/postgres-types.rs
tests/ui-tests.rs
tests/ui/postgres/gated/ipnetwork.rs
tests/ui/postgres/gated/ipnetwork.stderr

This pull request is trying to implement `ipnetwork` support for PostgreSQL.
Currently, it only implements the `Decode` and `Encode` trait for `IpNetwork`, because I have encountered a problem: there are no way to encoding one struct into two different types. In this case, `IpNetwork` can not be decoded into both `INET` and `CIDR`.
A workaround is to create two wrapper structs: 
```rust
pub struct Inet(IpNetwork);
pub struct Cidr(IpNetwork);
```
... but I'm not sure if it's acceptable. =)

[wip] postgres: ipnetwork support

---

Cargo.lock
Cargo.toml
sqlx-core/Cargo.toml
sqlx-core/src/postgres/types/bigdecimal.rs
sqlx-core/src/postgres/types/ipnetwork.rs
sqlx-macros/Cargo.toml
sqlx-macros/src/database/postgres.rs
tests/postgres-types.rs

This adds most of the remaining types to `query!` macro arrays.
There was one type I wasn't able to get working, `DateTime<Utc>`. Currently, I left its non-working implementation and test just commented out.
As for testing, I added a macro for using the `query!` macros. Right now it is very verbose and needs a good rewrite when/if the concatenation of SQL literals gets implemented.

Add array of uuid, chrono, time, bigdecimal, and ipnetwork as well as JsonValue to query macro

---

sqlx-macros/src/derives/row.rs
tests/postgres-derives.rs

This PR fixes the the incorrect handling of keywords fields of a struct in the FromRow macro.
Currently a struct with a field like 'r#type' will try to read values from a column with the exact same name with r# prefix. With this change this field will now map to a database column with the correct name 'type' without the r# prefix.

Process keyword fields correctly in FromRow macro

---

sqlx-core/src/cursor.rs
sqlx-core/src/query.rs
sqlx-core/src/query_as.rs
sqlx-core/src/transaction.rs

Mark several types as #[must_use]

---

sqlx-core/src/mysql/connection.rs
sqlx-core/src/postgres/connection.rs
sqlx-core/src/url.rs

Decodes connection string URL component so usernames with `@` symbols in them are handled properly.
Closes #152

Decode username on read

---

.github/workflows/build-examples.yml

Follow up for issue: https://github.com/launchbadge/sqlx/issues/207
Installing the psql client is brittle and making the action fail (see https://github.com/launchbadge/sqlx/runs/559129591). 
Instead use the psql client in the docker container to load the schema.

Use psql client in container to make action less brittle

---

sqlx-core/src/sqlite/arguments.rs
sqlx-core/src/sqlite/statement.rs
sqlx-core/src/sqlite/value.rs

Without these changes, sqlx couldn't be built with `sqlite` feature for such architectures as armv7: there are errors such as
```
--> sqlx-core/src/sqlite/arguments.rs:106:25
|
106 |                         bytes_ptr,
|                         ^^^^^^^^^ expected `u8`, found `i8`
|
= note: expected raw pointer `*const u8`
found raw pointer `*const i8`
```
These changes can verified by installing and running `cross` for cross-compiling (requires Docker)
```
cargo install cross --version 1.0.16
cross build --target armv7-unknown-linux-gnueabihf --features sqlite
```
or by building on real device (e.g. Raspberry Pi).

Sqlite: fixed types of variables that interact with libsqlite3

---

sqlx-macros/src/derives/row.rs
sqlx-macros/src/lib.rs
tests/postgres-derives.rs

supports #[sqlx(rename = "xxx")] attribute in a FromRow macro

support rename attribute in FromRow macro

---

.github/workflows/rust.yml
sqlx-core/src/mysql/protocol/row.rs
sqlx-core/src/mysql/protocol/type.rs
sqlx-core/src/mysql/types/bigdecimal.rs
sqlx-core/src/mysql/types/mod.rs
sqlx-macros/src/database/mysql.rs
tests/mysql-types.rs

Implement `DECIMAL` type support for mysql.
Close #202

Implement `DECIMAL` type support for mysql

---

sqlx-core/src/query.rs

This should be a backwards-compatible change that makes `Map::fetch()` usable as intended. Using `BoxStream` would be a breaking change because it requires the stream to be `Send` which we would have to add to `F` and `F::Output`.
TODO: regression test, might just do as a code example
closes #244

make the stream returned from `Map::fetch()` `Unpin`

---

cargo-sqlx/Cargo.toml
cargo-sqlx/src/main.rs

So I did some clean up and integrated anyhow for cleaner error messages.
I also included a function that uses the connection string to create a database if there is none with the correct name in the database. Would like some feedback on wether that is a good idea or not. 
As is you can't actually create the database in a normal migration because the connection will fail because there is no database... 
This could be worked around in a number of ways.
1. We could assume there is always a database created 
2. There could be specialized migration script that creates the database (like `create_db.sql`)
3. Assume the first migration always is a create database script
4. Use the connection string to create a database
5. A mix of the above
I can see pros and cons with all of these methods. This …

Enable create database

---

sqlx-macros/src/lib.rs
sqlx-macros/src/query_macros/mod.rs
sqlx-macros/src/query_macros/query.rs
src/macros.rs

Add query_unchecked and query_file_unchecked macros

---

sqlx-core/src/types.rs

Derive all traits and impl Deref and AsRef for types::Json

---

sqlx-core/src/sqlite/connection.rs
sqlx-core/src/url.rs

undo URL percent-encoding for SQLite connection strings

---

sqlx-core/src/executor.rs
sqlx-core/src/lib.rs
sqlx-core/src/logging.rs
sqlx-core/src/mysql/executor.rs
sqlx-core/src/postgres/executor.rs
sqlx-core/src/query.rs
sqlx-core/src/query_as.rs
sqlx-core/src/sqlite/executor.rs

Prints each query performed at DEBUG level,
along with a timing of how long the query took
to execute.
Slow queries will be printed at WARN level.
Currently the slow query threshold is
hardcoded to 1 second.
Begins #162

Add basic query logging

---

Cargo.lock
sqlx-macros/Cargo.toml
sqlx-macros/src/derives/attributes.rs
sqlx-macros/src/derives/mod.rs

I encountered a use case while converting a project
from Diesel to sqlx, where I had a custom Postgres enum
which included a snake case field name:
```rust
pub enum JobStatus {
NotRun,
Finished,
Failed,
}
```
Which translates to:
```sql
CREATE TYPE job_status AS ENUM ('not_run', 'finished', 'failed');
```
This is likely to be a semi-common use case,
so this commit adds snake case support for enums
via the `#[sqlx(rename_all = "snake_case")]` attribute.

Add snake_case rename support for Type macro

---

cargo-sqlx/Cargo.toml
cargo-sqlx/src/database_migrator.rs
cargo-sqlx/src/main.rs
cargo-sqlx/src/postgres.rs
cargo-sqlx/src/sqlite.rs

Start refactoring a bit so it's not all in main.
* Added support for sqlite and prepared for mysql
* Ask if user want to drop database 
* Add alias `mig` for migrate
Had some issues with performing migrations in a transaction with sqlite, so would appreciate some help there.

Prepare migrator for more databases

---

sqlx-core/Cargo.toml
sqlx-core/src/io/tls.rs
sqlx-core/src/mysql/stream.rs
sqlx-core/src/mysql/tls.rs
sqlx-core/src/postgres/connection.rs
sqlx-core/src/postgres/stream.rs
sqlx-core/src/postgres/tls.rs
sqlx-core/src/runtime.rs
sqlx-core/src/url.rs

This PR adds unix domain socket support for Postgres.  It also changes the default values of multiple connection parameters to match libpq behaviour, e.g. `postgres:///` was equivalent to `postgres:///postgres@localhost/postgres` for sqlx, but now sqlx would connect to the DB via UDS with the current user as username and database name (assuming we're running a Unix).
Current state: Works on my Linux :laughing:  What kind of tests would you like to see?
Open questions:
- This PR uses `$USER` to get the name of the current user.  Does this work on all (supported) Unixes? What about Windows? Do we want to be smarter? (e.g. call `geteuid` and `getpwuid`)
- What about TLS over UDS? This is currently not supported.
Fixes #144

Add unix domain socket support for Postgres

---

Cargo.lock
sqlx-core/src/mysql/types/json.rs
sqlx-core/src/mysql/types/mod.rs
sqlx-core/src/postgres/types/json.rs
sqlx-core/src/types.rs
tests/mysql-types.rs

mysql: Add JSON support

---

Cargo.lock
sqlx-core/Cargo.toml
sqlx-core/src/logging.rs

Before, the query would be formatted equivalent to the input string:
```
[2020-04-18T23:47:32Z DEBUG sqlx_core::postgres::executor] SELECT id, queue, ..., elapsed: 2.320µs
SELECT id, queue, payload, status, priority, created_at, updated_at
FROM jobs
WHERE status = $1
ORDER BY priority ASC, created_at ASC
```
After, the query is formatted cleanly and consistently:
```
[2020-04-19T00:30:18Z DEBUG sqlx_core::postgres::executor] SELECT id, queue, ..., elapsed: 2.280µs
SELECT
id,
queue,
payload,
status,
priority,
created_at,
updated_at
FROM
jobs
WHERE
status = $1
ORDER BY
priority ASC,
created_at ASC
```
This uses the [`sqlformat`](https://github.com/shssoichiro/sqlformat-rs) crate, which was ported from the Javascript [`sql-formatter-plus`](https://github.com/kufii/sql-formatter-plus) library …

Format SQL queries when printing them to the logs

---

sqlx-core/src/logging.rs

This will make logged queries show
as from `sqlx::query` instead of `sqlx::db_name::executor`.
Followup to #268 [comment](https://github.com/launchbadge/sqlx/pull/268#issuecomment-616241075)

Log queries from sqlx::query

---

sqlx-macros/src/lib.rs

This change will attempt to load an .env file from CARGO_MANIFEST_DIR, if it exists.
For backwards compatibility, if the .env file does not exist, we will fall back to default dotenv behaviour.
Resolves #267

Add support for crate specific .env files

---

sqlx-core/src/sqlite/connection.rs

Ensure all statements are dropped before closing sqlite connection

---

.github/workflows/rust.yml
tests/ui-tests.rs
tests/ui/mysql/gated/chrono.stderr
tests/ui/postgres/gated/chrono.stderr
tests/ui/postgres/gated/ipnetwork.stderr
tests/ui/postgres/gated/uuid.stderr
tests/ui/postgres/issue_30.stderr
tests/ui/postgres/unsupported-type.stderr
tests/ui/postgres/wrong_param_type.stderr
tests/ui/sqlite/expression-column-type.stderr

looks like the `.stderr` file for a SQLite UI test never got added, and notes on errors in other tests changed slightly

fix UI tests

---

README.md

I believe `.build()` takes `&str`, but `env:var()` returns ` Result<String, VarError>`

readme example typo

---

sqlx-core/src/mysql/types/mod.rs

Fix a spell mistake: "TIMETAMP" -> "TIMESTAMP"

Fix a misspelling in MySQL types document

---

sqlx-macros/src/derives/attributes.rs
sqlx-macros/src/derives/mod.rs
tests/mysql-derives.rs
tests/postgres-derives.rs
tests/sqlite-derives.rs

Thank you for this project!
I've begun switching my project to sqlx and I ran into an issue with my custom enum types. I've created all my enum types as uppercase and rename_all for uppercase didn't exist.

Add uppercase support for Type macro

---

README.md

This  `.await?` in the example code looks unnecessary.
```
$ rustc -V
rustc 1.43.0 (4fb7144ed 2020-04-20)
```
```toml
[dependencies]
tokio = { version = "0.2", features = ["full"] }
sqlx = { version = "0.3", default-features = false, features = [ "runtime-tokio", "macros", "mysql" ] }
```
```rust
// main.rs
use sqlx::mysql::MySqlPool;
use sqlx::Cursor;
#[tokio::main]
async fn main() -> Result<(), sqlx::Error> {
// Create a connection pool
let pool = MySqlPool::new("mysql://root:secret@localhost:3306/foo").await.unwrap();
let email = "test@example.com";
// Make a simple query to return the given parameter
let mut cursor = sqlx::query("SELECT * FROM users WHERE email = ?")
.bind(email)
.fetch(&pool).await.unwrap();
while let Some(row) = cursor.next().await? {
// map the row into a …
```

Fix the example code in README

---

sqlx-core/src/pool/inner.rs

I tried to create a database connection pool, the code is as follows, and then I found a bug
```rust
//......
let conn_string = format!(
"mysql://{user}:{password}@{host}:{port}/{database}",
user = server_config.db_user(),
password = server_config.db_password(),
host = server_config.db_host(),
port = server_config.db_port(),
database = server_config.db_name()
);
MySqlPool::builder()
.connect_timeout(Duration::from_secs(10))
.min_size(10)
.max_size(100)
.idle_timeout(Duration::from_secs(5 * 60))
.max_lifetime(Duration::from_secs(30 * 60))
.build(&conn_string)
.await;
```
I want it to create 10 connections when it is initialized, and it can hold up to 100 connections.
But in fact it did not do this, it directly created 100 connections during initialization.
I finally found the location of …

fix bug in init_min_connections

---

sqlx-core/src/mysql/connection/executor.rs
tests/mysql/describe.rs

If a query has a column alias available we should use that name instead
of the column name.
Fixes #385

mysql: always use column alias when available

---

Cargo.toml
sqlx-core/src/postgres/types/bigdecimal.rs

Previously any number like 1000, 1000_0000, etc, would have the wrong scale by 1
Closes #423

 fix: bigdecimal decoding ob1 for positive weight multiples of 4

---

sqlx-core/src/sqlite/connection/mod.rs

Per #430, adds a method `as_raw_handle()` to get the underlying `sqlite3*` from a `SqliteConnection`.
This PR is cleaner (a single commit). The previous PR also failed CI due to a (hopefully) random fault in docker.

Adds a method get the underlying sqlite3 pointer

---

sqlx-core/src/common/mod.rs
sqlx-core/src/common/statement_cache.rs
sqlx-core/src/mysql/connection/mod.rs
sqlx-core/src/mysql/connection/stream.rs
sqlx-core/src/mysql/options.rs
sqlx-core/src/net/socket.rs
sqlx-core/src/postgres/connection/stream.rs
sqlx-core/src/postgres/options.rs

- Adds support for Unix Domain Sockets on MySQL
- Allows setting the socket path in PostgreSQL connection options
- ... and MySQL connection options
Fixes issue https://github.com/launchbadge/sqlx/issues/449

MySQL UDS Support

---

sqlx-core/src/mysql/connection/mod.rs

Joins the MySQL connection setup statements into a single statement to prevent issues with ProxySQL, which requires special handling of connections that might be shared between multiple backends.
Original:
> Splits the MySQL connection setup statements into discrete executions to
> prevent issues with proxies, such as ProxySQL, which may need to balance
> and share connections between different backends.
> 
> Fixes #422
> 
> Signed-off-by: Marcus Griep <marcus@griep.us>

fix(mysql): improve compatibility with ProxySQL

---

sqlx-core/src/mysql/types/chrono.rs
sqlx-core/src/mysql/types/time.rs
tests/mysql/types.rs

mysql: Fix decoding of TIME '00:00:00.000000'

---

sqlx-core/src/sqlite/error.rs

This allows us to match between SQLite's errors, allowing conversion to more useful types.

Reveal SQLite's extended error code

---

sqlx-core/src/postgres/type_info.rs
sqlx-core/src/postgres/types/int.rs
sqlx-core/src/postgres/types/mod.rs
sqlx-core/src/postgres/types/money.rs
tests/postgres/types.rs

Reading is possible as `i64`, presenting the number of cents with the default setting. The fractional precision depends on the `lc_monetary` setting. By default the setting gives a fractional precision of 2.
Writing works with `i32`, `i64` or a numeric type such as `BigDecimal`. When using an integer to write, it is not possible to represent cents. Writing `123` to a money field stores a value of 12300.
When writing with a numeric type, cents can be represented. Reading should still be done to an integer and if needed, converted to a numeric type in the application to get the correct fractional precision.

Support for `money` type in Postgres

---

sqlx-core/src/sqlite/type_info.rs
sqlx-core/src/sqlite/types/chrono.rs
sqlx-core/src/sqlite/types/mod.rs
sqlx-core/src/types/mod.rs
sqlx-macros/src/database/sqlite.rs
tests/sqlite/setup.sql
tests/sqlite/types.rs

Hello!
This pull request rebases #230, fixes it to work on master, adds support to `DateTime<Utc>` and `DateTime<Local>`, and adds a few tests.

WIP: chrono for SQLite, rebasing @felipesere + more

---

src/macros.rs

These should all expand to invocations of `expand_query!()` but I guess I missed a couple.
Closes #503

fix(macros): fix broken `_unchecked` macros

---

sqlx-macros/src/derives/attributes.rs
sqlx-macros/src/derives/row.rs
tests/postgres/derives.rs

Closes https://github.com/launchbadge/sqlx/issues/308
I'm not used to doing stuff with macros, but this seemed easy enough to give it a try.
Still needs documentation, more tests? (where?) and whatever fixes are necessary :smiley:

[WIP] Support for #[sqlx(default)]

---

sqlx-macros/src/derives/row.rs

A remnant from #495 that used sqlx_core directly requiring end-user to add it as a dependency from the expanded macro.

fix(macros) - use re-exported Error type from sqlx crate

---

sqlx-core/src/from_row.rs

As requested in https://github.com/launchbadge/sqlx/pull/495
~I set the rust code examples without `ignore`, which is present in the first code example - I'm not sure why it's necessary.~ nvm, figured it out :zany_face: 
I didn't see any standard for docs, so I just rolled with something that looked nice

FromRow derivation docs

---

Cargo.lock
sqlx-core/Cargo.toml

I was looking through a project's cargo tree output at usages for the rand crate and noticed that sqlx-core has an indirect dependency on it through the phf crate. When I went to check where this was used, it apparently was not in use anywhere?
A fast commit search shows that it got added with [this commit](https://github.com/launchbadge/sqlx/commit/757a930e21860ab402b5afdf210c5f2a542b1b1d) 2 months ago, but even in it I couldn't see where it was used. 
After I removed it I tried `cargo check  --no-default-features  --features offline,all-databases,all-types,runtime-{tokio, async-std, actix}` and rustc didn't complain. `rg -i --no-ignore-dot "phf"` also returns 0 results. The two macros in phf-macros are defined [here](https://github.com/sfackler/rust-phf/blob/master/phf_macros/src/lib.rs# …

Remove unused phf dependency

---

sqlx-core/src/sqlite/types/chrono.rs

Hi, I noticed something that looks like a debug message when I was playing around with sqlite. It probably shouldn't be there so I removed it.
Thank you for this very nice library too!

Remove sneaky 'println!' in sqlite chrono.

---

sqlx-macros/src/derives/attributes.rs
sqlx-macros/src/derives/mod.rs
tests/postgres/derives.rs

This mirrors the addition of `uppercase` in https://github.com/launchbadge/sqlx/pull/304, but for all uppercase snake case.

Add SCREAMING_SNAKE_CASE rename_all option

---

sqlx-core/src/error.rs
sqlx-core/src/executor.rs
sqlx-core/src/query.rs
sqlx-core/src/query_as.rs
sqlx-core/src/query_scalar.rs
sqlx-core/src/row.rs
sqlx-core/src/value.rs
src/macros.rs

When we generate docs of the current master branch (dad1356147235ab9057f262743dc72a3bcf793f1), the following 20 warnings are reported:
<details><summary>click me to see the warnings</summary>
<p>
```
cargo +nightly doc
```
```
warning: `[Row::get]` cannot be resolved, ignoring it.
--> sqlx-core/src/error.rs:23:20
|
23 | /// Returned from [`Row::get`] if the value from the database is `NULL`,
|                    ^^^^^^^^^^ cannot be resolved, ignoring
|
= note: `#[warn(intra_doc_link_resolution_failure)]` on by default
= help: to escape `[` and `]` characters, just add '\' before them like `\[` or `\]`
warning: `[crate::row::FromRow]` cannot be resolved, ignoring it.
--> sqlx-core/src/query.rs:80:23
|
80 |     /// a [`FromRow`](crate::row::FromRow) implementation.
| …
```

doc: fix wrong links

---

Cargo.lock
sqlx-cli/Cargo.toml
sqlx-cli/src/bin/cargo-sqlx.rs

And also update the console dependency so it no longer gets compiled twice (0.10 direct, 0.11 indirect).

cargo-sqlx-cli: Fix exiting with 0 on failure

---

sqlx-core/src/mysql/types/uint.rs

https://dev.mysql.com/doc/refman/5.7/en/year.html

Allow decoding a `YEAR` value as uint from MySQL

---

.github/workflows/sqlx.yml
Cargo.toml
sqlx-cli/src/migrate.rs
sqlx-core/src/migrate/migration.rs
sqlx-core/src/migrate/migrator.rs
sqlx-macros/Cargo.toml
sqlx-macros/src/common.rs
sqlx-macros/src/lib.rs
sqlx-macros/src/migrate.rs
sqlx-macros/src/query/input.rs
src/lib.rs
src/macros.rs
tests/migrate/macro.rs
tests/migrate/migrations/20200723212833_tweet.sql
tests/migrate/migrations/20200723212841_accounts.sql

This PR implements embedded migrations with a new `migrate!` macro. The macro takes an optional string literal for specifying the migrations directory, which defaults to `"migrations"`. It expands to a static instance of `Migrator`.
```rust
sqlx::migrate!().run(&pool).await?;
```
Addresses #550

Embedded migrations

---

sqlx-core/src/migrate/migration.rs
sqlx-core/src/migrate/source.rs

This simply adds constructors for Migration. I don't think this is a great API, but it works for my cases. This allows for fully embedding the migrations in the binary rather than having to ship the migrations and the binary. Below is an example of how I plan to use it (they're simple migrations for an IRC bot):
```
#[derive(Debug)]
struct IntegratedMigrations(Vec<Migration>);
impl IntegratedMigrations {
fn new() -> Self {
IntegratedMigrations(vec![
Migration::new(1, "karma".into(), include_str!("1_karma.sql").into()),
Migration::new(2, "bucket".into(), include_str!("2_bucket.sql").into()),
Migration::new(3, "noaa".into(), include_str!("3_noaa.sql").into()),
Migration::new(4, "forecast".into(), include_str!("4_forecast.sql").into()),
])
}
}
impl MigrationSource<'static> for …
```

Allow MigrationSource to be implemented externally

---

.github/workflows/sqlx.yml

This PR implements CI builds of `cargo-sqlx` as build artifacts. Windows and macOS builds target their default triple while Linux targets `unknown-linux-musl` for improved compatibility. All builds only target `x86_64` and are in debug mode (since they're CI builds, and it speeds up compile times, and the CLI isn't really performance critical anyway, but that can be easily changed).
Currently this PR doesn't implement builds attached to releases themselves, as it was unclear to me whether that should be done by creating the release when detecting a version tag and then attaching the binaries, or by simply attaching the binaries to existing releases when they are created manually.
Also implements caching to speed up most CI jobs.

CI binary builds and caching

---

sqlx-macros/src/query/args.rs

cc https://github.com/rust-lang/rust-clippy/issues/5849
@jplatte could you please test if this change resolves the warning with your Clippy configuration

fix(macros): resolve clippy lint warning

---

sqlx-core/src/logger.rs

The query log did not have a `target` property, which led to it not being affected by log filters (e.g. in `env_logger`)

Added missing target for query logger

---

Cargo.lock
sqlx-core/Cargo.toml
sqlx-core/src/postgres/types/decimal.rs

num_bigint::BigInt, rust_decimal::Decimal use same trait ToPrimitive from crate nums-traits(0.2).
https://github.com/launchbadge/sqlx/blob/9ea5ce01a2b04779203bd086e7eb1358ada70ec1/sqlx-core/src/postgres/types/decimal.rs#L2
`use rust_decimal::prelude::ToPrimitive;` is as same as `use num_traits::ToPrimitive;`
The num_traits dependency is unnecessary.
https://github.com/launchbadge/sqlx/blob/9ea5ce01a2b04779203bd086e7eb1358ada70ec1/sqlx-core/src/postgres/types/decimal.rs#L71

Remove rust_decimal unnecessary dependency num-traits

---

sqlx-cli/src/bin/sqlx.rs

Fixes https://github.com/launchbadge/sqlx/issues/582
This will make sqlx-cli exit with an error code of 1 if it errors. Why? Because CI, that's why.

sqlx-cli: Exit with code 1 on error.

---

Cargo.toml
sqlx-core/Cargo.toml
sqlx-core/src/postgres/type_info.rs
sqlx-core/src/type_info.rs
sqlx-macros/Cargo.toml
sqlx-macros/src/query/mod.rs
src/macros.rs
tests/postgres/macros.rs

 fix: allow queries that select just void to pass through macros as `()` instead of `struct { _1: () }`

---

src/macros.rs

Just a tiny fix to add a missing bracket which caused the syntax highlighting to fail on docs.rs.

docs(macros): Add missing closing bracket in docs code example

---

sqlx-core/src/mssql/mod.rs

Fixed typo in doc: `MySQL` -> `MSSQL`

doc: fix typo

---

sqlx-cli/README.md

The docs mentions `sqlx migration run`, but the `migration` subcommand does not exist. `sqlx migrate run` does exist and is probably meant.

`sqlx migration` subcommand does not exist but `sqlx migrate` does

---

sqlx-core/src/postgres/options/parse.rs

The `url` crate returns username and password portions of a URL as percent encoded ASCII strings. In order to use them for the Postgres connection, we need to decode them.
This seems to be a regression from #214.
We found this as well when connecting to a PostgreSQL DB in Azure, which uses the `username@hostname` format for all it's usernames.

Support non-ASCII chars in postgres credentials

---

sqlx-core/src/sqlite/connection/establish.rs
sqlx-core/src/sqlite/options/mod.rs
sqlx-core/src/sqlite/options/parse.rs

This addresses issue #362 by enabling the shared cache for in-memory sqlite databases and generating a new unique filename per in-memory pool config. The existing implementation returns a blank database when opening a connection to the pool that has not been reused.

Add support for pooling in-memory sqlite DB, enabling shared cache

---

sqlx-core/src/mysql/types/str.rs

I also switched that bit of the conditional to use `matches!()`, as it seemed like 3+ allowed values was starting to get a little unwieldy for a `||` chain, but I can always switch that back if desired
The actual purpose is that it enables compiling against a Vitess database :) although in theory, I'd imagine it would also enable people using `utf8 COLLATE utf8_general_ci` on a `TEXT` column with vanilla MySQL/MariaDB

sqlx-core/src/mysql/types/str.rs:  str::compatible():  Added support for charset number 33 (utf8 COLLATE utf8_general_ci)

---

sqlx-core/src/any/options.rs

With this change you can customize the connect options for each database even when using the `Any` driver.

impl From for AnyConnectOptions

---

sqlx-core/src/arguments.rs
sqlx-core/src/sqlite/connection/explain.rs
sqlx-macros/src/query/input.rs
sqlx-macros/src/query/mod.rs
sqlx-macros/src/query/output.rs
src/macros.rs
tests/mysql/macros.rs
tests/postgres/macros.rs
tests/sqlite/describe.rs
tests/sqlite/macros.rs

(0.5) implement `query_scalar!()`

---

sqlx-core/Cargo.toml
sqlx-core/src/postgres/connection/describe.rs
sqlx-core/src/postgres/connection/executor.rs
sqlx-core/src/postgres/io/buf_mut.rs
src/macros.rs
tests/postgres/postgres.rs
tests/sqlite/describe.rs

BREAKING CHANGE: some columns emitted by `query!()` and `query_as!()`, primarily those brought in by a `[LEFT | RIGHT | FULL] JOIN` will become `Option<T>` where they were `T` before.
In practice breakage should be minimal as these would result in `UnexpectedNull` errors at runtime unless they were manually overridden with `foo as "foo?"` already.
However, I expect there to be edge cases that aren't covered yet, thus why we've chosen to land this in 0.5 and kick out an early alpha for testing.
* requires the `json` feature (and thus the `serde` and `serde_json` features) to always be on for `postgres` (to parse `EXPLAIN VERBOSE` output, possible formats are JSON, XML, YAML or text)
closes #367

(BREAKING: 0.5) patch nullable inference in Postgres using EXPLAIN

---

sqlx-cli/src/database.rs
sqlx-cli/src/lib.rs
sqlx-cli/src/opt.rs

Addresses #596 - Similar to the way [Phoenix](https://github.com/phoenixframework/phoenix/pull/1202/commits/502e06b521b014c6423fbd26859c21b2057fb23c) has aliases for common database operations, this adds the following commands following the same terminology.
- `sqlx db reset` - Runs the equivalent of `sqlx db drop`, `sqlx db create`, and `sqlx migrate run`. Useful when developing.
- `sqlx db setup` - Runs the equivalent of `sqlx db create` and `sqlx migrate run`. Useful when pulling an existing project with many migrations already created.

sqlx-cli: adds the db reset and setup command

---

sqlx-core/src/mysql/options/mod.rs

I'm using this library for the first time, and I noticed this small oversight in the docs.

Correct PgConnectOptions to MySql in mysql docs

---

sqlx-core/src/error.rs
sqlx-core/src/sqlite/connection/describe.rs
sqlx-core/src/sqlite/connection/executor.rs
sqlx-core/src/sqlite/connection/mod.rs
sqlx-core/src/sqlite/statement/worker.rs

Explanation and benchmark has been already provided inside https://github.com/launchbadge/sqlx/issues/616, so - without further ado - here's the code.

sqlite: Fix #616

---

sqlx-core/src/postgres/options/mod.rs
sqlx-core/src/postgres/options/parse.rs

This adds the ability to parse additional parameters, mentioned in #501. It does not add the complete set of acceptable parameters from the Postgres spec, but it adds parsing capabilities for all the options sqlx supports today relating to postgres. Also adds documentation for the new parameters, as well as an example connection string that utilizes parameters as that was missing before.

Parse additional postgres connection parameters

---

sqlx-core/src/pool/options.rs

I took this from the changelog. Let me know if I should add similar examples to the other `after_` and `before_` methods.

Add examples to `after_connect` documentation

---

sqlx-core/src/mysql/protocol/text/column.rs

In some cases the returned value is of `ColumnType::String`, but it has the `ENUM` flag set.

Use flags to detect MySQL enums

---

sqlx-core/src/pool/inner.rs
tests/mysql/mysql.rs
tests/postgres/postgres.rs

fixes #622
cc @skuzins @cetra3 would two mind trying this branch to see if it still has the problem?

fix(pool): ignore spurious wakeups when waiting for a connection

---

README.md

Closes https://github.com/launchbadge/sqlx/issues/728.

Document `macros` feature in README

---

sqlx-core/src/mysql/protocol/statement/execute.rs

The MySQL protocol [specifies that the `iteration-count` field should always be set to 1](https://dev.mysql.com/doc/internals/en/com-stmt-execute.html), but MySQL itself [ignores the field entirely](https://github.com/mysql/mysql-server/blob/f8cdce86448a211511e8a039c62580ae16cb96f5/sql/protocol_classic.cc#L2628,L2640).  Vitess is more strict and will reject execute packets with `iteration-count` set to anything other than 1.
It sounds like they may change to mimic actual MySQL behavior, but I figured you would like to also have the protocol correction on your end, even if it is borderline pedantic :)

[MySQL] Fix minor issue in execute statement packet

---

sqlx-core/src/sqlite/types/chrono.rs

The [documentation](https://docs.rs/chrono/0.4.13/chrono/naive/struct.NaiveDate.html#method.parse_from_str) specifies that `NaiveDate::parse_from_str` takes two arguments: value and format, in respective order. 
Due to this, `DATE` fields could not be read into `NaiveDate`... and I have ptsd.

Fix NaiveDate parse_from_str argument order

---

Cargo.lock
sqlx-core/Cargo.toml
sqlx-core/src/any/statement.rs
sqlx-core/src/lib.rs
sqlx-core/src/mssql/connection/stream.rs
sqlx-core/src/mssql/protocol/col_meta_data.rs
sqlx-core/src/mssql/row.rs
sqlx-core/src/mssql/statement.rs
sqlx-core/src/mysql/connection/executor.rs
sqlx-core/src/mysql/row.rs
sqlx-core/src/mysql/statement.rs
sqlx-core/src/postgres/connection/describe.rs
sqlx-core/src/postgres/connection/establish.rs
sqlx-core/src/postgres/connection/mod.rs
sqlx-core/src/postgres/statement.rs
sqlx-core/src/sqlite/connection/explain.rs
sqlx-core/src/sqlite/row.rs
sqlx-core/src/sqlite/statement/mod.rs
sqlx-core/src/sqlite/statement/virtual.rs

Hashbrown is now the hashmap used in the standard library, so no need to
pull in an external dependency.
Closes https://github.com/launchbadge/sqlx/issues/731

Remove hashbrown dependency

---

sqlx-core/src/postgres/options/mod.rs
sqlx-core/src/postgres/options/parse.rs

This PR improves the parsing of `PgConnectOptions` to more accurately support less common forms described by the postgres documentation, including:
- Specifying a socket path with percent encoding in the host position (e.g. `postgres://user@%2Fvar%2Flib%2Fpostgres/database`)
- Supporting more connection parameters
- `user`
- `password`
- `hostaddr` (functions the same as `host`, but with an additional assertion that it must parse as an `IpAddr`)
- The postgres documentation allows specifying multiple values for `hostaddr` which will be tried in order, but this implementation only allows one value
- `port`
- `dbname`
These changes allow some use cases that were previously impossible without manipulating environment variables - for example, there was previously no way to specify a socket …

Support percent-encoded socket files and more parameters in postgres connect URIs

---

sqlx-core/src/postgres/message/response.rs

In order to support PostgreSQL <= 9.5, the b'S' field of an error/notice
message was parsed. However, this field can be localized and thus parsing
can fail for instances that use a non-english locale. In version > 9.5,
the b'V' field, that is guaranteed to be in english, was added. However,
even for these versions parsing would fail as the b'S' field was also
parsed. This patch prefers b'V' over b'S' if it exists and uses a default
severity in case b'V' is not present and b'S' could not be parsed.
Fixes #734

fix(postgres): prefer parsing non-localized notice severity field

---

sqlx-macros/src/derives/attributes.rs
sqlx-macros/src/derives/mod.rs
tests/postgres/derives.rs

Here, adding an option to have `kebab-case` as enum in postgres `TYPE`.
Linking to issue [#752](https://github.com/launchbadge/sqlx/issues/752).
Let me know if anything else is required.

Add support of kebab-case enum with Postgres

---

src/macros.rs

Fixes issue experienced in https://github.com/launchbadge/sqlx/issues/746 when using no parameter:
```
error: paths relative to the current file's directory are not currently supported
--> src/db.rs:7:5
|
7 |     sqlx::migrate!().run(&conn).await?;
|     ^^^^^^^^^^^^^^^^
|
= note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

Fix migrate! macro with no params

---

sqlx-macros/src/derives/row.rs
tests/postgres/derives.rs

Add #[derive(FromRow)] for tuple struct

---

sqlx-macros/src/database/postgres.rs

This PR enables using postgres range types in `query!` macros.

Add ranges and range arrays types

---

README.md

Hi, I think I found a typo in a code example of the readme while getting started with SQLx.

Fix typo: add missing &pool parameter in readme

---

sqlx-cli/src/prepare.rs
sqlx-core/src/common/statement_cache.rs
sqlx-macros/src/query/mod.rs

I've transitioned to a workflow where `SQLX_OFFLINE` is the default because it improves compile times substantially. However, it feels like this workflow is not well supported with `cargo sqlx prepare` writing the cache from cache data if `SQLX_OFFLINE` is `true`. Luckily, after #732, there's an easy way to overwrite `SQLX_OFFLINE` (before, you could only unset the env variable but that wouldn't help when it was set in `.env`).
The last commit should allow running multiple cargo commands (e.g. IDE-spawned `cargo check` + `cargo sqlx prepare`) without the risk for broken query metadata files, as long as only one of them is running in online mode.

Improve SQLX_OFFLINE / cargo sqlx prepare workflow

---

sqlx-cli/README.md

Behaviour changed in #732, but docs weren't updated.

Fix documentation for SQLX_OFFLINE environment variable

---

sqlx-cli/src/prepare.rs

By the way, the feature wasn't mentioned in README of sqlx.
This made me wonder and I looked into sqlx-cli features, I wonder why there isn't offline feature.

Add context of where to put the offline feature

---

sqlx-core/src/sqlite/statement/worker.rs

This commit greatly improves performance of SQLite worker. In quick&dirty tests it not also was twice fast but also had much less CPU usage (most probably because of busy-loop removed).

use futures_channel::oneshot in sqlite worker

---

sqlx-macros/src/derives/attributes.rs

This fixes https://github.com/launchbadge/sqlx/issues/774
Some other crates use non meta attributes, this crashes FromRow and Encode derive when using on the same struct.
This patch makes sure the identifier is sqlx before passing it to parse_meta.

Fixing don't parse all attributes as `Meta`

---

sqlx-core/src/sqlite/arguments.rs
tests/sqlite/sqlite.rs

The sqlite driver for sqlx currently supports only the `?` and `?NNN` bind parameter formats. However, sqlite supports additional formats as specified here: https://sqlite.org/c3ref/bind_blob.html. With this change, I propose adding support for `$NNN`, which is a subset of `$VVV`. This will make it easier for sqlx users to write queries that are supported by both sqlite and postgres.

Support $NNN bind parameters for sqlite

---

sqlx-core/src/any/options.rs
sqlx-core/src/connection.rs
sqlx-core/src/logger.rs
sqlx-core/src/mssql/connection/establish.rs
sqlx-core/src/mssql/connection/executor.rs
sqlx-core/src/mssql/connection/mod.rs
sqlx-core/src/mssql/options/connect.rs
sqlx-core/src/mssql/options/mod.rs
sqlx-core/src/mysql/connection/establish.rs
sqlx-core/src/mysql/connection/executor.rs
sqlx-core/src/mysql/connection/mod.rs
sqlx-core/src/mysql/options/connect.rs
sqlx-core/src/mysql/options/mod.rs
sqlx-core/src/postgres/connection/establish.rs
sqlx-core/src/postgres/connection/executor.rs
sqlx-core/src/postgres/connection/mod.rs
sqlx-core/src/postgres/options/connect.rs
sqlx-core/src/postgres/options/mod.rs
sqlx-core/src/sqlite/connection/establish.rs
sqlx-core/src/sqlite/connection/executor.rs
sqlx-core/src/sqlite/connection/mod.rs
sqlx-core/src/sqlite/options/connect.rs
sqlx-core/src/sqlite/options/mod.rs

Allow dynamically configuring the log level of the query log. 
This is an alternative to #601.

Allow configuring the log level of query logging

---

README.md

Nothing too crazy: Just removal of a duplicate entry, and then move one item so that the `runtime-foo-*` entries entries for a given runtime are grouped together.

doc: README.md: minor cleanup of section "Cargo Feature Flags"

---

.github/workflows/sqlx.yml

In the wake of submitting PR #808 I saw that the GitHub Actions workflow was failing. Though it was unrelated to the changes in that specific PR, the failure messages were similar to what I was seeing building locally, so I decided to take a look:
```
Error:   --> sqlx-rt/src/lib.rs:9:1
|
9  | / compile_error!(
10 | |     "one of the features ['runtime-actix-native-tls', 'runtime-async-std-native-tls', \
11 | |      'runtime-tokio-native-tls', 'runtime-actix-rustls', 'runtime-async-std-rustls', \
12 | |      'runtime-tokio-rustls'] must be enabled"
13 | | );
| |__^
```
The current PR sprinkles-in the use of the feature name matrix in the handful of obvious places needed to allow `cargo build` invocation to succeed (by explicitly naming 'runtime${foo}').
I tested these changes one at at …

gh actions: sprinkle use of runtime feature name matrix to allow successful run of all jobs

---

sqlx-cli/README.md

I was getting an error while running `cargo sqlx prepare` while on `sqlx` version 0.4.1:
```
error: EOF while parsing an object at line 34 column 6
```
Then I realized that I had version 0.1.0-beta.1 of sqlx-cli but 0.2.0 was released on cargo.
I upgraded to 0.2.0 and the command succeeded.
I figured that the README was mistakenly not updated with the release.

Bump version in sqlx-cli README to 0.2.0

---

sqlx-macros/src/query/args.rs
sqlx-macros/src/query/mod.rs

Expanding several query arguments in the query! macro creates several `if false { ... }` statements, which in turn trigger clippy's [suspicious_else_formatting](https://rust-lang.github.io/rust-clippy/master/index.html#suspicious_else_formatting).
This commit allows the clippy lint so users won't be disturbed by it anymore.

Allow clippy::suspicious_else_formatting when expanding query arguments.

---

sqlx-cli/src/database.rs
sqlx-cli/src/lib.rs
sqlx-cli/src/migrate.rs
sqlx-cli/src/opt.rs
sqlx-core/src/any/migrate.rs
sqlx-core/src/migrate/error.rs
sqlx-core/src/migrate/migrate.rs
sqlx-core/src/migrate/migration.rs
sqlx-core/src/migrate/migration_type.rs
sqlx-core/src/migrate/mod.rs
sqlx-core/src/migrate/source.rs
sqlx-core/src/mysql/migrate.rs
sqlx-core/src/postgres/migrate.rs
sqlx-core/src/sqlite/migrate.rs
sqlx-macros/src/migrate.rs

- add -r flag to migration add command which if true will generate an up and a down file
- add revert subcommand, which reverts the last migration
- add --dry-run flag to migration run command, which list the migrations that will be applied
- updates add migration to check if all migration are of same type, i.e cannot mix and match reversible and simple migrations
- add database reset subcommand which drops and creates database and applies migrations
Tested on Postgresql. Need to test on mysql and sqlite

reversible migrations for cli

---

sqlx-macros/src/database/postgres.rs

Fix path for &[NaiveTime] in query! macro

---

sqlx-core/src/any/mod.rs
sqlx-core/src/mssql/mod.rs
sqlx-core/src/mysql/mod.rs
sqlx-core/src/postgres/mod.rs
sqlx-core/src/query.rs
sqlx-core/src/sqlite/mod.rs
src/lib.rs

The same thing as #823, but a new PR because GitHub doesn't allow reopening after closing, then force-pushing to the head branch. @abonander's review feedback has been incorporated (hence the force-push).

Allow chaining map / try_map

---

sqlx-core/Cargo.toml

Fixed: https://github.com/launchbadge/sqlx/issues/903

fix: whoami crash on FreeBSD aarch platform

---

sqlx-core/src/pool/connection.rs
sqlx-core/src/pool/inner.rs

This fixes an issue where the use of `PoolConnection::release` would later cause `Pool::close` to enter an infinite loop.
Update: I merged the suggested fix from #897

Fix: decrement pool size when connection is released

---

Cargo.lock
sqlx-cli/src/lib.rs
sqlx-cli/src/opt.rs
sqlx-cli/src/prepare.rs
sqlx-macros/Cargo.toml
sqlx-macros/src/query/mod.rs

This patch enables having a top-level `sqlx-data.json` file within a
workspace.
It does this by using a full clean / check instead of `cargo rustc`
which fails on a workspace.
It also uses the `cargo_metadata` package to find the `workspace_root`
(which should be the same as `CARGO_MANIFEST_DIR` in a non workspace).
Note: `cargo_metadata` pulls in serde / serde_json. I wasn't sure if I
should remove the features for those with this change.
Fixes #353.
Signed-off-by: Joe Grund <jgrund@whamcloud.io>

Support workspaces for offline feature

---

Cargo.lock
Cargo.toml
examples/postgres/mockable-todos/.env.example
examples/postgres/mockable-todos/Cargo.toml
examples/postgres/mockable-todos/README.md
examples/postgres/mockable-todos/docker-compose.yml
examples/postgres/mockable-todos/migrations/20200718111257_todos.sql
examples/postgres/mockable-todos/src/main.rs
examples/postgres/todos/Cargo.toml

This PR adds a Postgres example based on the ideas in [this blog post](https://medium.com/better-programming/structuring-rust-project-for-testability-18207b5d0243).
We also fixed the existing postgres/todos example (2nd commit).  If you want us to pull this out into a separate PR then we can do.
If this PR is ok, then we have a stab at making an example for transactions as well, potentially using the `Acquire` trait.

Add postgres example with test of business logic

---

Cargo.lock
Cargo.toml
README.md
sqlx-core/Cargo.toml
sqlx-core/src/types/bstr.rs
sqlx-core/src/types/git2.rs
sqlx-core/src/types/mod.rs
tests/sqlite/types.rs

This adds support for SQL conversions for the bstr::BString binary
string type, and for the git2::Oid object ID type. Both types are
encoded and decoded as bytes.
These types are database-independent and work with any database that can
handle bytes, so add tests that work with sqlite.

Add support for bstr::BString and git2::Oid, behind feature flags

---

sqlx-core/src/sqlite/mod.rs
sqlx-core/src/sqlite/options/connect.rs
sqlx-core/src/sqlite/options/mod.rs
sqlx-core/src/sqlite/options/synchronous.rs

Add support for "synchronous" setting in SQLite connection options.
This makes changing this setting to NORMAL (from default FULL) easy.
The NORMAL mode is even advised by SQLite documentation (and that is understandable):
> If durability is not a concern, then synchronous=NORMAL is normally all one needs in WAL mode.

sqlite synchronous setting

---

sqlx-core/src/from_row.rs
sqlx-macros/src/derives/attributes.rs
sqlx-macros/src/derives/mod.rs
sqlx-macros/src/derives/row.rs
tests/postgres/derives.rs

As per title.
Sample usage (from test)
```rust
#[derive(Debug, sqlx::FromRow)]
#[sqlx(rename_all = "camelCase")]
struct AccountKeyword {
user_id: i32,
user_name: String,
user_surname: String,
}
```
It looks like this feature was present in a previous version / someone's intention because it was already documented (but not working).
The choice of using `camelCase` and `PascalCase` was taken for consistency with `serde` and with the existing documentation, even though heck's terminology is `mixedCase` and `CamelCase`

Add rename_all to FromRow, add camelCase and PascalCase to all rename_all

---

sqlx-macros/src/database/postgres.rs

Adding support in macros for arrays of `bytea` in Postgres.
Closes #873

Adding support for vector of bytea type in postgres

---

sqlx-core/src/connection.rs

This pull requests updates `Connection::transaction` wrapper so it behaves like:
```rust
conn.transaction(|transaction: &mut Transaction<Database> | {
// ...
});
```

Fix transaction wrapper

---

sqlx-core/src/mysql/types/str.rs

Just adding support for another collation being considered a string :)

sqlx-core/src/mysql/types/str.rs:  + COLLATE_UTF8MB4_GENERAL_CI

---

README.md

Added mention to the `mysql` feature flag, as it is required for MySQL support but not mentioned in `README.md`.

Fix README.md to include mysql feature flag

---

sqlx-core/src/pool/inner.rs

If wait_for_conn is dropped before completing, release will call
wake on a waker that no one is listening on. This leads to a state where
waiting will grow indefinitely while all connections are idle.
To fix this we turn waiting into a queue of unique Weak pointers.
This way if wait_for_conn is dropped the pointer in waiting cannot
be upgraded, we can use this as a signal that we shroud wake the
next one instead.
We get into a similar state will happen if wait_for_conn timeouts.

Handle dropping wait_for_conn

---

sqlx-core/src/transaction.rs

Connection::begin link is incorrect (it is a trait, not a struct).

Fix broken link in Transaction docs

---

sqlx-core/src/pool/inner.rs

Fixes #848
This implements exponential backoff on reconnect when connect() returns ECONNREFUSED. We start by waiting 10ms, doubling until plateauing at 2seconds. There is nothing magic about these numbers, they somehow seem reasonable to me.

Connection refused backoff

---

sqlx-core/src/connection.rs
sqlx-macros/src/derives/attributes.rs

I'd like to disable the query logging entirely due to https://github.com/launchbadge/sqlx/issues/633 and a few other reasons.
Currently, it looks like I can do this two ways:
* set `RUST_LOG` env variable or add more configuration into the logger directly: a fragile indirect way, since can be spoiled too easy and not verifiable by the compiler
* use `ConnectOptions`-like trait for my db and pass the `LevelFilter::Off` there, which is good except for the fact that I use `tracing` instead of `log` and I need to drag in another dependency just to disable the logging.
This PR adds another method to `ConnectOptions` that allows disabling the logs without requiring somebody to use `log` crate for that.

Add a way to disable query logging programmatically

---

sqlx-core/src/pool/options.rs

Otherwise 
```
.before_acquire(|conn| {
|          ^^^^^^^^^^^^^^ cannot infer type for type parameter `Fut` declared on the associated function `before_acquire`
```

remove unnecessary Fut

---

sqlx-core/src/query.rs
src/macros.rs

doc: add tables describing the right method to call on `query!()` et al

---

CHANGELOG.md
sqlx-core/src/postgres/types/mod.rs
sqlx-core/src/types/mod.rs
sqlx-macros/src/derives/attributes.rs
sqlx-macros/src/derives/type.rs
src/lib.rs
tests/postgres/derives.rs
tests/ui/postgres/deprecated_rename.rs
tests/ui/postgres/deprecated_rename.stderr
tests/ui/postgres/gated/chrono.stderr
tests/ui/postgres/issue_30.stderr
tests/ui/postgres/wrong_param_type.stderr

As suggested [on Discord](https://discord.com/channels/665528275556106240/694697474689859614/793379588008706100).

Rename sqlx(rename) attribute to sqlx(type_name)

---

sqlx-core/src/mysql/protocol/connect/auth_switch.rs

The current implementation fails to connect a MySQL 8 server if the authentication plugin of the user has been changed from the default  `caching_sha2_password` (related issue: https://github.com/launchbadge/sqlx/issues/779).
This PR addresses the problem.
Note that I'm not familiar with MySQL and not sure this patch is the correct solution to address this issue, so any advice is very welcomed.
Starts a MySQL server:
```
$ docker run -e MYSQL_DATABASE=db -e MYSQL_USER=foo \
-e MYSQL_PASSWORD=password -e MYSQL_ROOT_PASSWORD=password -p 3306:3306 --rm mysql:8.0.22
```
Connects to the server with `foo` user (this will be succeeded):
```rust
use sqlx::Connection;
#[async_std::main]
async fn main() -> anyhow::Result<()> {
let url = "mysql://foo:password@127.0.0.1/db"; …
```

Fix auth switch failure on MySQL 8

---

sqlx-core/src/error.rs
sqlx-core/src/postgres/error.rs
tests/postgres/postgres.rs
tests/postgres/setup.sql

Override `constraint` method for `PgDatabaseError`.
Fixes #821

Add `constraint` method to `DatabaseError` trait

---

sqlx-core/src/error.rs
sqlx-core/src/postgres/connection/describe.rs

This is for  https://github.com/launchbadge/sqlx/issues/239. 
I didn't use the proposed error message in the issue because I'm not sure if there's an easy way differentiate between a missing user type and a typo. Although it does like that method should only be called in the context of new type names. 
I haven't written much Rust and definitely have a couple of questions. 
I don't really understand what's going on with the `?` macro that pulls the `oid` out of the tuple automatically. I think my code would be a little clearer if I didn't need to leave the `oid` in a tuple
I'm also not sure if using `map_error` to mutate the error to the new `TypeNotFound` error is idiomatic
I'm not sure if this is worthy of a new error, and organizationally I'm not sure if it makes sense to have that type …

Improves error handling in the case of missing type

---

tests/sqlite/sqlite.rs

sqlite test - prepared statements are reset after fetch_one

---

sqlx-macros/src/migrate.rs

entry.metadata() does not follow symlinks, while fs::metadata() does. This allows for greater compatibility with the bazel build system which uses symlinks for data files such as migrations.
Fixes #614

Allow symlinks to be followed for migration files

---

sqlx-core/src/sqlite/arguments.rs

`MySqlArguments` implements `Debug + Default` but `SqliteArguments` only implements `Default`.
I wonder if I should add `Clone` especially for backward compatibility in the future. I'm willing to remove `Clone` if I should.

feat: Adds `Debug, Clone` auto-derive to `SqliteArguments`

---

README.md

The function no longer exists. Fixes #969.

Remove fetch_scalar mention from README.md

---

sqlx-core/src/acquire.rs

I think all current `Connection` types are `Send`, so this should be fine, right?

Some improvements around the Acquire trait

---

sqlx-cli/src/lib.rs
sqlx-cli/src/prepare.rs

Moves the check for the existence of `Cargo.toml` to the prepare module. Also uses `anyhow::ensure` instead of `anyhow::bail`.
Closes #1017.

Don't require `Cargo.toml` for all subcommands

---

sqlx-core/src/sqlite/connection/explain.rs

fix(sqlite): GROUP BY in query! cause infinite loop at compile time

---

sqlx-macros/src/derives/attributes.rs
sqlx-macros/src/derives/decode.rs
sqlx-macros/src/derives/encode.rs
sqlx-macros/src/derives/row.rs
sqlx-macros/src/derives/type.rs
sqlx-macros/src/lib.rs
sqlx-macros/src/migrate.rs
sqlx-macros/src/query/args.rs
sqlx-macros/src/query/mod.rs
sqlx-macros/src/query/output.rs

This pr makes all paths in macros absolute paths, so for example `sqlx::Database` becomes `::sqlx::Database`, `str` becomes `::std::primitive::str` and `format!(...)` becomes `::std::format!(...)`

use absolute paths in macros

---

CHANGELOG.md
Cargo.lock
sqlx-macros/src/lib.rs
sqlx-rt/Cargo.toml
sqlx-rt/src/lib.rs

actix-rt is close to releasble, I don't expect any more drastic changes after the current beta-3; not that sqlx uses much of it

rt: update to actix-rt v2

---

sqlx-macros/src/derives/decode.rs
sqlx-macros/src/derives/encode.rs
sqlx-macros/src/derives/mod.rs
sqlx-macros/src/derives/row.rs
sqlx-macros/src/derives/type.rs
sqlx-macros/src/migrate.rs
sqlx-macros/src/query/args.rs

I broke `#[derive(sqlx::Type)]` without `#[sqlx(type_name = "...")]` (or `#[sqlx(rename = "...")]`) in #940, here is a fix along some refactoring.
CC #1031 (after this, the code there *should* compile)

Typename fix

---

clippy.toml
sqlx-core/src/lib.rs
sqlx-core/src/pool/options.rs

It is *much* too easy to misread `x.min(y)` as "`x` should be *at least* `y`" when in fact it means the *exact* opposite, and same with `x.max(y)`. This has bitten us in the gluteus maximus a number of times both in SQLx and in private projects. For example: https://discordapp.com/channels/665528275556106240/729682286513225799/806793002340057098
We need a CI pass running Clippy to make this truly effective though, and it needs to hit all the optional features (at least the not-mutally-exclusive ones) to be sure.

ban `Ord::{min, max}` with Clippy as it's too easy to misread infix calls

---

sqlx-postgres/src/connection/stream.rs

This peaks at the message type and payload size of a postgres message.
It delays removing the header from the buffer until the payload is removed as well.
The intent here is to make recovery after a dropped stream easier, by leaving the header in the stream such that the next reader sees a full message.

postgres: peek at header then take whole message

---

sqlx-core/src/pool/connection.rs
tests/any/pool.rs

This should alleviate some issues WRT cancellation (cc #563) as connections in an inconsistent state should not be recycled by `Pool`.
SQLx-next (0.6) will address the cancellation issue by ensuring connections remember all relevant state in order to resume where they left off.

fix(pool): always test connection on release to see if it's still viable

---

sqlx-macros/src/derives/decode.rs
sqlx-macros/src/derives/encode.rs
sqlx-macros/src/derives/row.rs
sqlx-macros/src/derives/type.rs

There's a lesser-known attribute called [#[automatically_derived]](https://doc.rust-lang.org/reference/attributes/derive.html#the-automatically_derived-attribute) that marks an `impl` block as "derived". Docs state it does nothing, but it actually [disables at least one lint](https://github.com/rust-lang/rust/commit/24d410abd6924c175ee776ed84be851b615a555b) to improve perf (can't find who wrote this where, but also seems not super important).

Mark derived impl blocks #[automatically_derived]

---

sqlx-mysql/src/protocol/auth_plugin.rs
sqlx-mysql/src/protocol/auth_plugin/dialog.rs

Same thing as #1062 but targeting `next`.
Encountered a mariadb server that only accepted [dialog](https://mariadb.com/kb/en/authentication-plugin-pam/#dialog) authentication (which seems typical if using mariadb's pam integration). This PR adds support for dialog authentication if the server is only asking for a password.
On my system I set up a mariadb server with basic pam authentication. When providing the correct password I am able to connect to the database and execute queries.
If I provide the wrong password I get this error:
```
[2021-02-28T00:28:46Z TRACE sqlx_core::io::buf_stream] read  [   4] > b"X\0\0\0"
[2021-02-28T00:28:46Z TRACE sqlx_core::io::buf_stream] read  [  88] > b"\n5.5.5-10.5.9-MariaDB\0*\0\0\09JHj^xbb\0\xfe\xf7\xe0\x02\0\xff\x81\x15\0\0\0\0\0\0\x0f\0\0\0Dlrw!:B{hs, …
```

Basic MySql dialog authentication support (attempt 2)

---

sqlx-core/src/pool/inner.rs

AtomicU32::compare_and_swap() is marked deprecated, in favor of compare_exchange().
compare_exchange() is fallible, so we continue to loop if it fails.
According to the docs, for the original AcqRel ordering, the equivalent failure ordering is Acquire.
https://doc.rust-lang.org/std/sync/atomic/struct.AtomicU32.html#method.compare_exchange_weak

replace deprecated compare_and_swap() with compare_exchange()

---

src/macros.rs

The link was broken since it used a singular "crate" in the URL.
Fix it by using "crates".

Fix `sqlx-cli` crate link

---

sqlx-core/src/pool/connection.rs
sqlx-core/src/pool/inner.rs
sqlx-core/src/pool/options.rs
tests/postgres/postgres.rs

* fix `DecrementSizeGuard::drop()` only waking one `Waiter` regardless of whether that waiter was already woken
* fix connect-backoff loop giving up the size guard
* don't cut in line to open a new connection
* have tasks waiting on `acquire()` wake periodically to check if there's a connection in the queue
@dignifiedquire do you mind testing this?
Signed-off-by: Austin Bonander <austin@launchbadge.com>

fix: pool internals improvements

---

sqlx-core/src/sqlite/options/auto_vacuum.rs
sqlx-core/src/sqlite/options/connect.rs
sqlx-core/src/sqlite/options/locking_mode.rs
sqlx-core/src/sqlite/options/mod.rs

This adds enums for the possible values of those two pragmas, and sets
them at connection time.
My primary motivation for this is that to get the full benefits of
locking_mode, it needs to be set *before* setting journal_mode.

Support the sqlite locking_mode and auto_vacuum pragmas

---

sqlx-core/src/io/buf_stream.rs

Fix bug when a read on a BufStream is cancelled.

---

sqlx-core/src/io/buf_stream.rs
sqlx-core/src/postgres/listener.rs
tests/postgres/postgres.rs

Fixes #612 
Includes changes from #1099 as they are a prerequisite.

Unlisten before releasing connections to the pool

---

sqlx-core/src/postgres/connection/describe.rs
tests/postgres/postgres.rs
tests/postgres/setup.sql

Fix commit updates the `postgres::connection::describe` module to add full support for domain types. Domain types were previously confused with their category which caused invalid oid resolution.
Fixes launchbadge/sqlx#110

fix(postgres): Add support for domain types description

---

sqlx-cli/src/lib.rs

sqlx database reset currenctly requires no confirmation and a
confirmation when -y flag is set. Should be the other way around
as it is for sqlx database drop. This commit fixes this.

sqlx-cli database reset fix confirmation flag

---

sqlx-core/src/connection.rs

The provided callback doesn't seem to need to be `'static`. It seems to be enough that it doesn't borrow anything from the `Connection` itself, even if it does borrow data from elsewhere.

Bounds on `Connection::transaction` are overly strict

---

sqlx-core/src/sqlite/statement/virtual.rs

64-bit pointers can't be casted to i32 correctly.
It does not seem to cause problems on amd64 as long as both pointers
reside in the same page, but it's not correct generally.

fix(sqlite): do not cast pointers to i32

---

sqlx-core/src/sqlite/connection/executor.rs
sqlx-core/src/sqlite/statement/handle.rs
tests/sqlite/sqlite.rs

Unlike `Executor.fetch_optional()`, `Executor.fetch_many()` does not
have a single exit.  The stream can be dropped at any time.  To catch
this event, we create a `StatementResetter` structure inside the stream
loop and reset the statement when it is dropped.
A test case `it_resets_prepared_statement_after_fetch_many` is
similar to `it_resets_prepared_statement_after_fetch_one` which tests
`Executor.fetch_optional()`.
Fixes #1147

fix(sqlite): reset the statement when fetch_many() stream is dropped

---

sqlx-core/src/net/tls/mod.rs
sqlx-core/src/postgres/types/array.rs
sqlx-core/src/sqlite/options/auto_vacuum.rs
sqlx-core/src/sqlite/options/locking_mode.rs
sqlx-core/src/types/json.rs
sqlx-rt/src/lib.rs

Notes on the first commit:
* This changes a few `panic!`s behaviors. I'm assuming not using a format string there was an oversight, rather than those panics really being meant to be catch-able as `std::io::Error`s.
* It looks like `enter_runtime` for tokio was actually wrong before, due to the runtime guard being dropped before calling the function argument.
About the second ("main") commit: I've only tested that the change of the slice implementation doesn't result in compilation errors, nothing more.

Remove `Self: Type` bounds in Encode / Decode implementations

---

sqlx-core/src/sqlite/mod.rs

This makes it possible to `use sqlx::sqlite::SqliteLockingMode`.

sqlite: export SqliteLockingMode

---

src/macros.rs

Noticed that the table looked weird in the `query!` documentation, so I wanted to add a fix.

Fix `query!` documentation of `.execute`

---

sqlx-cli/src/prepare.rs

Hi and thanks for sqlx!
While trying to generate a metadata file for a CI build via `cargo sqlx prepare`, I found the help message slightly confusing. I didn't have the offline feature enabled of course which was the problem, and my initial thought when I saw the message "no queries found; do you have the 'offline' feature enabled in sqlx?" was "I don't think so, I never even heard of that feature... There must be another problem..." at which point I started googling.
Eventually I realised I had understood the message the wrong way round and that I _needed_ the offline feature to make the metadata generation work :) This message change may (or may not!) help people to avoid the same confusion as me.
Thanks again

Try to make 'no queries found' message more clear

---

sqlx-core/src/sqlite/options/connect.rs
sqlx-core/src/sqlite/options/mod.rs

The page size setting only takes effect if set before doing anything
else to the database.

Support setting sqlite page_size

---

sqlx-cli/src/opt.rs

Executing `cargo sqlx database setup --help` produces the following output for me:
```
cargo-sqlx-database-setup 
Creates the database specified in your DATABASE_URL and runs any pending migrations
USAGE:
cargo sqlx database setup [OPTIONS]
FLAGS:
-h, --help       Prints help information
-V, --version    Prints version information
OPTIONS:
--source <source>    Path to folder containing migrations. Defaults to 'migrations'
[default: migrations]
```
In particular, two last lines have duplicated information about the default value. This PR removes the redundancy.

Remove redundant default hint in help

---

sqlx-core/src/sqlite/options/mod.rs

This makes it possible to open database in shared cache mode without
having to construct `sqlite://` URL with `?cache=shared` flag.

sqlite: add SqliteConnectOptions::shared_cache()

---

sqlx-core/src/pool/inner.rs
tests/postgres/postgres.rs

* a task that is marked woken but didn't actually wake before being cancelled will instead wake the next task in the queue
* a task that wakes but doesn't get a connection will put itself back in the queue instead of waiting until it times out with no way to be woken
* the idle reaper now won't run if there are tasks waiting for a connection, and also uses
the proper `SharedPool::release()` to return validated connections to the pool so waiting tasks get woken
closes #622, #1210
(hopefully for good this time)
Signed-off-by: Austin Bonander <austin@launchbadge.com>

more pool fixes

---

sqlx-core/src/types/mod.rs
src/macros.rs

First time contributing, so please point out if I missed a guideline!
When looking for information on how to add an enum to my schema, I stumbled across the derive macro for the `Type` trait and had to search a bit before finding the supported values for the `rename_all` attribute. This PR adds a link for people in the same situation :)
Also, I've fixed a typo that made the build fail, I hope it's okay to include this here, wasn't sure if a second PR was warranted for that.

Add docs for rename_all attribute for Type derive macro

---

sqlx-core/src/any/types.rs

Added support of decoding/encoding of bytes and `chrono::NaiveDateTime` in `any`.
Both are supported for `sqlite`, `postgres`, `mysql`, but not for `mssql`.

Added any types for binary blobs and chrono NaiveDateTime

---

sqlx-core/src/any/types.rs

Hello, a while back I put in a PR adding `Any` type support for `chrono` types. It seems I somehow missed that the `mysql` implementation supports `chrono::DateTime<chrono::types::Local>`. So this PR should add that support.

Adding Any support for Local chrono datetime for MySQL

---

Cargo.lock
sqlx-core/Cargo.toml

The latest webpki version bump results in some compilation failures when compiling sqlx-core when compiling with tokio-rustls, which depends on 0.21.4. For example:
```
error[E0308]: mismatched types
--> /home/etcaton/.cargo/registry/src/github.com-1ecc6299db9ec823/sqlx-core-0.5.3/src/net/tls/rustls.rs:73:39
|
72 |         match verifier.verify_server_cert(roots, presented_certs, dns_name, ocsp_response) {
|               ---------------------------------------------------------------------------- this expression has type `std::result::Result<ServerCertVerified,
TLSError>`
73 |             Err(TLSError::WebPKIError(webpki::Error::CertNotValidForName)) => {
|                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `webpki::error::Error`, found enum …
```

Revert webpki version bump to keep compatability with tokio-rustls

---

sqlx-macros/src/query/mod.rs

A recursive reference to a Lazy<Metadata> in its own initializer leads to a hanging compile.
The regression was introduced in #1184, and seems to also be experienced by the commenter [here](https://github.com/launchbadge/sqlx/issues/1239#issuecomment-846481571) complaining about a hang.

Fix infinite compile loop regression from recursive Lazy reference

---

sqlx-macros/src/query/args.rs

Fixes #1263
Hi @abonander, how does this look?
Let me know if this needs any changes.
Thanks

Rename _expr to expr

---

sqlx-macros/src/query/mod.rs

Fixes #1272.
Maybe not the best way to word this? Should I list all 8 macros w/o `_as` explicitly?

Fix error message about wildcard overrides

---

sqlx-core/src/mysql/types/chrono.rs

This should also fix the CI errors for MySQL.
closes #1222

fix(mysql): implement type traits for `chrono::DateTime<Local>`

---

sqlx-core/src/sqlite/connection/explain.rs
tests/sqlite/describe.rs

(This was specifically made for and tested against #1246 but it may solve other issues as well)
This pr changes the SQLite EXPLAIN parsing to keep track of the types of each column that the query modifies. This allows typechecking on queries that insert into a row, and then later read back that row for its returning columns. I've tested this against `RETURNING` clauses on `INSERT` statements, which is where I was running into my issue with typechecking, but this might resolve other issues with typechecking on similar queries.

Keep track of column typing in SQLite EXPLAIN parsing

---

sqlx-core/src/postgres/types/money.rs

handle negative values correctly in `PgMoney::from_decimal()`

---

sqlx-macros/src/query/mod.rs
sqlx-macros/src/query/output.rs

fix(macros): prefix generated variable names in `query_as!()`

---

sqlx-rt/src/lib.rs

I have a use-case where I create an SQLite connection pool in a tokio threaded runtime, and then create a task that inserts rows to the DB in an infinite loop, and also create an actix web server which upon requests, performs queries on the DB using the same connection pool.
The task that inserts works without problem, but the actix workers panic with `"can call blocking only when running on the multi-threaded runtime"` when they try to establish a new connection via the pool. This happens because `block_in_place` tries to convert the actix worker thread into a tokio blocking thread. It doesn't matter whether or not the actix runtime I create uses an underlying tokio threaded runtime or current thread runtime.
Changing it into `spawn_blocking` solves the problem because now the actix …

Use tokio `spawn_blocking` instead of `block_in_place`

---

sqlx-core/src/error.rs

I bumped into this limitation by chance and it seemed easy enough to fix.
Curious to know if there was a reason behind the omission or if it simply wasn't noticed.

Mark the original DatabaseError as source.

---

sqlx-core/src/postgres/migrate.rs

As described in #1283, currently when trying to create multiple databases in parallel, `sqlx::Postgres::create_database` will fail with the error message `source database "template1" is being accessed by other users`.
@li-kai did already find the cause of this. The function `parse_for_maintenance` is meant to emulate the behavior of the `createdb` util, but uses the username instead of the database. This PR fixes that.
I did not run extensive tests, but it works without issues on my project.

Use postgres as maintenance db unless maintaining postgres itself

---

Cargo.lock
sqlx-core/Cargo.toml

avoid regression rust-lang/rust#85574
this will fix build for PR #1351 #1352

build(deps): bump git2 from 0.13.19 to 0.13.20

---

Cargo.lock
Cargo.toml
examples/postgres/transaction/Cargo.toml
examples/postgres/transaction/README.md
examples/postgres/transaction/migrations/20200718111257_todos.sql
examples/postgres/transaction/src/main.rs
src/macros.rs

This adds two things I was looking for while getting to know sqlx. 
I wasn't sure which `Notes` to add to the `fetch_all()` rows, please tell me anything you'd like to see mentioned there.

Add docs for fetch_all, example for postgres transactions

---

sqlx-macros/src/query/mod.rs

Workaround for https://github.com/launchbadge/sqlx/issues/1229, in which running `cargo fix` when using sqlx in offline mode breaks because `cargo` acts differently when being called under `cargo fix`.
The workaround is to unset the `__CARGO_FIX_PLZ` environment variable that is set by `cargo fix`. This should make `cargo metadata` work as normal.

Fix cargo fix bug with sqlx offline mode

---

sqlx-core/src/postgres/connection/executor.rs
tests/docker-compose.yml
tests/postgres/postgres.rs
tests/x.py

After investigation, the root cause of #1254 is:
- `apply_patches` may cause another query to execute
- `fetch_optional` won't consume all messages until ready
- after bind and execute, we will receive the unconsumed messages which causes the  `unexpected message` error in stream

Fix bug for PostgreSQL if the statement has type holes

---

Cargo.lock
sqlx-cli/Cargo.toml

When `clap_derive 3.0.0-beta.4` released, new invocations of `cargo install sqlx-cli` would try to compile that against `clap 3.0.0-beta.2` which caused some breakages.
Until `clap 3.0.0` proper is released, we need to pin both versions to insure against potential breakages from automatic upgrades.
closes #1378

fix(cli): pin `clap_derive` version

---

sqlx-core/src/postgres/connection/describe.rs
sqlx-core/src/postgres/message/parameter_status.rs

CockroachDB currently can't handle explain with verbose and json params, so query! wasn't working .
If crdb_version exists in parameter_statuses  it doesn't use nullables_from_explain function.

Fix macro error with CockroachDB

---

sqlx-macros/src/query/input.rs

fixes #1387
@AtkinsChang does this fix the regression?

fix(macros): use `resolve_path` when getting path for `include_str!()`

---

sqlx-core/src/pool/connection.rs
sqlx-core/src/postgres/listener.rs

refactor(pool): deprecate `PoolConnection::release()`, provide renamed alts
closes #1389

fix(postgres): avoid recursively spawning tasks in `PgListener::drop()`

---

sqlx-cli/src/lib.rs
sqlx-cli/src/opt.rs

closes #1391 
bit of churn in the diff but it's just moving `database_url` to the subcommands which actually use it.

fix(cli) move database_url

---

Cargo.lock
sqlx-cli/Cargo.toml
sqlx-cli/src/database.rs

Use promptly instead of dialoguer

---

sqlx-core/src/pool/connection.rs
sqlx-core/src/postgres/listener.rs
sqlx-rt/src/lib.rs

Fixing #1389 by explicitly asking for a `handle` to spawn the future in `Drop`.
Because of the `Runtime` being unavailable when application stops, it prevent a panic when trying to spawn a futur in a shutting down runtime.
Signed-off-by: Freyskeyd <simon.paitrault@gmail.com>

Postgres connection : Getting current Handle in Drop

---

sqlx-macros/src/query/mod.rs

In particular building with bazel and cargo-raze doesn't imply having
cargo at all, and deferring the lookup allows same-crate builds to
succeed with no change to semantics.
Fixes #1414
Signed-off-by: Robert Collins <robert.collins@cognite.com>

Don't require cargo to build offline queries

---

sqlx-core/src/any/mod.rs
sqlx-core/src/mssql/mod.rs
sqlx-core/src/mysql/mod.rs
sqlx-core/src/postgres/mod.rs
sqlx-core/src/sqlite/mod.rs
src/lib.rs

Simple convenience improvement.

Add executor trait "aliases"

---

sqlx-core/src/connection.rs
sqlx-core/src/mysql/options/mod.rs
sqlx-core/src/postgres/options/mod.rs
sqlx-core/src/sqlite/options/mod.rs

Currently everything is output to `Info` by default, this seems sub-optimal as in real world situations you do not need to constantly see every time a query happens, it is debugging and probably better suited to go there by default. I made `LogSettings` public too so people can override this behavior as wanted.
Thanks,
Elise
🖤

feat: allow log level customization

---

sqlx-macros/src/derives/attributes.rs

This allows users to do
```rust
#[derive(sqlx::Type)]
#[repr(transparent)]
pub struct MyType(String);
```
p.s The error this throwed was very unfriendly.
`error: unexpected #[repr(..)]`
with no hint as to why that's not allowed or why its enforced.

don't assert #[repr(...)] on `#[derive(sqlx::Type)]` unless needed

---

Cargo.lock
sqlx-core/Cargo.toml
sqlx-macros/Cargo.toml

`futures-util` enables the `async-await-macro` feature by default, which imports `futures-macro`, `proc-macro-hack` and `proc-macro-nested`. Those features are unnecessary and slow to compile.

Reduce futures-util features

---

sqlx-cli/src/bin/cargo-sqlx.rs
sqlx-cli/src/bin/sqlx.rs
sqlx-cli/src/lib.rs

This PR fixes the problem identified in #1431: currently, environmental variables set in `.env` are not detected in `sqlx database ...` commands.
This problem is a regression caused by commit 0e51272 which was part of issue #1391.
`dotenv()` must execute before clap's `get_matches()`

Fix issue #1431

---

sqlx-core/src/postgres/types/ipnetwork.rs

Fixes querying postgres columns of `CIDR[]` into a `Vec<IpNetwork>`. Inspired by the [bit_vec integration](https://github.com/launchbadge/sqlx/blob/b6e127561797fe9aababa24ec640275ecb9b42af/sqlx-core/src/postgres/types/bit_vec.rs#L28)

Fix CIDR[] not being compatible with Vec<IpNetwork>

---

sqlx-core/src/sqlite/connection/establish.rs
sqlx-core/src/sqlite/options/mod.rs
sqlx-core/src/sqlite/options/parse.rs

This fixes https://github.com/launchbadge/sqlx/issues/987
This is working for us, but I admit I have not thought carefully about how it interacts with other options. Open to feedback on the PR.

Support the immutable option on SQLite connections

---

README.md

I did manual checks for some of the other backends:
* PostgreSQL requires `$1`
* MySQL requires `?`
* SQLite is fine with either `$1` or `?`

docs: added a note about MySQL syntax in the README example

---

sqlx-core/src/mysql/connection/executor.rs
sqlx-core/src/mysql/connection/mod.rs
sqlx-core/src/mysql/connection/stream.rs
sqlx-core/src/mysql/transaction.rs
tests/mysql/mysql.rs

This PR changes the state of unread query results from single value to queue. It's similar to pending_ready_for_query_count in PgConnection.
This should fix the panic described in #1078 and #1358.
The reason of panic is MySqlStream cannot handle multiple pending queries. In #1358 situation, there's two unread results:
1. The result of `SELECT 1` isn't fully read because fetch_one() only reads until the first row
2. `ROLLBACK` is pushed to wbuf when transaction is dropped
3. wbuf is sent to MySQL in the next wait_until_ready() phase
4. Here, there's two unread results: `SELECT 1` and `ROLLBACK`. wait_until_ready() didn't handle this situation correctly.
So I changed `busy` state to a queue. In my environment, #1358 example runs without panic.

fix(mysql): handle multiple waiting results correctly

---

Cargo.lock
sqlx-core/src/sqlite/connection/executor.rs
sqlx-core/src/sqlite/connection/handle.rs
sqlx-core/src/sqlite/connection/mod.rs
sqlx-core/src/sqlite/row.rs
sqlx-core/src/sqlite/statement/handle.rs
sqlx-core/src/sqlite/statement/mod.rs
tests/sqlite/sqlite.rs

Was able to cut the example given in #1419 down to a nice minimal repro.
Closes #1419

Fix a panic in the worker thread when dropping the connection while `SqliteRow`s still exist

---

sqlx-core/src/sqlite/connection/mod.rs
sqlx-core/src/sqlite/statement/worker.rs
tests/sqlite/sqlite.rs

In my testing at least, this fixes #1452
I would prefer for the `StatementWorker::shutdown` method to take `mut self`, but that would require additional changes.

Shut down statement worker in Sqlite Connection::close

---

sqlx-core/src/connection.rs
sqlx-core/src/mysql/options/mod.rs
sqlx-core/src/postgres/options/mod.rs
sqlx-core/src/sqlite/options/mod.rs

This reverts commit 719d80038b2f685ab52ce15bb15e953f1f162b42.
@EliseZeroTwo we already support setting these options if you import the `ConnectOptions` trait: https://docs.rs/sqlx/0.5.7/sqlx/trait.ConnectOptions.html
I should have taken a closer look at your PR, sorry. It ended up being redundant.

Revert "feat: allow log level customization (#1371)"

---

sqlx-core/src/sqlite/types/chrono.rs

Hi, I encountered this problem while using `sqlx ^0.5`.
> hread 'main' panicked at 'a Display implementation returned an error unexpectedly: Error', /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/alloc/src/string.rs:2380:14
https://github.com/SeaQL/sea-orm/pull/207/checks?check_run_id=3728117667#step:5:212
After digging into the source code...
- I think there is a typo, `%T%.f%` should be `%T%.f`
https://github.com/launchbadge/sqlx/blob/6e1c7a999a514be2df809f36f26bd5758b96c448/sqlx-core/src/sqlite/types/chrono.rs#L77-L81
- And, considering `NaiveTime` is encoded into a string with format `%T%.f`. Decoding it from string should also parse from the same format, i.e. `%T%.f`. However, it's not.
https://github.com/launchbadge/sqlx/blob/6e1c7a999a514be2df809f36f26bd5758b96c448/sqlx-cor …

[SQLite] encoding & decoding `NaiveTime` with correct format

---

sqlx-cli/README.md

Hello! Thanks for working on SQLX: it's been a great library to include in our own projects. 
Today, while I was adding migrations to a new project for the first time (previously we were using another solution), I found that it took some digging to understand how to _revert_ migrations. I thought that I might try to save other people from having to investigate this themselves by adding a note to the README on reverting migrations. No worries about rejecting this if this doesn't fit with your plans for the project: I just thought it might be helpful for others.

Add reverting instructions to README

---

sqlx-core/src/sqlite/connection/establish.rs
sqlx-core/src/sqlite/options/mod.rs

Currently, sqlx starts up in multi-threaded threading mode by default for sqlite, and attempts to maintain the invariants required for this (not using the same connection on multiple threads). We have encountered a situation where this was causing errors (on iOS, specifically, we are still unsure why only this platform seems effected), and verified this was resolved by switching to the serialized threading mode. This change weakens invariants at the cost of performance, and is something that could be configurable through the connection options (with the default still being to use multi threaded mode rather than serialized).
From what we can tell, diesel will use the default connection mode (serialized), thus this error started presenting itself when we migrated from diesel to sqlx.

Add support for serialized threading mode to sqlite

---

sqlx-core/src/query_as.rs
sqlx-core/src/query_scalar.rs

Add persistent setter (#1503)

---

sqlx-core/Cargo.toml

Ok, this is a very niche problem, but important in my particular case, and I think the change shouldn't have any impact to anyone else. I'm just submitting a PR with no prior discussion since it's just a one-line change, but I'm happy to discuss further if you have concerns.
My project depends on both `deno_core` and `sqlx`, and [Deno requires `=1.6.2` of `indexmap`](https://github.com/denoland/deno/blob/004d07dccd69c9fae8370665632d90401f770938/core/Cargo.toml#L18) to work around some circular dependency problem in dependencies.
With the recent addition of `indexmap = "1.7.0"` to sqlx, I can no longer include both crates at the same time since Cargo refuses to resolve two different versions of a crate if those versions are semver-major-compatible. 
I initially intended to just stay on …

Reduce indexmap version requirement to 1.6.2

---

sqlx-core/src/postgres/types/range.rs
tests/postgres/types.rs

I'm about to test if this works, but it should be fine, I believe, who knows!
I wish there weren't two decimal crates.

fix(postgres): allow rust_decimal::Decimal in PgRange

---

FAQ.md

Thanks to @jplatte in the sqlx Discord for providing this solution.

Update FAQ to include building on docs.rs

---

sqlx-core/src/postgres/types/interval.rs

* resolves https://github.com/launchbadge/sqlx/issues/736
* adds related unit tests
How I dealt with corner cases follows existing comments (for [std::time](https://github.com/launchbadge/sqlx/blob/65222a62aaf7485a06c33c8ec71fe51b73a45a6a/sqlx-core/src/postgres/types/interval.rs#L103-L104), [chrono](https://github.com/launchbadge/sqlx/blob/65222a62aaf7485a06c33c8ec71fe51b73a45a6a/sqlx-core/src/postgres/types/interval.rs#L150-L151), [time](https://github.com/launchbadge/sqlx/blob/65222a62aaf7485a06c33c8ec71fe51b73a45a6a/sqlx-core/src/postgres/types/interval.rs#L189-L190)).
*I'm a newcomer to this repo. If I had anything inappropriate, it would be great if you point it out.*

fix panic when converting negative chrono::Duration into PgInterval

---

src/macros.rs

As in the topic.
The structure of the `./migrations` directory is not mentioned anywhere in the `migrate!` macro documentation. The user has to go to the `Migrator` page first to discover that, and it isn't indicated anywhere that they have to do so.

Include a reference to the shape of the migration files in the migrate macro documentation

---

sqlx-core/src/postgres/copy.rs
sqlx-core/src/postgres/mod.rs

Copy API improvement (#1536)

---

Cargo.lock
sqlx-core/Cargo.toml

This PR bumps libsqlite3-sys to the latest version.

bump libsqlite3-sys to 0.23.1

---

sqlx-core/src/any/kind.rs
sqlx-core/src/pool/mod.rs

This PR addresses https://github.com/launchbadge/sqlx/issues/1225
It adds a `get_kind` method to `Pool`, going through `SharedPool` and `ConnectionOptions` to get the (dynamic for `Any`) type of the connection.
This will allow query builders to build the query based on which driver (and so which dialect) is used.
Note: The `sqlx-core/src/any/kind.rs` was moved to `sqlx-core/src/any_kind.rs` because it's now needed for every DB, so it shouldn't be guarded by the `any` feature.
I didn't add any tests, because I'm not entirely sure where to add them, and there is not really any logic to test. The test (if any) should probably only check the interface, maybe in a test where we have a `&any_pool` and we check its `.get_kind()`?

Add a `get_kind` method to Pool

---

sqlx-core/src/postgres/mod.rs
sqlx-core/src/postgres/types/array.rs
sqlx-core/src/postgres/types/bigdecimal.rs
sqlx-core/src/postgres/types/bit_vec.rs
sqlx-core/src/postgres/types/bool.rs
sqlx-core/src/postgres/types/bytes.rs
sqlx-core/src/postgres/types/chrono/date.rs
sqlx-core/src/postgres/types/chrono/datetime.rs
sqlx-core/src/postgres/types/chrono/time.rs
sqlx-core/src/postgres/types/decimal.rs
sqlx-core/src/postgres/types/float.rs
sqlx-core/src/postgres/types/int.rs
sqlx-core/src/postgres/types/interval.rs
sqlx-core/src/postgres/types/ipnetwork.rs
sqlx-core/src/postgres/types/json.rs
sqlx-core/src/postgres/types/mac_address.rs
sqlx-core/src/postgres/types/mod.rs
sqlx-core/src/postgres/types/money.rs
sqlx-core/src/postgres/types/range.rs
sqlx-core/src/postgres/types/str.rs
sqlx-core/src/postgres/types/time/date.rs
sqlx-core/src/postgres/types/time/datetime.rs
sqlx-core/src/postgres/types/time/time.rs
sqlx-core/src/postgres/types/tuple.rs
sqlx-core/src/postgres/types/uuid.rs

… to reduce boilerplate and allow custom types.
~~Fixes~~ Relates to #298.
Future possibilities: Let the `Type` derive macro generate an impl of the new `PgHasArrayType` trait.

Rewrite Postgres array type handling

---

sqlx-core/Cargo.toml

sqlx-core uses whoami to provide the fallback for postgres username. If
not building postgres support, omit the dependency on whoami.

Make whoami optional, and only pull it in for postgres

---

sqlx-cli/src/prepare.rs

This fixes #1579 .
Running `sqlx prepare --merged` should respect existing `RUSTFLAGS` set in the environment.
This change will append to the variable instead of overwriting it.

Append to existing RUSTFLAGS, instead of overwriting.

---

sqlx-core/src/postgres/options/mod.rs
sqlx-core/src/postgres/options/parse.rs
sqlx-core/src/postgres/options/pgpass.rs

This fixes two bugs in loading postgres passwords from `~/.pgpass` files:
- pgpass was applied before parsing the database URLs so it wasn't matching against  the host/port/user/database from the URL provided
- pgpass was matching user and database in the wrong order

fix(postgres): Match `~/.pgpass` password after URL parsing and fix user and database ordering

---

sqlx-core/src/lib.rs
src/lib.rs

Subj
It is convenient when you need to implement own Executor
`sqlx-core` is also would be nice to have available for `describe::Describe`

Reimport Either used in Executor

---

sqlx-core/src/postgres/types/array.rs
sqlx-core/src/postgres/types/record.rs
tests/postgres/postgres.rs

This is a fix for #1504 which makes `produces()` override `type_info()` when possible.

Postgres: Array enum encoding

---

sqlx-core/src/postgres/connection/describe.rs
sqlx-core/src/postgres/type_info.rs
sqlx-core/src/postgres/types/array.rs
tests/postgres/postgres.rs

This commit fixes the array decoder to support custom types. The core of the issue was that the array decoder did not use the type info retrieved from the database. It means that it only supported native types.
This commit fixes the issue by using the element type info fetched from the database. A new internal helper method is added to the `PgType` struct: it returns the type info for the inner array element, if available.
Closes #1477

Fix support for Postgres array of custom types

---

sqlx-core/src/postgres/connection/establish.rs
sqlx-core/src/postgres/mod.rs
sqlx-core/src/postgres/options/mod.rs
sqlx-core/src/postgres/options/parse.rs

This Pull Request allows you to specify extra command options to the PostgreSQL server through connection options like search path and statement timeouts etc.
This could fix #1290.

feat(postgres): add an option to specify extra options

---

sqlx-cli/Cargo.toml
sqlx-cli/README.md

Pretty simple Cargo change to allow the CLI to use Rustls instead.  It still defaults to native-tls, so should be transparent to users!

[CLI] Adds feature enabling Rustls usage rather than OpenSSL

---

CHANGELOG.md
Cargo.lock
Cargo.toml
sqlx-cli/Cargo.toml
sqlx-cli/src/bin/cargo-sqlx.rs
sqlx-cli/src/bin/sqlx.rs
sqlx-cli/src/opt.rs
sqlx-core/Cargo.toml
sqlx-macros/Cargo.toml
sqlx-rt/Cargo.toml
tests/sqlite/sqlite.rs

I got lazy when I wrote the changelog for 0.5.8 and didn't list all the PRs, and some folks were disappointed that their PR wasn't listed. So listing all 31 for this release cycle!

Prepare 0.5.10 release

---

sqlx-core/src/sqlite/connection/worker.rs

Related to previous issue #1452

Drop worker shared state in shutdown (Sqlite)

---

sqlx-core/src/postgres/connection/stream.rs

Adds a `target` field to the Postgres notice logs and filters based on that target. This makes it similar to how the query logs [have a `target` field](https://github.com/launchbadge/sqlx/blob/49928ddf81fe99137c565aa1ef43fd67282ee902/sqlx-core/src/logger.rs#L64) and [filter based on target](https://github.com/launchbadge/sqlx/blob/49928ddf81fe99137c565aa1ef43fd67282ee902/sqlx-core/src/logger.rs#L36).

Add target context to Postgres notice logs

---

sqlx-core/Cargo.toml
sqlx-core/src/sqlite/statement/handle.rs
tests/sqlite/sqlite.rs

This PR implement unlock notification to avoid `SQLITE_LOCKED` ("database table is locked") errors when running concurrent queries. The implementation is basically rustified version of the example from the official sqlite docs on https://www.sqlite.org/unlock_notify.html.
Closes #1649

SQLite unlock notification

---

sqlx-cli/src/migrate.rs

This fixes #870
Tested this manually locally:

Add checksum mismtaches to sqlx-cli migrate info

---

sqlx-core/src/mysql/connection/stream.rs

I'm having panics on those index accesses, an empty packet is probably a symptom of other problems, but it would be cool if the application doesn't panics like it does.

Avoid panicking if packet empty

---

Cargo.lock
sqlx-cli/Cargo.toml
sqlx-cli/src/bin/cargo-sqlx.rs

Updates clap to the official 3.0 release and removes workarounds for the cargo subcommand in favor of a simple enum Parser with the added `bin_name = "cargo"` setting.
This makes clap **think** the binary is called `cargo` and has only the `sqlx` subcommand, so the help output is unchanged.

Simplify cargo-sqlx cmdline definition

---

README.md

Changing this build setting made `cargo check` over twice as fast on a project I work on. I didn't see this mentioned anywhere in the documentation for this project, so I figured it was worth adding a note

Make a note about sqlx macros opt level

---

sqlx-macros/src/query/data.rs

I didn't delve too much into how things are used, but from what I can tell when using the offline data cache each compile-time verified query will parse the entire `sqlx-data.json` file. This change switches to caching the parsed `sqlx-data.json` files in a two-layer cache where the first layer is keyed by the path to `sqlx-data.json` (since there can be multiple) and the second layer is keyed by the query hash.
This did involve changing some of the types returned for errors since this now uses `String`s instead of `serde::de::Err::custom`. I didn't think this was a huge issue since the error type is a `Box<dyn std::error::Error>`.
_Note: the numbers here are ballpark around what I see at work. We have a workspace with over 200 queries that uses `--merged` to create a workspace level …

refactor: Keep parsed `sqlx-data.json` in a cache instead of reparsing

---

sqlx-core/src/any/mod.rs

With macro impl_encode_for_option Null values are not added, when creating arguments for the actual driver selected at runtime.
Fixes #772 
Fixes #1407

Fix Option for Any driver.

---

src/macros.rs

removing the sentences `the expression which is not possible as the macros are currently implemented.` 'cause it's confusing, which is referred in #1133.

docs(macros): remove sentences banning usage of `as _`

---

examples/postgres/transaction/src/main.rs

This fixes the missing await? mentioned in https://github.com/launchbadge/sqlx/issues/1631 and extends the example to include a case of explicit rollback, implicit rollback via drop of the transaction object and commit each.

fix and extend postgres transaction example

---

Cargo.lock
sqlx-core/Cargo.toml
sqlx-core/src/acquire.rs
sqlx-core/src/sqlite/options/mod.rs

Tried to summarize my findings around `Acquire` from
- https://github.com/launchbadge/sqlx/issues/1635
- https://github.com/launchbadge/sqlx/issues/1686
- https://github.com/launchbadge/sqlx/issues/1015#issuecomment-767787777
as doc examples so others might have an easier start.

docs: Acquire examples and alternative

---

sqlx-core/src/postgres/types/json.rs
sqlx-core/src/postgres/types/mod.rs
sqlx-core/src/types/json.rs

Fixes #1721. 
This adds `PgHasArrayType` for `serde_json::Value` and `serde_json::RawValue`, so that they can be bound to queries again.

Impl PgHasArrayType for serde_json::{Value,RawValue}

---

sqlx-core/src/postgres/options/mod.rs

This pull request should fix #1730, an issue introduced in #1539. The fixed logic is based on https://github.com/launchbadge/sqlx/issues/1730#issuecomment-1055914196.
A unit test has been added to ensure the formatting logic is correct this time.
I apologize for any inconvenience caused by the previous incorrect implementation.

fix(postgres): fix option passing logic

---

sqlx-cli/src/prepare.rs

Currently `cargo sqlx prepare` doesn't pass the database url value to the child command spawned for `sqlx-macros`.
```cmd
$ DATABASE_URL="..." cargo sqlx prepare
```
works as expected because `sqlx-macros` will read the value from the env var which is inherited, but
```cmd
$ cargo sqlx prepare --database-url "..."
```
will fail in some way (An existing `sqlx-data.json` makes it not fail, but causes it to find no queries. No existing `sqlx-data.json` will lead to a `error: failed to find data for query`) because the database url isn't being passed to the child process.
It's also worth noting that these changes appear to obey precedence correctly too where
```cmd
$ DATABASE_URL="A" cargo sqlx prepare --database-url "B"
```
will lead to `"B"` being used which should be right. I wasn't …

Pass the `DATABASE_URL` to command spawned for `sqlx-macros`

---

sqlx-core/src/mssql/types/str.rs
sqlx-core/src/mysql/types/str.rs
sqlx-core/src/sqlite/types/str.rs

I saw that #1343 added Encode/Decode impls for `Cow<str>` for all databases, but `Type` was only implemented on Postgres.
This change adds the missing `Type` impls for the remaining databases (which forward calls to the `&str` implementations).

sqlx-core: impl Type for Cow<str> on Mssql, MySql, and Sqlite

---

sqlx-macros/src/derives/type.rs
tests/postgres/derives.rs

Fixes #1744.
I'm not sure if the bounds are correct and complete or not, but this compiles now.

Derive PgHasArrayType for transparent sqlx types

---

Cargo.lock
sqlx-core/Cargo.toml
sqlx-core/src/pool/connection.rs
sqlx-core/src/postgres/advisory_lock.rs
sqlx-core/src/postgres/connection/mod.rs
sqlx-core/src/postgres/mod.rs
sqlx-core/src/postgres/transaction.rs
tests/postgres/postgres.rs

While working on a Launchbadge project, I realized I needed a way to provide mutual exclusion synchronized with the database so that multiple instances of a server application don't try to perform the same side-effecting operation, but the locking scheme I wanted didn't fit neatly onto standard row- or table-level locking.
[I excitedly remembered that Postgres has advisory locks with application-defined semantics](https://www.postgresql.org/docs/current/explicit-locking.html#ADVISORY-LOCKS), but quickly realized they were somewhat unwieldy to use for our purposes.
There's transaction-scoped advisory locks, which would work well except that because I was doing side-effecting operations, I wanted the updates I was making to the database to be published immediately, and it seemed …

feat: convenient wrapper for Postgres advisory locks

---

sqlx-core/src/postgres/connection/establish.rs
sqlx-core/src/postgres/options/mod.rs

closes #1074
addresses https://github.com/launchbadge/sqlx/issues/801#issuecomment-1081267780
I didn't really want to spend much time figuring out what version string Redshift returns, and according to the comment on #801 above, even certain versions of Postgres 10 don't support the `extra_float_digits` option, so that just generally sounded like a rabbit hole I didn't want to go down.
Supercedes #1746 (I wanted to editoralize the documentation on the method and also make it take `Option` and that point it was just easier to open a new PR rather than try to adjust that one)

feat(postgres): make `extra_float_digits` settable

---

sqlx-macros/src/database/postgres.rs

Updates macros for postgres to support arrays and ranges for `numeric` type using `decimal` feature.
The implementation just follows `bigdecimal` feature and adds the missing parts.
Fixes #1778

Support `NUMERIC[]` using `decimal` feature

---

sqlx-core/src/sqlite/options/auto_vacuum.rs
sqlx-core/src/sqlite/options/journal_mode.rs
sqlx-core/src/sqlite/options/locking_mode.rs
sqlx-core/src/sqlite/options/synchronous.rs

Just filling out these implementations for consistency and convenience.

Add FromStr, Copy, PartialEq, Eq impls for Sqlite options

---

sqlx-core/src/mysql/protocol/connect/handshake.rs
sqlx-core/src/mysql/protocol/statement/prepare_ok.rs
sqlx-core/src/mysql/protocol/text/column.rs

Not sure if there is a better way to go about this, but the sheer number of warnings generated on the CI makes it difficult to spot any new ones that show up.

(mysql) Silence warnings for unused fields

---

Cargo.lock
sqlx-core/Cargo.toml
sqlx-core/src/pool/inner.rs
sqlx-core/src/pool/mod.rs
sqlx-core/src/postgres/listener.rs
tests/postgres/postgres.rs

fix(postgres): integrate pool close-event into `PgListener`
closes #1764
cc @dbeckwith

feat(pool): implement close-event notification

---

sqlx-core/src/sqlite/connection/explain.rs
tests/sqlite/describe.rs

Populate column datatypes for a cursor reading from table/index blocks in the main database by parsing sqlite table/index pragmas.  Having that data available allows the Column opcode to map r_cursor correctly, which in turn allows NullRow opcode to clear the correct registers.

Fix #1249 Left joins in SQLite can break the query macros

---

sqlx-core/src/migrate/migrator.rs

Right now, there is only a `run` function to programatically run the
migrations, which is great, but nothing to run the migrations down.
This function adds the possibility to undo the migrations until a
specific version (could say -1 or 0 to remove them all).
With this feature, it's now possible, in the end to end or integration
tests to run the migrations and undo them between each test set and
therefore test the migrations themselves.
This is the kind of feature that some ORM have like sequelize in nodejs
that allow you to undo migrations programatically.
Reference to the doc:
https://sequelize.org/v7/manual/migrations.html#undoing-migrations
Signed-off-by: Jérémie Drouet <jeremie.drouet@gmail.com>

feat(migration): add function to undo migrations

---

sqlx-core/src/logger.rs
sqlx-core/src/mssql/connection/executor.rs
sqlx-core/src/mssql/protocol/type_info.rs
sqlx-core/src/mysql/connection/executor.rs
sqlx-core/src/postgres/connection/executor.rs
sqlx-core/src/sqlite/connection/execute.rs

Closes https://github.com/launchbadge/sqlx/issues/1570 (or at least will do once it's finished)
This is just a quick PoC, only affecting sqlite for now, but I'd be happy to flesh this out if you think this is a reasonable approach.
Since this is hard to test I made a little demo app here to explore how this interacts with, in particular, transactions and COMMIT statements: https://github.com/david-mcgillicuddy-moixa/sqlx-log-test

Include affected rows in logging even when query is done

---

sqlx-core/src/postgres/options/pgpass.rs

When parsing `pgpass` files, the BufReader's `read_line` function is used which does not strip \n or \r. To handle this, a substring was created that strips out the last character (`&line[..line.len() - 1]`)
This behavior fails in two cases:
1. If the file uses \r\n instead of just \n
2. If the file has no trailing newline
Case (2) is subtle because it means if you modify your pgpass to add a new entry and forget to add a trailing newline to your file, `[..line.len() - 1]` will cut off the last letter of your password (ex: `hunter12` -> `hunter1`) giving you an authentication error.
Two options:
1. Similar to my PR, we manually strip the newline characters from the end of the string
4. We switch from the `read_line` to the `lines` method which strips the newline characters for you (I …

Fix newline parsing in pgpass

---

sqlx-core/src/pool/connection.rs
sqlx-core/src/pool/inner.rs
sqlx-core/src/pool/options.rs

fix(pool): don't leak connections if drop task doesn't run

---

sqlx-core/Cargo.toml

git2-rs recently updated major versions due to libgit2 doing the same.
Bump the version used in sqlx accordingly, to allow users of the new
git2 to use git2::Oid with sqlx.

Update git2 to 0.14

---

sqlx-core/src/sqlite/types/chrono.rs
sqlx-test/src/lib.rs
tests/sqlite/types.rs

Sqlite chrono::DateTime<FixedOffset> timezone fix

---

sqlx-core/src/connection.rs

Currently all `ConnectOptions` implementation are `Clone`. I think this will continue to be true, and it might be useful to give this guarantee in general.

Make all ConnectOptions clonable

---

Cargo.lock
Cargo.toml
sqlx-core/Cargo.toml
sqlx-core/src/mysql/types/time.rs
sqlx-core/src/postgres/types/time/date.rs
sqlx-core/src/postgres/types/time/datetime.rs
sqlx-core/src/postgres/types/time/mod.rs
sqlx-core/src/postgres/types/time/time.rs
sqlx-core/src/postgres/types/time_tz.rs
tests/mysql/types.rs
tests/postgres/types.rs

Continuation of #1444
Still left to do:
Closes #1277

Upgrade to time 0.3

---

Cargo.lock
sqlx-core/Cargo.toml

The current release of num is 0.4. Without this change to use BigDecimal with sqlx you need to intentionally use an older version of num and BigDecmial.

Update BigDecimal dependency

---

Cargo.lock
sqlx-core/src/postgres/types/ltree.rs

Previously the function took strings and parsed them into PgLTreeLabel internally, now it's possible to directlry push PgLTreeLabels onto a PgLTree.
It was a bit awkward that pop and push returned different types

Make PgLTree::push infallible and take PgLTreeLabel directly.

---

sqlx-macros/src/query/mod.rs

When using compile-time queries in a workspace with a single `sqlx-data.json` file in the workspace root the  following code is run to get the path to the workspace root. Because we only need the workspace root we can ignore dep information which ends up being a small, but significant change
I setup a minimal test environment with a single crate in a workspace. Here are the timings of an incremental unchanged `cargo check`
| `master` (ec15f6b30c3eba483a1aff508d3f46fbbb7b7134) | PR (a4536c829c64d2636451a2f6e5bf2ce3c311e00d) | Diff |
| :---: | :---: | :---: |
| 228.4 ms ± 1.8 ms | 187.2 ms ± 1.5 ms | -42.2 ms |
I also tested with a workspace that had two crates compiled linearly, and the difference there came out to be roughly 40 ms per crate too

(sqlx-macros) Ignore deps when getting metadata for workspace root

---

sqlx-core/src/any/connection/mod.rs
sqlx-core/src/any/mod.rs
sqlx-core/src/pool/mod.rs
sqlx-macros/Cargo.toml
sqlx-macros/src/query/mod.rs
sqlx-rt/src/lib.rs

Similar spirit to #1684, but this focus in on speeding up `cargo sqlx prepare` with a remote database. This change reuses the same DB connection instead of recreating one for each `sqlx-macros` query macro.
Three setups tested here. Two MariaDB setups on my work computer, one local and one remote, and the SQLite setup from #1684 on my personal laptop
MariaDB query \#: 332
MariaDB `sqlx-data.json` size: 705 KiB
SQLite query \#: 200
SQLite `sqlx-data.json` size: 305 KiB
The runtimes for `cargo sqlx prepare` on the various setups
| Setup | `master` (f8581386d232aa1e7d4b76d2a7bb1009f8169bcc) | This PR | Reduction `(new - old) / old` |
| :---: | :---: | :---: | :---:
| MariaDB remote | 61.421 s ±  1.985 s | 12.694 s ±  0.153 s | -79% |
| MariaDb local | 5.291 s ±  0.086 s | 5.050 s ±  0.064 s …

Reuse a cached DB connection instead of always recreating for `sqlx-macros`

---

tests/postgres/postgres.rs

This fix following warnings:
```
tests/postgres/postgres.rs#L979
unused `Result` that must be used
```

fix "unused `Result` that must be used" warnings

---

tests/postgres/macros.rs

This PR will fix following warnings
```
tests/postgres/macros.rs#L116
field is never read: `id`
tests/postgres/macros.rs#L306
field is never read: `id`
tests/postgres/macros.rs#L307
field is never read: `name`
```
This warnings was produced on github actions about over 50times.

fix `field is never read` warnings on postgres test

---

sqlx-core/src/postgres/types/array.rs
sqlx-core/src/postgres/types/record.rs
sqlx-core/src/query_builder.rs
tests/postgres/postgres.rs

Postgres arrays and records do not fully support custom types. When encountering an unknown OID, they currently default to using `PgTypeInfo::with_oid`. This is invalid as it breaks the invariant that decoding only uses resolved types, leading to panics.
This commit returns an error instead of panicking. This is merely a mitigation: a proper fix would actually add full support for custom Postgres types. Full support involves more work, so it may still be useful to fix this immediate issue.
Related issues:
- https://github.com/launchbadge/sqlx/issues/1672
- https://github.com/launchbadge/sqlx/issues/1797

Fix panics on unknown Postgres type oid when decoding

---

sqlx-core/src/types/json.rs
sqlx-core/src/types/mod.rs
sqlx-macros/src/database/mysql.rs
sqlx-macros/src/database/postgres.rs

fix serde_json usage in macros

---

sqlx-cli/README.md

Sometimes people do a bad job of reading comprehension (see #1813). This rewords a little to be even more prescriptive about how to build in offline mode.

SQLx-cli Readme: Reword "building in offline mode"

---

sqlx-core/src/mysql/types/str.rs

From my testing, this resolves #1690, since Planetscale/Vitess is [unable to fix the issue](https://github.com/planetscale/discussion/discussions/162#discussioncomment-2608816) on their side.
Would love to be able to use `sqlx` with Planetscale!

Add COLLATE_UTF8MB4_0900_AI_CI

---

sqlx-core/src/postgres/connection/describe.rs
tests/postgres/postgres.rs

`Some("Inner")` is only relevant when looking at the parent relation for left and right joins, it should not be used when checking the `join_type` of the plan.

Fix nullability check for inner joins in postgres

---

sqlx-core/src/mysql/connection/stream.rs

Same issue as #1667, but fixes another instance of panicking.
Where those changes added a check for `.is_empty()` before the access, I've just changed it to return an `Err` instead of the implicit panic.
I used a `Error::Protocol` since this seems to fit into "unexpected or invalid data", but another error type could make more sense.

Avoid panic when streaming packets are empty

---

sqlx-core/src/net/socket.rs

I follow suggestion of @abonander and trim `[` and `]` from host string before connect
Close #1739

trim [ and ] from host string before used to connect by TcpStream

---

sqlx-cli/README.md

From a formatting perspective, `Usage` is currently nested under `Install`. I think these would appropriately be siblings. This has the side benefit of making the headings under `Usage` more visually distinct from the rest of the content which I think makes it easier to read.

SQLx-cli Readme: Move `Usage` to same level as `Install`

---

sqlx-core/src/query_as.rs
tests/any/any.rs

Fixes https://github.com/launchbadge/sqlx/issues/1884
When a single row cannot be converted to the target type of query_as,
it should not prevent the library user from accessing the other rows
Otherwise, the user cannot access all query results in query_as.

query_as: don't stop stream after decoding error 

---

sqlx-core/src/logger.rs
sqlx-core/src/sqlite/connection/explain.rs
sqlx-core/src/sqlite/type_info.rs
tests/sqlite/describe.rs

Improves the datatype and null tracking for sub-queries and common table expressions through a series of independent changes:
* separating the  'OpenEphemeral' and 'OpenAutoindex' operations from the regular/normal cursor read operations
* unify tracking nullability, inline with the datatype for registers AND cursors, instead of a separate hashtable only tracking cursors, so that nullability will be retained when going through the register.  Retrieve not-null column metadata at the same time, and include temp-tables schema too.
* track all branches of OpCode execution, including following both sides of branch instructions, then merging the possible result rows.

Improve Sqlite support for sub-queries and CTE's

---

Cargo.lock
sqlx-cli/Cargo.toml
sqlx-cli/src/database.rs
sqlx-cli/src/lib.rs
sqlx-cli/src/migrate.rs
sqlx-cli/src/opt.rs
sqlx-cli/src/prepare.rs

And add a default 10 second connection timeout to all subcommands.
This addresses sporadic "connection refused" errors when using using `sqlx-cli` in automated jobs that start concurrently with a fresh database instance, such as using a Postgres image as [a service in Gitlab CI](https://docs.gitlab.com/ee/ci/services/).
Normally, I'd expect Gitlab to wait for the database container to be ready before proceeding with the build, and [their documentation clearly states that this is already being done.](https://docs.gitlab.com/ee/ci/services/#how-the-health-check-of-services-works) 
However, it appears that [this is not the case for the Kubernetes executor](https://gitlab.com/gitlab-org/gitlab-runner/-/issues/27969#note_970050415) which we're using in a self-managed Kubernetes cluster to …

feat(cli): add `--connect-timeout`

---

sqlx-core/src/mssql/protocol/login_ack.rs

added test similar to https://github.com/launchbadge/sqlx/blob/master/sqlx-core/src/mssql/protocol/pre_login.rs#L294

added test for mssql LoginAck

---

sqlx-core/src/any/types.rs
tests/postgres/postgres.rs

All four databases of PostgreSQL, MySQL, SQLite, and MSSQL supported by SQLx support `i16` Type, but `Any` Type's support for `i16` seems to be missing.

Add i16 support for `Any` Type.

---

sqlx-cli/src/migrate.rs

When running `sqlx migrate info`, the applied migrations checksums are
compared against the checksums of the local migration files. While the
checksums of applied migrations are stored correctly in the database as
sha384sum values, the `migrate info` command was incorrectly comparing
these against the checksums of down-migrations in cases where reversible
migrations are being used (e.g. when migrations end in `.up.sql` and
`.down.sql`).
This fixes the issue by skipping over any migrations with the
`MigrationType::ReversibleDown` type, using the same idiom as is used
when running migrations (with `migrate run`).
Issue introduced in #1680
Partially resolves #1158

Fix migration checksum comparison during `migrate info`

---

sqlx-core/src/pool/mod.rs
sqlx-core/src/postgres/options/mod.rs

This is a PoC PR which is related to https://github.com/launchbadge/sqlx/issues/1853
The idea is to expose PoolOptions and ConnectionOptions after the pool has been created.
This would allow easy database deletion and modification without having to save the options used during creation for the whole duration of the program.

Expose `connect_options` for initialized pools and `database` on the `PgConnectOptions`

---

sqlx-bench/benches/pg_pool.rs
sqlx-core/src/any/connection/mod.rs
sqlx-core/src/connection.rs
sqlx-core/src/error.rs
sqlx-core/src/mssql/connection/mod.rs
sqlx-core/src/mysql/connection/mod.rs
sqlx-core/src/pool/connection.rs
sqlx-core/src/pool/inner.rs
sqlx-core/src/pool/mod.rs
sqlx-core/src/pool/options.rs
sqlx-core/src/postgres/connection/mod.rs
sqlx-core/src/postgres/error.rs
sqlx-core/src/sqlite/connection/mod.rs
tests/any/pool.rs
tests/postgres/postgres.rs

* Fixed leak of `Arc<SharedPool>` in `DecrementSizeGuard::cancel()`
* Renamed `PoolOptions::connect_timeout` to `acquire_timeout` for clarity.
* Fixed `/* SQLx ping */` showing up in Postgres query logs
* Made `.close()` a regular function that returns a `Future`
* Deleted deprecated method `PoolConnection::release()`
* Document why connection might be dropped if `Pool::acquire()` is cancelled
* Added connection metadata to pool lifecycle callbacks
* Improved guarantees for `min_connections`
* Fixed `num_idle()` to not spin forever at high load
* Improved documentation across the `pool` module
Closes #1869
Closes #1862 
Closes #1824 
Closes #1743 
Closes #561

pool fixes and breaking changes

---

CHANGELOG.md
README.md
sqlx-core/src/any/database.rs
sqlx-core/src/any/kind.rs
sqlx-core/src/any/migrate.rs
sqlx-core/src/any/options.rs
sqlx-core/src/database.rs
sqlx-core/src/migrate/migrate.rs
sqlx-core/src/mssql/options/parse.rs
sqlx-core/src/mysql/migrate.rs
sqlx-core/src/mysql/options/mod.rs
sqlx-core/src/mysql/options/parse.rs
sqlx-core/src/pool/mod.rs
sqlx-core/src/pool/options.rs
sqlx-core/src/postgres/listener.rs
sqlx-core/src/postgres/migrate.rs
sqlx-core/src/postgres/options/mod.rs
sqlx-core/src/postgres/options/parse.rs
sqlx-core/src/sqlite/migrate.rs
sqlx-core/src/sqlite/options/mod.rs
sqlx-core/src/sqlite/options/parse.rs

fix #1905 : replaced all uses of "uri" to "url"

---

sqlx-core/src/mssql/mod.rs
sqlx-core/src/pool/connection.rs
tests/any/pool.rs
tests/mssql/mssql.rs

add regression test
closes #1912

pool: fix panic when using callbacks

---

sqlx-core/src/pool/options.rs

To not break the API we need to use an Arc instead of a Box for the
callback functions. Alternatively we could require all the function to
be Clone, but that would be a breaking change.

Implement Clone for PoolOptions

---

sqlx-core/src/types/json.rs

Happy to take any feedback on board and change it.
Just had a bit of a tough time finding some code examples of using `Json` correctly from this library, and wanted to save the next person some time investigating by adding a little to the docs.

docs: added docs for json

---

sqlx-core/src/postgres/types/bytes.rs
tests/postgres/postgres.rs

This function can panic due to slicing out of bounds when the server
responds without the `\x` prefix. With this commit we instead error and
also ensure that the prefix is what we expect instead of blindly
removing it.
Not directly related to the panic, we replace as_str() with as_bytes()
because there is no reason to perform a utf8 validity check when
hex::decode already checks that the content is valid.

Fix panic in Postgres Bytes decode

---

sqlx-core/src/postgres/types/array.rs
sqlx-core/src/postgres/types/bytes.rs
tests/postgres/types.rs

For generic arrays `[T; N]` and a specialized implementation for byte arrays `[u8; N]`.
I am not very confident that I have tested this change sufficiently. Feel free to detail more tests that should be added.
Related to https://github.com/launchbadge/sqlx/issues/1180 .

Support Rust arrays in Postgres

---

sqlx-macros/src/query/mod.rs

Fixes #1929 
This works around the issue mentioned in #1929 by not including SQLite for the cached connection. I've confirmed using the repro provided in the issue that this no longer runs into the problem of the database reporting that it's busy for several seconds after being reset when journaling is turned off.
It is worth noting that I still don't really know what the root cause of the issue is...
---
Random other things I've noticed regarding the issue:
- I'm not able to repro nearly as much using `check` instead of `clippy`
- Reproed 10/10 times with `clippy`, but 1/10 with `check`
- Even with the fix I still noticed lingering `-shm` and `-wal` files very rarely after running the repro script. I'm not really sure how to inspect them, so I don't know why they occasionally stick …

Don't cache sqlite connections for macros

---

sqlx-cli/src/database.rs
sqlx-cli/src/opt.rs
sqlx-core/src/sqlite/connection/describe.rs
sqlx-core/src/sqlite/connection/execute.rs
sqlx-core/src/sqlite/connection/mod.rs
sqlx-core/src/sqlite/error.rs
sqlx-core/src/sqlite/migrate.rs
sqlx-core/src/sqlite/mod.rs
sqlx-core/src/sqlite/options/connect.rs
sqlx-core/src/sqlite/options/mod.rs
sqlx-core/src/sqlite/types/mod.rs
sqlx-macros/src/query/data.rs
sqlx-macros/src/query/mod.rs
tests/sqlite/sqlite.rs

* use direct blocking calls for SQLite in `sqlx_macros`
* this also ensures the database is closed properly, cleaning up tempfiles
* don't send `PRAGMA journal_mode` unless set
* this previously defaulted to WAL mode which is a permanent setting
on databases which doesn't necessarily apply to all use-cases
* changing into or out of WAL mode acquires an exclusive lock on the database
that can't be waited on by `sqlite3_busy_timeout()`
* for consistency, `sqlx-cli` commands that create databases will still
create SQLite databases in WAL mode; added a flag to disable this.
* in general, don't send `PRAGMA`s unless different than default
* we were sending a bunch of `PRAGMA`s with their default values just to enforce
an execution order on them, but we can also do this by inserting empty slots …

sqlite improvements

---

sqlx-core/src/from_row.rs
sqlx-macros/src/derives/attributes.rs
sqlx-macros/src/derives/row.rs
tests/postgres/derives.rs

Adding `#[sqlx(flatten)]` field attribute in a `FromRow` macro to handle a field that implements `FromRow`
This is a task of #156 : _"Handle a field that is impl FromRow. A parallel from serde_json would perhaps make this #[sqlx(flatten)]"_

support flatten attribute in FromRow macro

---

Cargo.lock
sqlx-core/src/postgres/message/response.rs

fix(postgres): don't panic if `S` or `V` Notice fields are not UTF-8

---

sqlx-cli/src/prepare.rs

I did try to set rustc's --out-dir but encountered a strange error
stating that it can not be set more than once (even though I am unable
to deduce what else is setting it).
This enabled me to set a custom CARGO_TARGET_DIR and still be able to
prepare queries.

Set CARGO_TARGET_DIR when compiling the prepare queries

---

Cargo.lock
Cargo.toml
examples/postgres/files/Cargo.toml
examples/postgres/files/README.md
examples/postgres/files/migrations/20220712221654_files.sql
examples/postgres/files/queries/insert_seed_data.sql
examples/postgres/files/queries/list_all_posts.sql
examples/postgres/files/src/main.rs

@abonander - _Original PR went stale, cleaned up my fork to exclude those superfluous commits as my original PR looks like it was closed due to no changes detected between forks_
First and foremost, after being relatively new to Rust, sqlx made it incredibly easy to dive right into data-driven applications with a great straightforward API and docs to match. The docs touch on `query_file!()` and `query_as_file!()` (along with the other variants), but I thought it would be nice to include a Postgres-based example as well (recently did this in a personal project). Great work!

Add example with external query files

---

sqlx-cli/src/prepare.rs

This fixes the build after 7d8ded9a1afa3775d14ee00fd12b30636d7a0a7f:
```
error[E0616]: field `target_directory` of struct `metadata::Metadata` is private
--> sqlx-cli/src/prepare.rs:175:47
|
175 |             .env("CARGO_TARGET_DIR", metadata.target_directory.clone())
|                                               ^^^^^^^^^^^^^^^^ private field
|
help: a method `target_directory` also exists, call it with parentheses
|
175 |             .env("CARGO_TARGET_DIR", metadata.target_directory().clone())
|                                                               ++
```

fix(sqlx-cli): fix the build

---

.github/workflows/sqlx.yml

I think the CI failures we've been seeing lately are due to bad incremental compilation artifacts being cached. The rust-cache action is smarter about what it actually caches.

fix(actions): use rust-cache action

---

sqlx-core/src/any/error.rs
sqlx-core/src/any/mod.rs
sqlx-core/src/any/row.rs
sqlx-core/src/any/value.rs
sqlx-core/src/error.rs

Close #1408.
The `Type<Any>::type_info()` is not implemented currently and doesn't seem to be any time soon.
https://github.com/launchbadge/sqlx/blob/826e63fc11fc43ce92099b6844d8a9155bf38356/sqlx-core/src/any/type.rs#L11

Fix type info access in `Any` database driver

---

sqlx-core/src/query_builder.rs

Dearest Maintainer,
Thank you for your work on this project. I started using query builder today and I have enjoyed it. I did have a hard time figuring out how best to use separated to generate the values for an IN statement. It is my hope that adding an example will save someone else a few minutes of code reading or compile time. I wrote the example in the github text editor but It looks correct.    
Thanks again for your work on this.
Becker

Add in an example of how to use separated

---

src/macros.rs

This is an occasional source of confusion when people discover that `FromRow`'s control attributes don't affect the behavior of `query_as!`.
We've plans to change this, but for now the docs could stand to be clearer.

docs: clarify relationship between `query_as!` and `FromRow`

---

sqlx-core/src/from_row.rs

After a [discussion](https://discord.com/channels/665528275556106240/665528275556106243/898651938642591836) on the discord server, i decided to add an example for a manual implemenation of the FromRow trait. A manual implementation is useful if you can't use the derive macro (e.g. because of a external type from another crate)

Add example for manual implemenation of the FromRow trait

---

CONTRIBUTING.md

Small change, but since the `master` branch may still exists locally for some people or in some forks, this may safe quite some time. Had to rebase + fix one of my PRs due to this.

docs: `master` -> `main`

---

Cargo.lock
Cargo.toml
examples/mysql/todos/Cargo.toml
examples/mysql/todos/src/main.rs
examples/postgres/files/Cargo.toml
examples/postgres/files/src/main.rs
examples/postgres/json/Cargo.toml
examples/postgres/json/src/main.rs
examples/postgres/listen/Cargo.toml
examples/postgres/listen/src/main.rs
examples/postgres/mockable-todos/Cargo.toml
examples/postgres/mockable-todos/src/main.rs
examples/postgres/todos/Cargo.toml
examples/postgres/todos/src/main.rs
examples/postgres/transaction/Cargo.toml
examples/postgres/transaction/src/main.rs
examples/sqlite/todos/Cargo.toml
examples/sqlite/todos/src/main.rs
sqlx-core/Cargo.toml
sqlx-macros/Cargo.toml

This fixes `cargo check --workspace` and rust-analyzer.
Also see <https://github.com/launchbadge/sqlx/discussions/1956>.

fix: agree one a single default runtime for the whole workspace

---

sqlx-core/src/query_builder.rs

* get raw SQL
* new method to build `QueryAs` instead of `Query`

feat: `QueryBuilder` improvements

---

Cargo.lock
Cargo.toml
README.md
sqlx-bench/Cargo.toml
sqlx-core/Cargo.toml
sqlx-core/src/migrate/source.rs
sqlx-core/src/mssql/connection/mod.rs
sqlx-core/src/net/mod.rs
sqlx-core/src/net/socket.rs
sqlx-core/src/net/tls/mod.rs
sqlx-core/src/postgres/copy.rs
sqlx-macros/Cargo.toml
sqlx-macros/src/lib.rs
sqlx-rt/Cargo.toml
sqlx-rt/src/lib.rs
src/lib.rs
tests/postgres/postgres.rs

Actix Web v4 is stable and finally works under `#[tokio::main]` / `#[tokio::test]`. Therefore, I think it's safe to "remove" these feature flags now. They haven't actually been doing anything more than tokio- flags for a while.
I thought that removing the private flags and aliasing the public ones to their tokio- equivalent would be the best migration path. That way this could go out in a non-breaking release.
Inspired by #1669.

refactor: alias actix-* features to their equivalent tokio-* features

---

sqlx-macros/src/test_attr.rs

When the `#[sqlx::test]` macro is imported using `#[macro_use]` such as in the following example:
```rust
extern crate sqlx;
mod tests {
#[test]
fn something() {}
}
```
then the `#[test]` generated by the macro will refer to itself instead of the standard Rust `#[test]` macro. This will cause `rustc` to recursively expand it and produce the following error message:
```
thread 'rustc' has overflowed its stack
fatal runtime error: stack overflow
```
Instead, we can just refer to the standard macro by using its fully qualified path.
This PR:
* Swaps `#[test]` usages in `#[sqlx::test]` for their hygenic path to prevent recursive expansion alongside `#[macro_use]`
Closes #2017.

fix: use hygenic macro path

---

sqlx-core/src/mysql/options/connect.rs
sqlx-core/src/mysql/options/mod.rs

Since PR #2038 was closed for unknown reason, this PR is a direct replica of it to resolve issue #2034

added flag for PIPES_AS_CONCAT connection setting for MySQL to fix #2034

---

Cargo.lock
sqlx-core/Cargo.toml

The `sha-1` crate will be deprecated in favor of `sha1`. See https://github.com/RustCrypto/hashes#crate-names for details.

chore: Switch to sha1 crate

---

sqlx-core/src/query_builder.rs

@danielakhterov and I were playing around with counting lines using regex and noticed that SQLx had an odd number of ` ``` ` and got a little nerd-sniped trying to find it.

fix(docs): close code block in query_builder.rs

---

sqlx-core/src/sqlite/connection/handle.rs
sqlx-core/src/sqlite/statement/handle.rs
sqlx-core/src/sqlite/statement/mod.rs
sqlx-core/src/sqlite/statement/unlock_notify.rs

Closes #2021
Note the SQLite [documentation about unlock notify](https://www.sqlite.org/unlock_notify.html) doesn't mention `sqlite3_exec` but it's just a convenience shortcut for `sqlite3_prepare_v2`, `sqlite3_step`, and `sqlite3_finalize`, so I think it should still apply.

Use unlock notify also on `sqlite3_exec` 

---

sqlx-core/src/postgres/types/mod.rs

This PR updates the documentation to reflect #1822

Add documentation for `IpAddr` support in Postgres

---

sqlx-cli/src/metadata.rs
sqlx-cli/src/prepare.rs
sqlx-cli/tests/assets/sample_metadata.json
sqlx-macros/src/query/mod.rs

Small PR to change the target directory for offline query caches from `target/sqlx` to `target/sqlx/<CRATE_NAME>`, which fixes the behaviour seen in #2049. CC @djc 
The problem is essentially a race condition: there is a period between `cargo sqlx prepare` deleting the `target/sqlx` directory and reading the queries from it, during which time another process could build/check one of the other crates in the workspace and populate it.
BEFORE, queries for all crates in a workspace would share the `target/sqlx` directory:
```
target/sqlx
├── query-2b192bf413d46a28226de2ad754a382043c483cf55c04d19bdfa916dcbf0e7ae.json
├── query-95d796755ea0ade4578c91d102407ae003487e40922284cdd6f5c8cbc8d0b5e2.json
└── query-e46f12d720e0911c9280a1b43d7aab30beef94861713fa686db77cfe30702792.json
```
AFTER this PR, …

Fix `prepare` race condition in workspaces

---

sqlx-cli/src/metadata.rs
sqlx-cli/src/prepare.rs

Small PR to change `cargo sqlx prepare` to always use `cargo check`. 
Currently, `prepare` invokes `cargo rustc` by default but switches to `check` when the `--merged` flag is used. This can lead to confusion since certain flags passed to `cargo check` will be rejected by `cargo rustc` when running `prepare`.
The current behaviour also contradicts the [`sqlx-cli` README](https://github.com/launchbadge/sqlx/blob/3f7111f05de2984aa00ad00fe6a670bca9db0aa0/sqlx-cli/README.md#include-queries-behind-feature-flags-such-as-queries-inside-of-tests), which states:
> In order for sqlx to be able to find queries behind certain feature flags you need to turn them on by passing arguments to rustc.
>
> This is how you would turn all targets and features on.
> ```
> cargo sqlx prepare -- --all-targets …
```

Use cargo check consistently in `prepare`

---

.github/workflows/sqlx.yml
sqlx-core/src/sqlite/connection/establish.rs
sqlx-core/src/sqlite/error.rs
sqlx-core/src/sqlite/options/mod.rs
tests/sqlite/sqlite.rs
tests/x.py

Implements #1460
I was trying to find a way to use extensions (specifically [`vsv`](https://github.com/nalgeon/sqlean/blob/main/docs/vsv.md) and [`spatialite`](https://www.gaia-gis.it/fossil/libspatialite/index)) with SQLite from Rust, and while Rusqlite supports them, my perferred SQL crate did not, hence this PR to try and rectify that situation.
I found the issue mentioned above and took note of the suggestions made, that we should probably implement this as conservatively as we can, please see the commit message for more specifics.
I would appreciate some guidance on how to test this from the integration test suite. Something like this will exercise the code in question, the more difficult problem is "How do we get the extension shared object to the test context?".
```rust …
```

Add extension support for SQLite

---

sqlx-core/src/postgres/connection/executor.rs
sqlx-core/src/postgres/message/close.rs

This allows to free server resources earlier and run the same logic as simple Query does:
"The simple Query message is approximately equivalent to the series Parse, Bind, portal Describe, Execute, Close, Sync,"

close unnamed portal after each executed extended query

---

sqlx-macros/src/derives/row.rs

Given a generic type like `A<B>` before `sqlx` would produce
`A<B>::from_row(row)` which is invalid syntax.
Now it produces `<A<B> as ::sqlx::FromRow<'a, R>>`.
This also fixes a bug for non-generic types where an inherent method
might have been called instead of the `::sqlx::FromRow::from_row` method
because UFCS wasn't used.

Fix expansion of `sqlx(flatten)`

---

sqlx-core/src/migrate/migrator.rs
sqlx-macros/src/migrate.rs
src/macros/test.md

? - Why 
Various pgwire databases such as CockroachDB do not support such a feature. 
> [iodb] running migrations failed: Execute(Database(PgDatabaseError { severity: Error, code: "42883", message: "unknown function: pg_advisory_lock()", detail: None, hint: None, position: None, where: None, schema: None, table: None, column: None, data_type: None, constraint: None, file: Some("name_resolution.go"), line: Some(205), routine: Some("ResolveFunction") }))
In such scenarios the only way to perform migrations is without locking
This PR allows the end user to choose whether to lock the DB when running migrations or not.
Default behaviour is maintained and DBs are still locked on default.
Example:
`sqlx::migrate!().set_locking(false).run(&pool).await`
(Changes have been tested & are actively …

customizable db locking during migration

---

sqlx-macros/src/derives/type.rs

Problem: `PgHasArrayType` was checking the application's `postgres` feature
Solution: only check the library's `postgres` feature
This wasn't fun to debug. 😅

PgHasArrayType for transparent types fix.

---

sqlx-core/src/from_row.rs
sqlx-macros/src/derives/attributes.rs
sqlx-macros/src/derives/row.rs
tests/mysql/macros.rs

This is used for converting type in FromRow.And I am not sure whether it is worth and just for discussing.
```rust
#[derive(sqlx::FromRow)]
struct Record {
#[sqlx(try_from = "i64")]  
id: u64,
}
// for custom type
#[derive(sqlx::FromRow)]
struct Record {
#[sqlx(try_from = "i64")]
id: Id,
}
#[derive(Debug, PartialEq)]
struct Id(i64);
impl std::convert::TryFrom<i64> for Id{
type Error = Error;
fn try_from(v:i64) -> Result<Id,Self::Error>{
Ok(Id(v))
}
}
```
* In fact,I open this pr mainly for decoding Bigint to u64,which will be supported in sqlx 6.0+.It makes me confused whether this pr is worth.
There is another attribute `with` for type converting.Maybe I will open another issue for discussing.
```rust
#[derive(sqlx::FromRow)]
struct Record {
#[sqlx(with(mysql = "path"))]
id: u64,
}
fn …
```

Add `try_from` attribute for `FromRow` derive

---

sqlx-cli/Cargo.toml

**TL;DR:** Remove unnecessary dependency on `time` 0.1 in `sqlx-cli`; that version of `time` is deprecated and contains a vulnerability flagged by `cargo audit`.
**Effects of Change:** This change adjusts the feature flags configured for the `chrono` crate for `sqlx-cli`. It disables default features for `chrono` and enables the `clock` flag only. The outcome is that `chrono` will no longer include the default `oldtime` feature flag which removes the dependency on `time`.
**Why?** `time` 0.1 is deprecated and vulnerable to [RUSTSEC-2020-0071](https://rustsec.org/advisories/RUSTSEC-2020-0071). Although chrono's dependency on time is not actually vulnerable, it causes cargo audit to be noisey:
```
Crate:     time
Version:   0.1.44
Title:     Potential segfault in the time crate
Date: …
```

fix: Remove default chrono dep on time for sqlx-cli

---

sqlx-core/src/sqlite/connection/worker.rs

Make begin,commit,rollback cancel-safe in sqlite 

---

sqlx-core/src/logger.rs
sqlx-core/src/sqlite/connection/explain.rs

Reduce overhead of sqlite explain plan logging.
Partial fix for #1921
Very rough 
`initial 
real    3m26.159s 
user    3m23.611s 
sys     0m1.920s  
capture program & operations by reference 
real    3m7.704s 
user    3m6.264s 
sys     0m0.754s 
use Vec instead of HashSet for results 
real    1m24.922s              
user    1m24.317s              
sys     0m0.562s               
check logging enabled before cloning result 
real    1m17.668s                    
user    1m17.047s                    
sys     0m0.521s
`

Sqlite explain plan log efficiency

---

sqlx-core/src/sqlite/connection/explain.rs

The sqlite CTE feature (#1816) introduced severe performance degradation, and this PR attempts to fix it.
This patch drastically reduces search space by adding memorization based on register type and cursor data type. Pushing new states on to the Stack is guarded by a `HashSet`, where if no new information is gained about an instruction (i.e. different register/cursor data type), the instruction will not be searched again. 
Now the example query in #1921 only takes 5s to verify instead of several minutes. It might be possible to further optimize this by stop tracking unnecessary information, which could save a lot of memory allocations.

Fix compile time verification performance regression for sqlite

---

Cargo.toml
sqlx-core/src/sqlite/connection/explain.rs

Small change to fix compilation errors on the [0.7-dev](https://github.com/launchbadge/sqlx/tree/0.7-dev) branch from merging #1946, #1960 and #2094 (nothing was wrong with any of those PRs, just a merging thing).
Compilation errors blocking further work. Figured it would be better to fix them in a separate PR.
```rust
error: failed to select a version for `libsqlite3-sys`.
... required by package `sqlx v0.6.2 (<...>\sqlx)`
... which satisfies path dependency `sqlx` (locked to 0.6.2) of package `files v0.1.0 (<...>\sqlx\examples\postgres\files)`
versions that meet the requirements `^0.24` are: 0.24.2, 0.24.1, 0.24.0                                
```
```rust
Compiling sqlx-core v0.6.2 (<...>\sqlx\sqlx-core)
error[E0532]: expected tuple struct or tuple variant, found struct variant …
```

Fix sqlite compilation

---

Cargo.toml
sqlx-core/src/mysql/testing/mod.rs
sqlx-core/src/pool/inner.rs
sqlx-core/src/pool/mod.rs
sqlx-core/src/postgres/testing/mod.rs
sqlx-core/src/sqlite/connection/explain.rs

This allows external updates of the `ConnectionOption` used when a new connection needs to be opened for the pool.  The primary use case is to support dynamically updated (read: rotated) credentials used by systems like AWS RDS.
Closes #445
Normally I shy away from using a `.expect()` invocation in code, but to my understanding the RwLock poisoning concept in the stdlib is generally regarded as a mistake. 
I looked at using Tokio's RwLock instead, but I didn't want to make the dynamic config update async-friendly.  Doing so might encourage anyone using the dynamic config to hold the write lock while fetching the updated credentials which in turn would block any new connections from being spawned in the pool.  Using a sync RwLock forces minimal holds on the lock, but Tokio's sync RwLock …

feat: Add set_connect_options method to Pool

---

sqlx-core/src/sqlite/connection/explain.rs

Fixes #1983.
Feel free to merge if repo maintainer thinks this is a good first step.

Sqlite EXPLAIN type inference improvements

---

sqlx-sqlite/src/connection/explain.rs
tests/sqlite/describe.rs

Add reproducers & fixes for various sqlite describe bugs.
Fixes include:
* fix handling of nested order-by queries
* handle when sqlite puts a 'record' inside of a blob column
* handle rewind of an empty table correctly
* allow opcodes to be evaluated twice per branch path
* fix retrieval of temporary table column signatures
* add basic support for date & time functions
* fix handling of offset clause
* fix handling of hard-coded large offsets
* implement IfPos to avoid creating unnecessary branches
* fix handling of group by clause 
* handle IfNull 
* handle delete statement when grouping with-clause results

Sqlite describe fixes

---

sqlx-core/src/pool/options.rs

This allows reading back `PoolOptions` that have already been set.
My concrete use-case is querying the maximum connections from a context where I regularly collect application performance metrics from a `PgPool`. Currently I can only see how many connections there are and how many of them are active/idle, but in order to graph this against the totally available connections, I would have to pass through the initial configuration somehow. It's much easier to expose them from the `PoolOptions` directly.

Expose PoolOptions for reading

---

sqlx-core/src/pool/inner.rs

Uses the new `let else` statement released in Rust 1.65 in favor of a `unwrap_or_else` macro rule inlined to the code.

Use `let else` statements in favor of macro

---

CHANGELOG.md
sqlx-postgres/src/copy.rs

Fixes #2178 
After experimenting for an our or so I fixed my issue by receiving the next notification available when something failed as described in the mentioned issue.

fix: ensures recover from fail with PgCopyIn

---

CHANGELOG.md
Cargo.lock
Cargo.toml
sqlx-core/Cargo.toml
sqlx-sqlite/Cargo.toml
sqlx-sqlite/src/connection/establish.rs
sqlx-sqlite/src/lib.rs
sqlx-sqlite/src/options/mod.rs
sqlx-sqlite/src/regexp.rs

Closes #194 
For a project I ended up implementing a custom `REGEXP` implementation for sqlite. I noticed sqlx did not have that, and #194  mentioned that it was not implemented yet.
This is technically a breaking change if a user has already defined their own `REGEXP` function. but sqlite's behavior is to simply overwrite the previous function, and `sqlx` did not have a `regex` feature yet (only in `sqlx-core`).
The current implementation is very strict. It only accepts UTF-8 columns in both the field and the REGEXP. In my system this has not been an issue.
I'm unsure where to add documentation on this, I'm guessing in the sqlite documentation?
I also took the liberty of bumping `libsqlite3-sys`

Added regexp support in sqlite

---

Cargo.lock
sqlx-mysql/Cargo.toml
sqlx-postgres/Cargo.toml
src/macros/mod.rs

Otherwise, whoami pulls in web-sys, wasm-bindgen and a BUNCH of additional dependencies. This is really unnecessary, and if someone has an actual use case where they are attempting to connect to postgres from a browser, well ... they've probably already been pwned by now. If it is deemed necessary, then add an additional activation feature for that specific slew of deps.

Set whoami default-features to false

---

sqlx-macros-core/src/derives/attributes.rs
tests/mysql/macros.rs

Hello :wave: 
The new attribute `try_from` for the `FromRow` derive introduced by #1081 expects the value of `try_from` to be a simple identifier instead of a full-fledged type. This means that that attribute cannot be used unless the referenced type is already in scope.
```rust
#[derive(sqlx::FromRow)]
struct Record {
#[sqlx(try_from = "SomeType")] // <- This is fine
id: u64,
}
#[derive(sqlx::FromRow)]
struct Record {
#[sqlx(try_from = "another::SomeType")] // <- This currently fails, but it should be allowed
id: u64,
}
```
This PR allows using complex types as the argument of `try_from` instead of just simple identifiers.

Allow using complex types in `try_from` when deriving `FromRow`

---

sqlx-postgres/src/connection/describe.rs
sqlx-postgres/src/connection/mod.rs
tests/postgres/postgres.rs

The current strategy employed to resolve a user-defined type name to an OID does not take into account the current `search_path`. This might cause some issues if we have different types with the same name in different schemas.
I noticed this behaviour because I'm working on a project that uses Postgres schemas to isolate integration tests by creating a new schema for each one, which means that I have a lot of types with the same name in different schemas.
```sql
CREATE TYPE status AS ENUM('open', 'closed');
CREATE SCHEMA test123;
CREATE TYPE test123.status AS ENUM('open', 'closed');
```
As an example, if we open a new connection and set the `search_path` to `test123`, `INSERT`s referencing the enum `status` start failing:
```rust
#[derive(sqlx::Type)]
#[sqlx(type_name = "status", …
```

Postgres OID resolution query does not take into account current `search_path`

---

CHANGELOG.md
sqlx-sqlite/src/connection/mod.rs
sqlx-sqlite/src/options/mod.rs

[SQLite] Add option to execute `PRAGMA optimize;` on close of a connection

---

sqlx-cli/src/prepare.rs

Previously, if `cargo metadata` failed to run, `cargo sqlx prepare` would output a cryptic `error: EOF while parsing a value at line 1 column 0` as reported in #2218 
This PR aims to clear up any confusion about the source of the error by changing the message to. `error: Issue parsing 'cargo metadata' output - consider manually running it to check for issues`

Add context to confusing sqlx prepare parse error

---

sqlx-cli/Cargo.toml
sqlx-cli/src/lib.rs
sqlx-mysql/src/any.rs
sqlx-postgres/src/any.rs
sqlx-sqlite/src/any.rs

Fix the `db create`, `db drop`, and `migrate run` commands for `sqlx-cli`. Edit: this is for the latest changes on main for 0.7.
Fixes the following errors running those commands:
> thread 'main' panicked at 'No drivers installed. Please see the documentation in `sqlx::any` for details.', sqlx-core/src/any/driver.rs:143:33
and
> error: while executing migrations: error with configuration: SQLite driver does not support migrations or `migrate` feature was not enabled
- Uncomment default and database features for `sqlx-cli`.
- Install database drivers in `sqlx-cli`.
- Implement `AnyConnectionBackend::as_migrate` for databases.
- Checkout this branch and install `sqlx-cli`.
```sh
cargo install -f --path ./sqlx-cli
```
- Use the SQLite example.
```sh
cd examples/sqlite/todos
export …
```

Fix sqlx-cli create, drop, migrate

---

sqlx-core/src/logger.rs

This also enables on services that can query this data to get useful metrics.
Also note that I chose `db.statement` to having a standard to follow even though this does not use opentelemetry, but the latter can benefit from it [1].
Running the tests with that would log something like this:
```
[2023-02-24T17:14:00Z INFO  sqlx::query] summary="select 1 as \"foo?\"" db.statement="" rows_affected=0 rows_returned=1 elapsed=24.75µs sql=""
[2023-02-24T17:14:00Z INFO  sqlx::query] summary="select 1 as \"foo: …" db.statement="\n\nselect\n  1 as \"foo: MyInt\"\n" rows_affected=0 rows_returned=1 elapsed=44.5µs sql="\n\nselect\n  1 as \"foo: MyInt\"\n"
[2023-02-24T17:14:00Z INFO  sqlx::query] summary="select 1 as \"foo?: …" db.statement="\n\nselect\n  1 as \"foo?: MyInt\"\n" rows_affected=0 …
```

chore: Use tracing's fields to get structured logs

---

sqlx-core/src/any/connection/backend.rs
sqlx-core/src/any/connection/mod.rs
sqlx-core/src/connection.rs
sqlx-core/src/net/socket/buffered.rs
sqlx-core/src/pool/connection.rs
sqlx-mysql/src/any.rs
sqlx-mysql/src/connection/mod.rs
sqlx-postgres/src/any.rs
sqlx-postgres/src/connection/mod.rs
sqlx-sqlite/src/any.rs
sqlx-sqlite/src/connection/mod.rs
tests/mysql/mysql.rs
tests/postgres/postgres.rs

BREAKING: adds new required method to `Connection` trait.
closes #2372

feat: add `Connection::shrink_buffers`, `PoolConnection::close`

---

sqlx-postgres/src/connection/describe.rs

Materialize [0] is a PostgreSQL-like database that, similar to CockroachDB, does not support PostgreSQL's `EXPLAIN` output. Extend the fix from PR #1248 to Materialize, too, so that sqlx can still be used with Materialize.
See #1248.
[0]: https://materialize.com

Don't run EXPLAIN nullability analysis on Materialize

---

sqlx-postgres/src/connection/describe.rs
tests/postgres/macros.rs
tests/postgres/setup.sql

Fixes #1449 (I think). I verified that without the fix, an appropriate invocation to `cargo test` fails, and with the fix included the same invocation to `cargo test` passes.
I used INOUT in setup.sql because older versions of Postgres don't support OUT parameters.

feat: support calling Postgres procedures with the macros

---

sqlx-macros-core/src/query/output.rs
sqlx-postgres/Cargo.toml
tests/postgres/derives.rs

fixes https://github.com/launchbadge/sqlx/issues/2173
```rs
use sqlx::PgPool;
struct Wrap(bigdecimal::BigDecimal);
impl From<bigdecimal::BigDecimal> for Wrap {
fn from(x: bigdecimal::BigDecimal) -> Self {
Wrap(x)
}
}
impl From<Wrap> for bigdecimal::BigDecimal {
fn from(x: Wrap) -> Self {
x.0
}
}
struct Data {
pub amount: Wrap,
}
#[tokio::main]
async fn main() {
let db = PgPool::connect("postgres://postgres:mysecretpassword@localhost:5432/teststore").await.unwrap();
sqlx::query_as!(Data, "select amount from test").fetch_one(&db).await.unwrap();
// previously it will expand like this:
{
{
#[allow(clippy::all)] {
use ::sqlx::Arguments   as _;
let query_args = <sqlx::postgres::Postgres as ::sqlx::database::HasArguments>::Arguments::default();
::sqlx::query_with::<sqlx::postgres::Postgres, …
```

new type support in query_as

---

sqlx-core/src/types/json.rs

Implements conversion traits between `Json` and its inner value. Useful for generic code. I ran into this today while trying to return an `impl Into<Foo>` using `sqlx::types::Json`.

Add From impls for Json

---

Cargo.toml

patch for [high severity advisory](https://github.com/advisories/GHSA-jw36-hf63-69r9) in libsqlite3-sys
closes #2388

PATCH: bump libsqlite3-sys to patched version

---

sqlx-core/src/connection.rs

This has been discussed in https://github.com/launchbadge/sqlx/issues/939 and https://github.com/launchbadge/sqlx/issues/942 over the course of two years. https://github.com/launchbadge/sqlx/pull/1371 changed it, but https://github.com/launchbadge/sqlx/pull/1465 reverted it being, I believe, an accident, a side effect of reverting the major change of the pull request.

Lower default logging level for statements to Debug

---

src/macros/mod.rs

RUSTFLAGS space separates the arguments, so we actually have to combine them with an equal sign

fix(docs): example of `sqlx_macros_unstable` in config.toml

---

FAQ.md
sqlx-cli/src/prepare.rs
sqlx-macros-core/src/query/data.rs
sqlx-macros-core/src/query/mod.rs

Resolves https://github.com/launchbadge/sqlx/issues/2395
Thanks to @cycraig for the advice here: https://github.com/launchbadge/sqlx/issues/2395#issuecomment-1464850928
The PR to implement one file per query: https://github.com/launchbadge/sqlx/pull/2363 implemented logic to write queries to a temp file and then persist them to `SQLX_OFFLINE_DIR` here: https://github.com/launchbadge/sqlx/blob/c03926c74176e80c2f6579e209a924c15494af56/sqlx-macros-core/src/query/data.rs#L163-L170
However, the docs for `NamedTempFile::persist` mention the following:
```
Note: Temporary files cannot be persisted across filesystems.
```
On Linux, the `/tmp` directory is commonly mounted as `tmpfs` which means the call to `tmp_file.persist` will result in the following error: `failed to move query file: …

fix(prepare): store temporary query files inside the workspace

---

Cargo.lock
Cargo.toml

chrono 0.4's default features include the `oldtime` feature which pulls in time 0.1.44. This is an unmaintained version with soundness issues (time-rs/time#293) and is rarely needed. If downstream users require this dependency, they can enable the feature themselves.

fix: drop old time 0.1.44 dep

---

sqlx-sqlite/src/connection/explain.rs
tests/sqlite/describe.rs

This closes https://github.com/launchbadge/sqlx/issues/2407
The issue describes the situation. The HaltIfNull opcode was not being respected, causing the macro to spit out optionals for types that could never be null.
This PR fixes it :)

fix(#2407): respect the HaltIfNull opcode when determining nullability

---

sqlx-cli/Cargo.toml

Without the `runtime-tokio` feature enabled `sqlx-cli` builds fine but when run prints ```thread 'main' panicked at 'either the `runtime-async-std` or `runtime-tokio` feature must be enabled', /home/paolo/.cargo/git/checkouts/sqlx-f05f33ba4f5c3036/9ac2cb3/sqlx-core/src/net/socket/mod.rs:217:9```

Enable runtime-tokio feature of sqlx when building sqlx-cli

---

sqlx-sqlite/src/connection/establish.rs
sqlx-sqlite/src/connection/mod.rs
tests/sqlite/sqlite.rs

**What**
Adds progress handler support to sqlite. The feature is already supported by the sqlite driver. This PR exposes it.

add progress handler support to sqlite

---

sqlx-sqlite/src/types/time.rs

Sqlite's DATETIME column can have a default value set by CURRENT_TIMESTAMP which is then a string expressed from UTC in the following format: "YYYY-MM-DD HH:MM:SS". Unfortunately, this can't be properly decoded as a time::OffsetDateTime as the TZ info is missing. This PR proposes to assume UTC in such a case.
Related issue #2288.

`time`: Assume UTC when decoding a DATETIME column in sqlite

---

sqlx-sqlite/src/connection/explain.rs

The current query explain implementation can make compilation appear to freeze during more complicated queries, due to an explosion of branches/loops now that most branching instructions are handled correctly.
This adds a fixed limit on the amount of effort to put into evaluating the explain of a single query. This could impact query analysis correctness, but avoids an enormous run time.

limit the number of instructions that can be evaluated

---

sqlx-macros-core/src/lib.rs
sqlx-macros-core/src/query/args.rs
sqlx-macros/Cargo.toml
src/macros/mod.rs

Adds a deprecation notice when type ascription pattern is used, preparing grounds for when
we drop support for the pattern, keeping compatibility with Rust's supported syntax, as decided
on [RFC 3307].
This change was created as discussed in #2482.
The following code uses type ascription for the second argument.
```rust
let _ = sqlx::query!(
r#"SELECT $1 as a, $2 as b"#,
foo_bar as i32,
(6 + 8): <Foo as Deref>::Target
);
```
Generating a warning that looks as follows:
```
warning: use of deprecated constant `main::{closure#0}::warning_arg1`: 
Type ascription pattern is deprecated, prefer casting
Try changing from
`(6 + 8) : < Foo as Deref > :: Target`
to
`(6 + 8) as < Foo as Deref > :: Target`
See <https://github.com/rust-lang/rfcs/pull/3307> for more information
--> src/main.rs:16:9
|
16 …
```

chore: add deprecation notice for type ascription use

---

Cargo.lock
sqlx-mysql/Cargo.toml
sqlx-postgres/Cargo.toml
sqlx-postgres/src/options/pgpass.rs

The `dirs` crate [inherits](https://github.com/dirs-dev/dirs-sys-rs/issues/21) an `MPL`-licensed dependency since v5.0.1, which can't be used in a lot of environments.
Use the cargo-team maintained `home` crate for non-Windows & `etcetera` crate for Windows `data_dir`.
Closes #2432.

chore(sqlx-postgres): replace `dirs` with `home` & `etcetera`

---

sqlx-mysql/src/types/mod.rs
sqlx-mysql/src/types/uuid.rs
sqlx-sqlite/src/types/mod.rs
sqlx-sqlite/src/types/uuid.rs
tests/mysql/types.rs
tests/sqlite/types.rs

Copy pasted the implementation for `Hyphenated` and adapt.

Add Simple format for Uuid for MySQL & SQLite.

---

sqlx-mysql/src/testing/mod.rs
sqlx-postgres/src/testing/mod.rs

I recently encountered a panic in our CI where a test db created by the `#[sqlx::test]` macro was seemingly missing, right after it was created and right before we connected to it.
```
thread panicked at 'failed to connect to test database: Database(PgDatabaseError { severity: Fatal, code: "3D000", message: "database \"_sqlx_test_38\" does not exist", detail: None, hint: None, position: None, where: None, schema: None, table: None, column: None, data_type: None, constraint: None, file: Some("postinit.c"), line: Some(885), routine: Some("InitPostgres") })',
at sqlx-core/src/testing/mod.rs:243:10
stack backtrace:
4: sqlx_core::testing::setup_test_db::{{closure}}
at sqlx-core/src/testing/mod.rs:240:20
5: sqlx_core::testing::run_test::{{closure}}
at sqlx-core/src/testing/mod.rs:216:63
``` …

fix: ensure fresh test db's aren't accidentally deleted by do_cleanup

---

Cargo.lock
Cargo.toml
benches/sqlite/describe.rs
sqlx-sqlite/src/connection/explain.rs
sqlx-sqlite/src/connection/intmap.rs
sqlx-sqlite/src/connection/mod.rs

Add a few simple benchmarks for sqlite describe performance, then improve the benchmarks by replacing HashMap with a custom IntMap struct (a thin wrapper around Vec giving an API similar to HashMap<i32,_>).
```
insert/fks
----------
434836b4     1.00      21.2±0.05ms       ? ?/sec (IntMap)
0797aa13     1.30      27.6±0.09ms       ? ?/sec (BranchList)
0f18d2c0     1.54      32.5±0.12ms       ? ?/sec (separateMemory)
9c0fc8bf     1.54      32.6±0.10ms       ? ?/sec (initial)
insert/returning
----------------
434836b4     1.00     430.3±3.55µs       ? ?/sec (IntMap)
9c0fc8bf     1.08     464.6±4.59µs       ? ?/sec (initial)
0f18d2c0     1.09     468.1±4.92µs       ? ?/sec (separateMemory)
0797aa13     1.12     482.5±3.89µs       ? ?/sec (BranchList)
select/recursive
----------------
434836b4 …
```

Add and improve sqlite describe performance benchmarks

---

sqlx-core/Cargo.toml
sqlx-core/src/net/tls/tls_rustls.rs

As in the title. Ideally this would be backported to 0.6. This should solve issues like https://github.com/SergioBenitez/Rocket/issues/2391.

Update rustls to 0.21, webpki-roots to 0.23

---

sqlx-macros-core/src/query/output.rs

Since `::std::result::Result::Ok` is not used here, it errs when the `Ok` in global scope is not `::std::result::Result::Ok`, for example when one imports `anyhow::Ok`.
This PR fixes it by using `::std::result::Result::Ok`.

Use ::std::result::Result::Ok in output.rs

---

Cargo.lock
Cargo.toml

Hi, `mac_address` maintainer here. This bumps the version of `mac_address` to 1.1.5 (which I just published) which includes an important fix for 32-bit Windows targets which would trigger a panic on nightly due to some unfortunate Windows ABI issues where Rust and the WinAPI don't agree on a struct's alignment. This is very unlikely to affect the vast majority of people using `sqlx`, so I don't think any kind of backport is necessary for pre-0.7 releases, but I wanted to make sure that you folks had the latest version going forward.
If you have any questions or comments let me know!

Bump mac_address to 1.1.5

---

sqlx-core/src/migrate/source.rs
tests/migrate/macro.rs
tests/migrate/migrations_symlink

When enumerating the source directory seeking migration files, `sqlx` ignores entries that aren't files. This was previously reported as #614 and fixed in #985 but apparently regressed somewhere along the way. This commit reintroduces the fix from #985 to the current implementation: use `std::fs::metadata` instead of `std::fs::DirEntry::metadata`. The former is documented to traverse symlinks; the latter does not.

Traverse symlinks when resolving migrations

---

sqlx-mysql/src/error.rs

Apparently the `mysql` reference for server error messages was moved
into it's own manual, breaking the existing links.
I fixed the links referring to the old page.

Fix broken links to mysql error documentation

---

sqlx-macros-core/src/query/data.rs

This adds a newline at the end of all cached ./.sqlx/... JSON files so that anyone who has "auto-newline" enabled in their IDE would not accidentally add it to the cached file. This also ensures that GitHub diff would not show an alarming red icon next to the end of the checked in sqlx files.
P.S. apparently this is the recommended way of doing it, per https://github.com/serde-rs/json/issues/716

Add a newline to the generated JSON files

---

sqlx-mysql/src/protocol/statement/prepare_ok.rs

Fixes #2512
I'm not sure what is the underlying issue that causes it, but it would be preferable to avoid panic if possible.

Do not panic when `PrepareOk` fails to decode

---

sqlx-core/src/query_builder.rs

Fixing #2494 
Allow to keep existing args when creating a query builder

add args to query builder (#2494)

---

sqlx-postgres/src/type_info.rs

This PR closes #1111 and supersedes #2146. It adds a function to retrieve OIDs, which is very useful in very dynamic schemas, such as DBMSs or when you want to provide a more low-level interface to the DB.
This function is a non-panicking alternative to `.oid()`.

Exposing the Oid of PostgreSQL types

---

sqlx-macros-core/src/database/sqlite.rs

Adds DATE pseudo-type support for sqlite into the macros for both `chrono` and `time`.
Just adding the few lines mentioned in https://github.com/launchbadge/sqlx/issues/2026#issuecomment-1212482339.
I'm aware sqlite has no actual support for the types and simply treats them as strings, however given we already kinda support it in sqlx I figured it may as well be integrated.

sqlite date macro support

---

Cargo.lock
sqlx-cli/Cargo.toml
sqlx-cli/src/completions.rs
sqlx-cli/src/lib.rs
sqlx-cli/src/opt.rs

I recently started using `sqlx` (and `sqlx-cli`) for a project and
noticed there is no autocompletion.
As it's trivial to add autocompletion to `clap`-based CLIs and I've done
it a bunch of times I would just create a pr.
I added a subcommand named `completions` to generate completions on the
fly. `clap_complete` theoretically also supports generating completions
at compile time, but as `cargo install` doesn't support installing
autocompletion scripts that doesn't really make sense here.
```console
$ sqlx completions bash > path/to/completions
```
`clap_complete` per default supports generating autocompletions for `bash`, `elvish`, `fish`, `powershell`, and `zsh`.
Sadly there is currently no standard way to create completions for
cargo subcommands, so `cargo-sqlx` can't benefit from …

Add CLI autocompletion using clap_complete

---

sqlx-sqlite/src/statement/unlock_notify.rs

I believe this resolves an EXC_BAD_ACCESS error I've been seeing on MacOS under high contention.

fix(sqlite) Do not drop notify mutex guard until after condvar is triggered

---

sqlx-core/src/transaction.rs
sqlx-postgres/src/connection/mod.rs

The documentation for `PgAdvisoryLockGuard` lists a set of types that should be able to be passed to it, but when actually trying to do so, compilation would fail due to missing `AsMut` trait implementations for those types. This commit adds the missing `AsMut` impls so that `Transaction` and `PgConnection` can be used as type parameters to `PgAdvisoryLockGuard`, as expected.
For reference: https://github.com/launchbadge/sqlx/issues/2520

Impl `AsMut` for advisory lock types (#2520)

---

.github/workflows/examples.yml
CHANGELOG.md
Cargo.lock
Cargo.toml
examples/mysql/todos/Cargo.toml
examples/mysql/todos/src/main.rs
examples/postgres/axum-social-with-tests/Cargo.toml
examples/postgres/files/Cargo.toml
examples/postgres/files/src/main.rs
examples/postgres/json/Cargo.toml
examples/postgres/json/src/main.rs
examples/postgres/listen/Cargo.toml
examples/postgres/listen/src/main.rs
examples/postgres/mockable-todos/Cargo.toml
examples/postgres/mockable-todos/src/main.rs
examples/postgres/todos/Cargo.toml
examples/postgres/todos/src/main.rs
examples/postgres/transaction/Cargo.toml
examples/postgres/transaction/src/main.rs
examples/sqlite/todos/Cargo.toml
examples/sqlite/todos/src/main.rs
sqlx-cli/src/migrate.rs
sqlx-core/Cargo.toml
sqlx-macros-core/Cargo.toml
sqlx-macros/Cargo.toml
sqlx-sqlite/src/options/connect.rs

I have to take off right now for personal reasons but I intend to finish this tonight.
Addendum: this release is going out one (business) day late, but it comes with a last-minute bugfix and I also put in some time to make sure the examples are tested in CI going forward and that they compile against the latest version.

0.7.0 release

---

Cargo.toml

Features of `sqlx-macros` are mostly only enabled when `sqlx-macros` is used, except in a couple places that I fix here.
I use `default-features = false, features = ["runtime-tokio-rustls", "sqlite"]` and currently it also unnecessarily pulls in `sqlx-macros`.

Fix optional dependency on sqlx-macros

---

README.md

0.7.0 is now released on crates.io

Update README.md now that 0.7.0 is no longer in alpha

---

sqlx-macros-core/src/database/postgres.rs
sqlx-postgres/Cargo.toml
sqlx-postgres/src/types/mod.rs
sqlx-postgres/src/types/money.rs
sqlx-postgres/src/types/range.rs

Fix for [this issue](https://github.com/launchbadge/sqlx/issues/2549).
When trying to use the (newly renamed) `rust_decimal` feature in version 7.0.0, compiling fails because there is a missing dependency on `num-bigint` and numerous places in the code where the previous feature name of `decimal` was not updated to the new name of `rust_decimal`. 
Even if one includes the `bigdecimal` feature when using the current code on `main`, `rust_decimal` functionality is not restored (although it is then possible to compile) because the macros still return `BigDecimal` for all `NUMERIC` Postgres types.
This small patch fixes those issues and restores `rust_decimal` functionality.

Fix for Issue #2549 - cannot use feature "rust_decimal" without also using "bigdecimal"

---

Cargo.lock
sqlx-core/Cargo.toml

This avoids the duplicate `rustls-webpki` dependency version

Bump webpki-roots to v0.24

---

README.md
src/lib.md

The feature is called `tls-native-tls`, not `tls-native`:
https://github.com/launchbadge/sqlx/blob/258eacafd9567df89f862cfbad3e8b9d69c22610/Cargo.toml#L77
So all the existing documentation is wrong.
I'd personally probably prefer `tls-native` as a feature name, but I wasn't sure if it's a good move to just change the name of that feature, so I decided to PR the docs change first. :)

Correct mention of the `tls-native-tls` in the documentation.

---

Cargo.lock
sqlx-cli/Cargo.toml

As the derive API of clap@4.0 is fully compatible with clap@3.1.0 (at least the parts that are used)
there is basically no reason not to update it.

Major Version Update clap to 4.0

---

sqlx-core/src/pool/options.rs

Trying to derive `Clone` automatically for `PoolOptions` results in errors when `clone` is actually called. This is because the derive incorrectly determines that `Clone` is _not_ derivable due to the lack of `Clone` implementation on the `DB: Database` type parameter, even though no value of that type is actually stored in a to-be-cloned position (in fact, it's only used for the `Connection` associated type on the type parameter's `Database` trait impl).
Manually implementing `Clone` side-steps this issue and insures the type is always actually cloneable.
For reference: https://github.com/launchbadge/sqlx/issues/2548

Implement `Clone` for `PoolOptions` manually (#2548)

---

sqlx-core/src/migrate/source.rs

fixes #1934
I've made this PR because I got quite confused trying to set up migrations for the first time. I managed to follow the link from the sqlx::migrate macro docs to https://docs.rs/sqlx/latest/sqlx/migrate/trait.MigrationSource.html but never noticed that there was documentation, as it is not expanded by default:
To make this more accessible I have moved the docs to the top level so that they are easier to find.

improve docs about migration files

---

sqlx-core/src/error.rs
sqlx-postgres/src/error.rs

Adds a new `table` function to the `DatabaseError` trait. This change facilitates building
driver-agnostic error handling.
Though only available with the Postgres driver, there's already a `constraint` function that's
also only available through Postgres.
The motivation is partially the same as #2109.

feat(sqlx-core): add table function to database error

---

sqlx-mysql/src/testing/mod.rs

Before this change the first test would always fail with a syntax error.

Remove incorrect CAST in test database cleanup for MySQL.

---

sqlx-core/src/query_builder.rs
sqlx-core/src/query_scalar.rs

This pr try to address #2550 by adding `build_query_scalar` to `QueryBuilder`. 
Closes
https://github.com/launchbadge/sqlx/issues/2539

Introduce build_query_scalar for QueryBuilder

---

CHANGELOG.md

related discussion https://github.com/launchbadge/sqlx/issues/1163#issuecomment-1627685514

docs(changelog): be more verbose about offline mode breaking change

---

sqlx-core/src/types/mod.rs
sqlx-macros-core/src/derives/attributes.rs
sqlx-macros-core/src/derives/type.rs
sqlx-postgres/src/types/array.rs
tests/postgres/derives.rs

feat: allow opt-out of `PgHasArrayType` with `#[derive(sqlx::Type)]`

---

Cargo.toml
sqlx-sqlite/src/any.rs
tests/sqlite/any.rs

Encodes boolean data types as integers when using the `AnyConnection`. This is a partial fix.
It is still not possible to `query_as::<_, (bool,)>`. `AnyRow` expects the bool type info to be
`BOOLEAN` but SQLite returns `INTEGER`.
An options is to modify the `impl Type<Any> for bool`
https://github.com/launchbadge/sqlx/blob/b5312c3b6f8e34e757d1441216b6b34a18afd14b/sqlx-core/src/any/types/bool.rs#L8-L14
and override the default `compatible` function to accept both `AnyTypeInfo::Bool` and `AnyTypeInfo::Integer`,
but this could lead to unintended problems when using other drivers that have a boolean data type.
*Partially* fixes #2592.

fix(sqlite/any): encode bool as integer

---

sqlx-cli/src/lib.rs
sqlx-cli/src/migrate.rs
sqlx-cli/src/opt.rs
sqlx-core/src/migrate/migration_type.rs

Coming from Django migrations, I got used to migrations being named sequentially so I decided to implement support for it in `sqlx`. Timestamp-based naming stays as the default; sequential naming is enabled with `-s` flag to `sqlx migrate add`.

Support naming migrations sequentially

---

sqlx-core/src/net/socket/buffered.rs
sqlx-postgres/src/copy.rs

fixes #2614 
This pull request addresses the issue with the `put_slice` function does not advance the `bytes_written` variable, and that an empty `CopyData` packet is sent with the correct length.

fix(postgres): fix buffer management in PgCopyIn::read_from

---

README.md

Looks like the note on one of the examples was left out when updating for the 0.7 release.

docs: 0.7 is stable in the entire README

---

.github/workflows/examples.yml
Cargo.lock
Cargo.toml
examples/postgres/chat/Cargo.toml
examples/postgres/chat/README.md
examples/postgres/chat/src/main.rs

Closes #161
this is just a continuation of #2165 made by Stephen
i just took his chat implementation and fixed the readme and renamed the folder to chat

supplement Postgres listen example with a small chat example

---

sqlx-mysql/src/types/mod.rs

MySQL does not have a BYTE type.

Documentation typo: BYTE -> BINARY

---

sqlx-postgres/src/types/bytes.rs

Not sure why this isn't implemented. Maybe something I'm missing here?

Adding PgHasArrayType for &[u8;N]

---

sqlx-mysql/src/connection/auth.rs
sqlx-mysql/src/connection/establish.rs
sqlx-mysql/src/options/mod.rs
sqlx-mysql/src/protocol/auth.rs
sqlx-mysql/src/protocol/connect/auth_switch.rs

Fixes https://github.com/launchbadge/sqlx/issues/2443 by implementing `AuthPlugin::MySqlClearPassword` as described in [mysql docs](https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_connection_phase_authentication_methods_clear_text_password.html) and sufficient to connect to a MySQL server hosted by AWS using [IAM authentication with ephemeral passwords](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.Connecting.AWSCLI.html).
For consistency with other clients, like [mysql](https://docs.rs/mysql/latest/mysql/struct.OptsBuilder.html#method.enable_cleartext_plugin), and to avoid accidental security issues, we also add a flag to ConnectionOpts to enable this plugin, as described [here](https://dev.mysql.com/doc/refman/8.0/en/cleartext-pluggable-aut …

Implement mysql_clear_password

---

sqlx-core/src/from_row.rs
sqlx-macros-core/src/derives/attributes.rs
sqlx-macros-core/src/derives/row.rs
tests/mysql/macros.rs

Hello :wave: 
This PR is a proposal to discuss JSON support for the `FromRow` derive. The proposal is to add a new `json` attribute to indicate that a field should be decoded using `sqlx::types::Json` instead of the field type.
The currently existing derive for `FromRow` allows quick and easy type conversions using `TryFrom`. This saves us a lot of boilerplate code just for the sake of converting types. Unfortunately `TryFrom`-based conversions are not enough for json values:
```rust
#[derive(FromRow)]
struct Record {
#[sqlx(try_from = "i64")]
counter: u64,
#[sqlx(try_from = "Json<Metadata>")] // <- Does not work
metadata: Metadata
}
#[derive(serde::Deserialize)]
struct Metadata {
some: String,
fields: String.
}
```
Due to Rust's rules, we can't just add an `impl<T> From<Json<T>> for T` …

Add JSON support to `FromRow` derive

---

.github/workflows/examples.yml
.github/workflows/sqlx.yml
sqlx-macros-core/src/database/mod.rs
sqlx-macros-core/src/test_attr.rs
sqlx-sqlite/src/connection/mod.rs

Fix a few warnings and make it so that all `cargo build` and `cargo check` in CI generate errors if they encounter warnings.  This will ensure cleaner code, and won't hide warnings (they tend to hide if CI doesn't show them as failures)
This PR also fixes example CI - `Chat (Check)` had a yaml error and misnamed target.
Note that `cargo test` still generates a lot of warnings, but they don't trigger build failure

Chore: Fix few build warnings, and make CI fail on warn

---

sqlx-postgres/src/connection/describe.rs
tests/docker-compose.yml

closes #2626 #2622 #2587 
Credit to @mrl5 for the fix, I just wanted to get this merged today without any extra back-and-forth.

fix: ignore extra fields in Postgres describe parsing

---

sqlx-cli/README.md
sqlx-cli/src/migrate.rs
sqlx-core/src/migrate/error.rs
sqlx-core/src/migrate/migration_type.rs

Since sqlx requires all migrations to be of the same type (simple or reversible), it makes sense to automatically set the type of newly generated migration to be the same as the last one if it exists.

Automatically infer migration type

---

sqlx-core/src/executor.rs

As per the Changelog for the 0.7.0 release:
> The Executor impls for Transaction and PoolConnection have been deleted because they cannot exist in the new crate architecture without rewriting the Executor trait entirely.

remove &mut PoolConnection from Executor docs

---

sqlx-core/src/net/socket/mod.rs

Implemented poll_flush for Box<S:Socket>

---

sqlx-core/src/column.rs
sqlx-core/src/row.rs

The `Row` and `ColumnIndex` traits used to be sealed, but that is not the case anymore. This PR removes the obsolete comments from the traits docs.

Remove sealed trait comments from documentation

---

.github/workflows/sqlx.yml
tests/docker-compose.yml
tests/x.py

With MariaDB 10.3 EOL it seems prudent to include the latest 10.11 LTS release in the CI tests.
To catch #1664 sort of issues prior to release, add a container image test for mariadb that contains the finished pre-release code changes (and container changes) to ensure that compatibility is maintianed. When server code hits the branch associated with this tag it is considered finished by its server developers and has passes CI so no regressions are expected, but it wouldn't hurt to have CI in other systems testing it too.
Since MySQL has fixed the regression that caused #1664 this puts it back to their 8.0 release tag.
Append the :z tag to the docker compose volume mounts so on selinux systems enough permissions occur for the volume to be able to read the volume contents.

Bump mariadb CI images + mysql unpin

---

sqlx-mysql/src/types/bytes.rs
sqlx-mysql/src/types/str.rs
sqlx-postgres/src/types/bytes.rs
sqlx-postgres/src/types/str.rs
sqlx-sqlite/src/types/bytes.rs
sqlx-sqlite/src/types/str.rs

This added impls for `Type`, `Decode`, and `Encode` for `Box<str>` and `Box<[u8]>`.
Rational is these types are slightly smaller than `String` and `Vec<u8>` if you do not need the ability to grow the capacity of the types.

Add impl for `Type`, `Decode`, and `Encode` for `Box<str>` and `Box<[u8]>`

---

sqlx-core/src/pool/options.rs

On `PoolOptions::connect()`, we open at least `min_connections` connections, or 1 if unset. Therefore, the expression needs to be `max()`. (`min(1, x)` would mean we always open only a single connection).

docs: Fix description of `min_connections`

---

sqlx-macros-core/src/query/args.rs
sqlx-macros-core/src/query/output.rs
tests/ui/mysql/gated/chrono.stderr
tests/ui/postgres/gated/chrono.stderr
tests/ui/postgres/gated/ipnetwork.stderr
tests/ui/postgres/gated/uuid.stderr

sqlx can give errors like the following:
optional feature `time` required for type TIMESTAMP of param #1
From this error message it is not clear where this feature should be enabled. I initially thought it is some feature that should be enabled in Postgres. People on Stackoverflow [are also confused](https://stackoverflow.com/questions/75376803/rust-actix-web-sqlx-optional-feature-time-required-for-type-timestamptz-of-col) by this error message.
This PR changes this error message to:
optional sqlx feature `time` required for type TIMESTAMP of param #1

Clarify where optional features should be enabled

---

Cargo.lock
sqlx-cli/Cargo.toml

Fix https://github.com/launchbadge/sqlx/issues/2755.
NOTES:
- The comment links to [this issue](https://github.com/rust-lang/rust/issues/29497), which relates to Windows. I don't have a Windows host handy to test, but I have seen that the CI covers it.
- Still, I have manually grepped for the three functions implemented by the crate at that version (https://docs.rs/remove_dir_all/0.7.0/remove_dir_all/index.html) and didn't find any reference in `sqlx-cli`.

Remove unused `remove_dir_all` crate from `sqlx-cli`, fixes RUSTSEC-2023-0018

---

sqlx-mysql/src/options/mod.rs
sqlx-postgres/src/options/mod.rs

This PR adds `ssl_client_cert_from_bytes` and `ssl_client_key_from_bytes` to `MySQL` and `PostgreSQL`.
This will allow slqx to configure tls cert without going through the filesystem. This can be useful in certain scenarios, such as reading certificates from Keychain.

Support for setting client certificate and key from bytes

---

sqlx-postgres/src/types/interval.rs

First of all, thank you for all the hard work you put into this library.
This is required for [these changes](https://github.com/SeaQL/sea-query/pull/709) in SeaQuery to work.

derived Hash trait for PgInterval

---

sqlx-postgres/src/types/time/time.rs
tests/postgres/types.rs

This resolves #2707 
The issue is caused by Postgres.
Specifically, when we select `0:0:0.123` from Postgres, it properly returns `00:00:00.123`.
However, in the case of selecting `0:0:0.0`, it returns `00:00:00`, removing after the `.0`.
This leads to the error `Decode(ParseFromDescription(InvalidLiteral)`, because it does not match the `Time` format.
```
test=# select '0:0:0.0'::time;
time
----------
00:00:00
(1 row)
test=# select '0:0:0.123'::time;
time
--------------
00:00:00.123
(1 row)
```
To solve this, I implemented the same logic as `datetime`.

fix: decode postgres time without subsecond

---

src/macros/mod.rs

I needed offline mode for my application and found the `query` macro documentation, but I spend some time trying to understand where the `offline` feature needed to be enabled. I had to go into the [changelog](https://github.com/launchbadge/sqlx/blob/main/CHANGELOG.md#breaking) to found out it has been removed and is now the default behavior.
This PR just remove the documentation stating it requires the `offline` feature, as this behavior is now unconditionnal.

Remove documentation on offline feature

---

Cargo.toml

I had been running into compilation failures because async-std's `task::spawn_blocking` function was marked as private. Upgrading my project to use async-std 1.12 fixed compilation, but I wondered why sqlx didn't encode this requirement.
The function was stabilized in async-std 1.12 (https://github.com/async-rs/async-std/pull/1017) -- according to what I read, `spawn_blocking` previously required a feature flag. It seems sensible to declare this requirement in sqlx.

Depend on version of async-std with non-private spawn-blocking

---

sqlx-mysql/src/connection/stream.rs
sqlx-mysql/src/protocol/packet.rs
tests/mysql/mysql.rs

This will allow packets over 16mb to be sent and received by handling splitting packets. (https://mariadb.com/kb/en/0-packet/#packet-splitting)
Fixes #189

feat(mysql): support packet splitting

---

sqlx-mysql/src/testing/mod.rs
sqlx-postgres/src/testing/mod.rs

As described in https://github.com/launchbadge/sqlx/issues/2631, the #[sqlx::test] macro is occasionally failing to connect to the created database.
- The PR I submitted before, #2635, trying to fix the race condition to ensure the current timestamp was acquired in the proper order didn't cover all the cases
- So I realize that the issue may be that the `SystemTime is not monotonic`, as we can see [from the documentation](https://doc.rust-lang.org/std/time/struct.SystemTime.html):
> Distinct from the [Instant](https://doc.rust-lang.org/std/time/struct.Instant.html) type, this time measurement is not monotonic. This means that you can save a file to the file system, then save another file to the file system, and the second file has a SystemTime measurement earlier than the first. In other …

fix: sqlx::macro db cleanup race condition by adding a margin to current timestamp

---

Cargo.lock
sqlx-postgres/Cargo.toml
sqlx-postgres/src/types/rust_decimal.rs
tests/mysql/types.rs
tests/postgres/types.rs

also fixes handling of feature flags
fixes #666

fix: correct decoding of `rust_decimal::Decimal` for high-precision values

---

sqlx-postgres/src/transaction.rs

This attempts to make Postgres's begin step more cancel safe than it used to be. 
1. Using execute to perform a `begin` is overkill, so I have switched to using the simple query protocol like sqlx uses in drop-rollback - this is inspired by tokio-postgres.
2. Implement a short lived drop-rollback struct to start the rollback incase of error/panic/cancel during `wait_until_ready`
Because we guarantee to write a BEGIN/SAVEPOINT to the PgStream, any drops will definitely rollback to that point and not to a parent BEGIN. The previous impl could be cancelled at the prepare/bind and not need to be rolled back, so applying this drop guard would not be so safe
cc #2805

postgres begin cancel safe

---

FAQ.md
sqlx-cli/src/prepare.rs
sqlx-macros-core/Cargo.toml
sqlx-macros-core/src/query/data.rs
sqlx-macros-core/src/query/mod.rs

Replaces #2787 and fixes #2663

Don't use separate temp dir for query jsons (2) 

---

sqlx-postgres/src/listener.rs

This is often encountered when the host the db is on is restarted. For example, a reboot of AWS Aurora cauases this. If we don't handle this properly the PgListeners are stuck in an erroring state, even when the DB is back online. By catching it here, we will reconnect when it is (eventually) back online.

Make PgListener recover from UnexpectedEof

---

Cargo.lock
sqlx-core/src/from_row.rs
sqlx-macros-core/src/derives/attributes.rs
sqlx-macros-core/src/derives/row.rs
tests/postgres/derives.rs

This commit adds `sqlx(default)` as a struct attribute when deriving `FromRow` - imitating the similar behaviour of `serde(default)`. E.g. the following two definitions are equivalent:
```rust
#[derive(sqlx::FromRow)]
#[sqlx(default)]
struct Options {
option_a: Option<String>,
option_b: Option<i32>,
}
```
derives the same `FromRow` implementation as
```rust
#[derive(sqlx::FromRow)]
struct Options {
#[sqlx(default)]
option_a: Option<String>,
#[sqlx(default)]
option_b: Option<i32>,
}
```

derive FromRow: sqlx(default) for all fields

---

Cargo.lock
sqlx-macros-core/src/query/mod.rs

Customize the macro error message based on the metadata

---

.gitignore
tests/docker.py
tests/sqlite/.gitignore
tests/sqlite/any.rs
tests/x.py

Hello!
I found some bugs in `tests/x.py`.
Is it maintained?
Also, I tried fix it and made some small improvements.
Please use this if you like.
Here's contents of fixing and improvements.
In Macos and Linux, download ipaddr binary when running `tests/x.py`.
However, they are targeting git modifications and it takes time and effort to remove them from the commit target.
So I added to gitignore ipaddr library files.
In Linux, shared libraries in the current directory are not loaded, so add the current directory to the LD_LIBRARY_PATH environment variable.
In sqlite it_encodes_bool_with_any, originally it was inserted by specifying the primary key.
However, Since it_encodes_bool_with_any is executed for each test cases, it is conflicted.
So I removed specific primary key in insert.
From a …

Is tests/x.py maintained? And I tried fix it.

---

sqlx-core/src/net/socket/mod.rs

This commit updates the error handling logic in the `connect_tcp` function. Previously, the function would panic if the hostname did not resolve to at least one address.
The updated logic attempts to establish a TCP connection for each address that the hostname resolves to. If it fails to connect to any of the addresses, it will return the last encountered error. If the hostname doesn't resolve to any addresses, the function returns a custom error message stating "Hostname did not resolve to any addresses".
closes #2821

issue #2821 Update error handling logic when opening a TCP connection

---

sqlx-core/src/from_row.rs

I expected that I could trivially make `()` from a row, but didn't find this implementation

Add impl `FromRow` for the unit type

---

sqlx-postgres/src/options/mod.rs

add get_host function in `PgConnectOptions`.

Enhancement #2747 Provide `fn PgConnectOptions::get_host(&self)`

---

sqlx-core/src/ext/async_stream.rs

fix(core): avoid unncessary wakeups in `try_stream!()`

---

sqlx-cli/src/opt.rs

The old description for the `sequential` flag read "If set, use *timestamp* versioning". I guess this was a simple copy-paste error.

Fix comment in `sqlx migrate add` help text

---

sqlx-postgres/src/options/mod.rs

Update `extra_float_digits` to default to `2` instead of `3` to address https://github.com/launchbadge/sqlx/issues/801 following the advice provided in https://github.com/launchbadge/sqlx/pull/2708.

Update extra_float_digits default to 2 instead of 3

---

sqlx-macros-core/src/database/mod.rs

When none of the features is enabled (default features), prevent compiler warnings.

Prevent warnings running `cargo build`

---

sqlx-postgres/src/types/rust_decimal.rs

The `scale` field in `PgNumeric` was not being used to set the correct scale in rust_decimal. Set the scale then added/extended unit tests. #2247

Fixes rust_decimal scale for Postgres

---

sqlx-mysql/src/types/bigdecimal.rs
sqlx-mysql/src/types/rust_decimal.rs

fixes https://github.com/readysettech/readyset/issues/143
When using readyset as a caching proxy - readyset returns a decimal with the following type info `MySqlTypeInfo { type: Decimal, flags: ColumnFlags(0x0), char_set: 33, max_size: Some(1024) }`
Currently rust_decimal and bigdecimal expect an exact match for the type info `MySqlTypeInfo { type: NewDecimal, flags: ColumnFlags(BINARY), char_set: 63, max_size: None }`
Therefore the following error  occurs when readyset sends a valid decimal type
```
error occurred while decoding column "price": mismatched types; Rust type `core::option::Option<rust_decimal::decimal::Decimal>` (as SQL type `DECIMAL`) is not compatible with SQL type `DECIMAL`
```
This patch makes the `Type<MySql> for Decimal` more lenient by matching `MySqlTypeInfo` that …

fix: Make rust_decimal and bigdecimal decoding more lenient

---

sqlx-sqlite/src/connection/establish.rs

fix(sqlite): use `AtomicUsize` for thread IDs

---

FAQ.md

Update Faq - Bulk upsert with optional fields 

---

sqlx-mysql/src/options/mod.rs

The Postgres implementation has this method. It is also helpful for queries that require the current database name. example:
```sql
SELECT table_name FROM INFORMATION_SCHEMA.TABLES WHERE table_name = ? &&
table_schema = ?;
```
No

Add `MySqlConnectOptions::get_database()` 

---

sqlx-sqlite/src/types/mod.rs

doc(sqlite): cover lack of `NUMERIC` support

---

sqlx-postgres/src/migrate.rs

When force dropping database from the cli, database name is expected to be in single quotes.

Fixed force dropping bug

---

Cargo.toml
sqlx-core/Cargo.toml
sqlx-core/src/types/mod.rs
sqlx-core/src/types/text.rs
sqlx-mysql/src/types/mod.rs
sqlx-mysql/src/types/text.rs
sqlx-postgres/src/types/array.rs
sqlx-postgres/src/types/mod.rs
sqlx-postgres/src/types/text.rs
sqlx-sqlite/src/types/mod.rs
sqlx-sqlite/src/types/text.rs
tests/mysql/types.rs
tests/postgres/types.rs
tests/sqlite/types.rs

This will allow users to store and retrieve values of types we don't support, as long as they have `Display` and `FromStr` impls.
Caveat: this does not toggle the text format for PostgreSQL, to allow direct input and output of otherwise unsupported types, though it theoretically could.

feat: `Text` adapter

---

README.md

whitespace is being interpreted by the a tag causing blue hyperlinks to show up between the badges.
Sorta :)

Fixed ReadMe badge styling

---

sqlx-postgres/src/copy.rs

This pull request addresses a potential hang in `PgCopyIn::read_from` caused by `conn.stream.flush().await?;`. The flush call appears to be unnecessary at this point, as the write buffer has already been flushed in `PgCopyIn::begin`.

fix(postgres): avoid unnecessary flush in PgCopyIn::read_from

---

sqlx-core/src/from_row.rs

Fix a tiny doc error:
https://docs.rs/sqlx/latest/sqlx/trait.FromRow.html#default

fix duplicate "`" in FromRow "default" attribute doc comment

---

Cargo.lock
sqlx-core/Cargo.toml

sqlx-core doesn't use dotenvy. Removing it means that users who only
depend on sqlx with sqlite and default-feature = false don't need it.

sqlx-core: Remove dotenvy dependency

---

sqlx-macros-core/src/query/mod.rs

Eagerly calling https://github.com/launchbadge/sqlx/blob/929af41745a9434ae83417dcf2571685cecca6f0/sqlx-macros-core/src/query/mod.rs#L80 results in build failure in Bazel builds.

Support `query!` for cargo-free systems

---

Cargo.lock
sqlx-core/Cargo.toml

Update ahash to version 0.8.7 to resolve vulnerability RUSTSEC-2023-0074.
```
Crate:     zerocopy
Version:   0.7.26
Title:     Some Ref methods are unsound with some type parameters
Date:      2023-12-14
ID:        RUSTSEC-2023-0074
URL:       https://rustsec.org/advisories/RUSTSEC-2023-0074
Solution:  Upgrade to >=0.2.9, <0.3.0 OR >=0.3.2, <0.4.0 OR >=0.4.1, <0.5.0 OR >=0.5.2, <0.6.0 OR >=0.6.6, <0.7.0 OR >=0.7.31
Dependency tree:
zerocopy 0.7.26
└── ahash 0.8.6
├── sqlx-core 0.7.3
│   ├── sqlx-sqlite 0.7.3
│   │   ├── sqlx-macros-core 0.7.3
│   │   │   └── sqlx-macros 0.7.3
│   │   │       └── sqlx 0.7.3
│   │   │           ├── sqlx-test 0.1.0
│   │   │           │   └── sqlx 0.7.3
│   │   │           ├── sqlx-sqlite 0.7.3
│   │   │           ├── sqlx-example-sqlite-todos 0.1.0
│   │ …
```

chore: Update ahash to 0.8.7

---

FAQ.md

It comes up often enough (#2993) and the database manuals aren't always helpful so I figured I'd finally write up an explanation myself.

doc(FAQ): add entry explaining prepared statements

---

sqlx-postgres/src/connection/executor.rs
tests/postgres/postgres.rs

Currently this for PostgreSQL only, but if the fix would be accepted I can apply it to the other databases as well.
Fixes #1370

Fix handling of deferred constraints

---

sqlx-mysql/src/connection/executor.rs
tests/mysql/mysql.rs

This pull request fixes an issue that prepared statements are not closed if persistence or statement cache are disabled.
```rust
use sqlx::{Connection, MySqlConnection, Row};
#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
let url = std::env::var("DATABASE_URL")?;
let mut connection = MySqlConnection::connect(&url).await?;
for i in 0..10 {
let _ = sqlx::query("SELECT ? AS val")
.bind(i)
.persistent(false)
.fetch_one(&mut connection)
.await?;
}
let rows = sqlx::query(
r#"
SELECT 
psi.STATEMENT_ID
, psi.SQL_TEXT
FROM performance_schema.threads AS t
INNER JOIN performance_schema.prepared_statements_instances AS psi
ON psi.OWNER_THREAD_ID = t.THREAD_ID 
WHERE t.processlist_id = CONNECTION_ID()
"#,
)
.fetch_all(&mut connection)
.await?;
for row in rows {
let id: u64 …
```

fix(mysql): Close prepared statement if persistence is disabled

---

sqlx-mysql/src/options/mod.rs
sqlx-postgres/src/options/mod.rs

Exposes some of the main fields for PgConnectOptions and
MySqlConnectOptions. Exposed fields include host, port, socket, 
ssl mode, application name, and charset via getters.
It didn't seem like a good idea to expose passwords and SSL certificates.
Other less relevant fields also don't look necessary.
Partially solves #2764 by creating getters for most fields.

feat: expose getters for connect options fields

---

Cargo.lock
Cargo.toml
tests/sqlite/sqlcipher.rs

Last release of `tempdir` was [six years ago](https://crates.io/crates/tempdir/versions).

chore(deps): Replace unmaintained tempdir crate with tempfile

---

sqlx-postgres/src/types/interval.rs

I've noticed that compared all other sqlx data types `PgInterval` does not implement `Default` trait. As a result it's not possible to use methods like `unwrap_or_default()` with this data type. 
This PR adds `PgInterval::default()` implementation.

Add default implementation for PgInterval

---

sqlx-mysql/src/types/inet.rs
sqlx-mysql/src/types/mod.rs

Allow using `IpAddr`/`Ipv4Addr`/`Ipv6Addr` with the mysql driver.
These can also be used with MariaDB's INET4 and INET6 types.

Added support to IpAddr with MySQL/MariaDB.

---

Cargo.lock
Cargo.toml
sqlx-bench/Cargo.toml

Resolves advisory [RUSTSEC-2021-0145](https://rustsec.org/advisories/RUSTSEC-2021-0145) related to `atty` crate by using a newer version of `criterion` that does not have `atty` as a dependency.

chore(deps): Upgrade criterion to 0.5.1

---

Cargo.lock
Cargo.toml
sqlx-test/Cargo.toml

Upgrade the `env_logger` dependency.
Only used in `dev-dependencies` (`sqlx-test` is not published).

chore(dev-deps): Upgrade env_logger from 0.9 to 0.11

---

sqlx-postgres/src/types/money.rs

Similar to this PR https://github.com/launchbadge/sqlx/pull/3013 this one adds default implementation for `PgMoney`.

Add default implementation for PgMoney

---

.gitignore

Manually running the CI steps locally results in the creation of a `.sqlx` folder in the repo root that does not belong in source control.
Ignore that folder.

chore: Ignore .sqlx folder created by running ci steps locally

---

sqlx-core/src/logger.rs

This is a partial resolution to https://github.com/launchbadge/sqlx/issues/2671.
I chose `elapsed_ms` over `elapsed_us` as sub-millisecond latencies are not likely interesting for a relational database query, and individuals searching and filtering logs would find milliseconds more convenient.
I also left the existing `elapsed` string field in place in case it is being used by others in ops and monitoring (which seems to be the case with @Matthias247).

feat(logging): Add numeric elapsed time field elapsed_secs

---

sqlx-core/src/net/socket/mod.rs

Fixed https://github.com/launchbadge/sqlx/issues/3043
Based on https://www.man7.org/linux/man-pages/man3/setsockopt.3p.html#ERRORS, I think it's better to propagate the error than ignore it but happy to change that

Set TCP_NODELAY option on TCP sockets

---

sqlx-postgres/Cargo.toml
sqlx-postgres/src/connection/sasl.rs

Don't recreate the HMAC, just [reset](https://docs.rs/hmac/latest/hmac/trait.Mac.html#tymethod.finalize_reset). That feature exists for a reason :) This makes postgres sasl auth 2-3ms faster (or 40ms in debug mode). 
Benchmark results (with `+nightly` `#![feature(test)]` `extern crate test;`) on M1 Pro:
before: 
```
test connection::sasl::bench_sasl_hi                                        ... bench:   4,004,666 ns/iter (+/- 73,042)
```
after 
```
test connection::sasl::bench_sasl_hi                                        ... bench:   2,065,200 ns/iter (+/- 15,375)
```

Optimize SASL auth in sqlx-postgres

---

sqlx-core/src/lib.rs
sqlx-core/src/query.rs
sqlx-core/src/query_as.rs
sqlx-core/src/query_scalar.rs
sqlx-core/src/raw_sql.rs
src/lib.rs
tests/mysql/mysql.rs
tests/postgres/postgres.rs
tests/sqlite/sqlite.rs

This is meant to be much easier to discover than the current approach of directly invoking `Executor` methods.
In addition, I'm improving documentation for the `query*()` functions across the board.
This also deprecates `.execute_many()` and `.fetch_many()` on these types because only the SQLite driver actually ever supported multiple statements in a single query string with the prepared statement interface, and that's just a consequence of the fact that it handles all statements as prepared statements.

feat: add `raw_sql` API

---

sqlx-cli/src/migrate.rs

Show latest url to docs for macro.migrate

---

Cargo.lock
sqlx-macros-core/Cargo.toml
sqlx-macros-core/src/query/data.rs

This provides the same functionality but without temporary files, platform-specific code, fragility of `O_TMPFILE` support, and an extra dependency.

Use `create_new` instead of `atomic-file-write`

---

sqlx-macros-core/src/test_attr.rs

This patch addresses an issue with the `#[sqlx::test]` attribute macro that causes problems when used in conjunction with the [insta](https://github.com/mitsuhiko/insta) snapshot testing library.
```rust
#[sqlx::test(migrator = "mymodule::migrator")]
async fn select_foo(pool: PgPool) {
let res = my_function_to_test(pool);
insta::assert_debug_snapshot!(res); // we expect insta to generate a snapshot file named `mymodule__tests__select_foo.snap`
} 
```
When using `sqlx::test`, the test code is wrapped inside an inner function, which can lead to snapshot files being generated with the name of the inner function (`inner`), causing filename conflicts when multiple functions exist within the same module.
```rust
// expanded code
#[test]
fn select_foo() {
async fn inner(pool: PgPool) {
let res = …
```

Change the name of "inner" function generated by `#[sqlx::test]`

---

sqlx-mysql/src/options/connect.rs
sqlx-mysql/src/options/mod.rs

Hi, I ran into some issues connecting with a MariaDB Instance behind [ProxySQL](https://github.com/sysown/proxysql) (I would guess, that the Variables are not replicated correctly to the cluster).
I don't have any access to the Database or the Logs and thus can't debug that much but found out, that the only differences to other MySQL Drivers are the Parameters set after connecting to the Instance.
I have found this Issue #2389 and after hacking around a bit, I found that turning off the initialization "fixes" my problem.
This PR gives an option to disable the Default Behavior after connecting. I haven't touched the defaults, so there should be no breaking behavior.

feat(mysql): allow to connect with mysql driver without default behavor

---

.github/workflows/sqlx.yml
sqlx-core/src/migrate/source.rs

fix(migrate): improve error message when parsing version from filename

---

Cargo.lock
sqlx-postgres/Cargo.toml

There's no open issue for it. But SHA1 is not cryptographically secure and it wasn't being used in sqlx-postgres.

Remove sha1 because it's not being used in postgres

---

.github/workflows/sqlx.yml
Cargo.toml
sqlx-postgres/src/types/bigdecimal-range.md
sqlx-postgres/src/types/bigdecimal.rs
sqlx-postgres/src/types/mod.rs
sqlx-postgres/src/types/rust_decimal-range.md
sqlx-postgres/src/types/rust_decimal.rs
tests/postgres/postgres.rs
tests/sqlite/sqlcipher.rs

fix: do not panic when binding a large BigDecimal

---

sqlx-core/src/any/options.rs
sqlx-core/src/connection.rs
sqlx-mysql/src/options/connect.rs
sqlx-mysql/src/options/mod.rs
sqlx-mysql/src/options/parse.rs
sqlx-postgres/src/options/connect.rs
sqlx-postgres/src/options/parse.rs
sqlx-sqlite/src/options/connect.rs
sqlx-sqlite/src/options/mod.rs
sqlx-sqlite/src/options/parse.rs

Add a `get_url` to `ConnectOptions` and implement it for all needed types; add `get_filename` for `SqliteConnectOptions`. These changes make it easier to test sqlx.
Fixes #2901
Related to #2764

feat: add `to_url_lossy` to connect options

---

sqlx-core/src/migrate/migrator.rs
sqlx-core/src/migrate/mod.rs
sqlx-core/src/migrate/source.rs
sqlx-macros-core/src/migrate.rs

Migrations fixes

---

sqlx-macros-core/src/database/postgres.rs
sqlx-macros-core/src/database/sqlite.rs

Replicates the same approach done by the MySQL compatibility layer and only enables `chrono` types
if `time` is disabled.
I expect this to close #2689.

fix(macros): only enable chrono when time is disabled

---

Cargo.toml

This PR bumps the `bigdecimal` version to enable using the latest `bigdecimal` crate version solving #2719.

Closes #2719 by bumping bigdecimal version

---

Cargo.lock
sqlx-macros-core/Cargo.toml
sqlx-macros-core/src/database/mod.rs
sqlx-macros-core/src/derives/attributes.rs
sqlx-macros-core/src/derives/encode.rs
sqlx-macros-core/src/derives/mod.rs
sqlx-macros-core/src/query/args.rs
sqlx-macros-core/src/test_attr.rs
sqlx-macros/Cargo.toml
sqlx-macros/src/lib.rs
src/macros/mod.rs

This PR bumps the `syn` crate to the new major 2.0 version. Following what some of the dependencies
are using as well (`serde 1.0.159`, `futures 0.3.27`, `tokio 1.26.0`).
It seems like now is a good time to bump before the 0.7 release. Some of the breakages include:
* `AttributeArgs` no longer exists, we must `Punctured` directly;
* `NestedMeta` no longer exists.
* `LifetimeDef` is now `LifetimeParam`;
* No more support for type ascription;
The `parse_nested_meta` replaces whatever would be done using `AttributeArgs`.

chore: bump syn to 2.0

---

sqlx-core/src/column.rs
sqlx-core/src/connection.rs
sqlx-core/src/row.rs
sqlx-core/src/value.rs

The `Database` trait's associated types are constrained using `Connection<Database = Self>` but this constraint is not specified for the reverse `Database<Connection = Self>`. This causes issues when wrapping or "extending" sqlx traits since as far as rust's type system is concerned `Self::Connection::Database::Connection != Self::Connection`. 
Consider the following example: 
```rust
type DatabaseTypeOf<T> = <<T as ConnectOptions>::Connection as Connection>::Database;
pub trait OptionWrapper {
type Pool: Pool;
async fn connect(self) -> Self::Pool;
}
impl <T> OptionWrapper for T
where
T: ConnectOptions,
for<'a> &'a mut T::Connection: Executor<'a, Database = DatabaseTypeOf<T>>,
{
type Client = Pool<DatabaseTypeOf<T>>;
async fn connect(self) -> Self::Pool { …
```

Constrain cyclic associated types to themselves

---

sqlx-core/src/any/arguments.rs
sqlx-core/src/arguments.rs
sqlx-core/src/query.rs
sqlx-core/src/query_as.rs
sqlx-core/src/query_builder.rs
sqlx-core/src/query_scalar.rs

Initial PR that removes all the `Send` trait bounds from various argument binding methods. While the argument buffer makes sense to be `Send` as it might be passed around, arguments passed in are immediately encoded away, so it does not seem to be required for them to be `Send`.
The PR could be expanded to add an `Encode` impl for `std::fmt::Arguments` (the initial motivation for removing the bounds) and even make the `Text` adapter rely on it when getting encoded.
Fixes #2959

Removed `Send` trait bound from argument binding

---

sqlx-sqlite/src/connection/handle.rs
sqlx-sqlite/src/connection/mod.rs
sqlx-sqlite/src/connection/worker.rs

This suddenly became an error for some reason. I guess tuple fields recently started getting checked by the `dead_code` lint.

fix(sqlite): delete unused `ConnectionHandleRaw` type

---

sqlx-mysql/src/protocol/statement/row.rs
sqlx-mysql/src/types/chrono.rs
sqlx-mysql/src/types/float.rs
sqlx-mysql/src/types/int.rs
sqlx-mysql/src/types/mod.rs
sqlx-mysql/src/types/mysql_time.rs
sqlx-mysql/src/types/time.rs
sqlx-mysql/src/types/uint.rs
tests/mysql/types.rs

Also clarifies the handling of `TIME` (we never realized it's used for both time-of-day and signed intervals) and adds appropriate impls for `std::time::Duration`, `time::Duration`, `chrono::TimeDelta`
fixes #3144
fixes #2691

feat: add `MySqlTime`, audit `mysql::types` for panics

---

Cargo.toml
README.md
sqlx-macros-core/Cargo.toml
sqlx-macros-core/src/lib.rs
sqlx-macros/Cargo.toml
sqlx-macros/src/lib.rs
src/lib.rs

As mentioned in https://github.com/launchbadge/sqlx/pull/2482#issuecomment-1992717206, the current `macros` flag enables a ton of unrelated things. Personally, my use of SQLx is almost always limited to the derive macros, and I don't want to be bombarded with `query_*!` macros every time I enable the derives. The new `derive` feature flag solves this.
Derives will still be enabled when using the `macros` feature.

feat: new derive feature flag

---

sqlx-core/src/lib.rs
sqlx-core/src/type_checking.rs
sqlx-macros-core/src/database/impls.rs
sqlx-macros-core/src/database/mod.rs
sqlx-macros-core/src/query/args.rs
sqlx-macros-core/src/query/output.rs
sqlx-mysql/src/lib.rs
sqlx-mysql/src/type_checking.rs
sqlx-postgres/src/lib.rs
sqlx-postgres/src/type_checking.rs
sqlx-sqlite/src/lib.rs
sqlx-sqlite/src/type_checking.rs

Motivated by #2917
cc @g-bartoszek you can build your changes onto this. Just use `Postgres::fmt_value_debug()`

refactor: lift type mappings into driver crates

---

Cargo.toml
sqlx-sqlite/Cargo.toml

This includes SQLite v3.45(.1), which includes new JSONB functionality.

Bump libsqlite3-sys to v0.28

---

Cargo.lock
sqlx-sqlite/Cargo.toml
sqlx-sqlite/src/connection/establish.rs

This drops the [unmaintained](https://github.com/kornelski/rust_urlencoding/commit/3cc277fc4e577a0bef99294d7ab9bc85232f0730) and scary looking use of the `urlencoding` crate with a more proper implementation using `serde_urlencoded` and `percent-encoding`

Drop urlencoding dependency

---

sqlx-core/src/logger.rs
sqlx-core/src/pool/inner.rs
sqlx-core/src/pool/mod.rs
sqlx-core/src/pool/options.rs

If the connection pool is full, and all connections are in use, the next request for a connection involving `PoolInner::acquire` will block until a connection is released back to the pool.
* Track the time taken to acquire a connection from the connection pool
* Warn if a time threshold is exceeded
* Threshold duration is configurable via `PoolOptions` 
* Threshold defaults to three seconds, which should be reasonable to prevent false positives for apps connecting to a database server that is nearby on the network
The default tries to avoid reporting a slow acquire when the pool grows itself within its capacity limit by creating a new connection.

feat(logging): Log slow acquires from connection pool

---

.github/workflows/sqlx.yml

https://github.com/actions/runner-images/issues/9557

fix(ci): use `docker compose` instead of `docker-compose`

---

sqlx-core/src/migrate/error.rs
sqlx-mysql/src/migrate.rs
sqlx-postgres/src/migrate.rs
sqlx-sqlite/src/migrate.rs

Yes - it shows following output:
```
❯ sqlx migrate run --ignore-missing
error: while executing migration 20240314125700: error returned from database: column "email" of relation "customer_status_extended" already exists
```
fixes #3129

Add version information for failed cli migration (#3129)

---

Cargo.lock
sqlx-core/Cargo.toml
sqlx-macros-core/Cargo.toml
sqlx-mysql/Cargo.toml
sqlx-postgres/Cargo.toml

This cleans up the dep tree of projects depending and should duplicates over time. rustls still needs updating, but it seems like quite extensive migration is needed which I didn't feel comfortable to perform.

Bump deps that do not need code changes

---

Cargo.lock
Cargo.toml
sqlx-sqlite/src/types/time.rs

Update time to 0.3.36

---

Cargo.lock
sqlx-sqlite/src/any.rs
sqlx-sqlite/src/connection/explain.rs
sqlx-sqlite/src/type_checking.rs
sqlx-sqlite/src/type_info.rs
sqlx-sqlite/src/types/bool.rs
sqlx-sqlite/src/types/chrono.rs
sqlx-sqlite/src/types/int.rs
sqlx-sqlite/src/types/mod.rs
sqlx-sqlite/src/types/time.rs
sqlx-sqlite/src/types/uint.rs
sqlx-sqlite/src/value.rs
tests/sqlite/any.rs
tests/sqlite/macros.rs

Breaking changes:
* integer decoding will now loudly error on overflow instead of silently truncating.
* some usages of the `query!()` macros might change an `i32` to an `i64`.
Also adds support for *decoding* `u64`s because there's no reason not to.
Closes #3179
Supercedes #3180
@elsirion can you try this and confirm it fixes the problem?

[BREAKING} fix(sqlite): always use `i64` as intermediate when decoding

---

sqlx-core/src/migrate/migration.rs
sqlx-core/src/migrate/migrator.rs
sqlx-core/src/migrate/source.rs
sqlx-macros-core/src/migrate.rs
sqlx-postgres/src/migrate.rs
src/macros/test.md
tests/postgres/migrate.rs
tests/postgres/migrations_no_tx/0_create_db.sql
tests/postgres/test-attr.rs

Yes, this change allows for a way to create migrations that will be executed outside of the postgres transaction block.
It works as described in this [comment](https://github.com/launchbadge/sqlx/issues/767#issuecomment-943782775)
fixes #767 
😬 accidentally closed #3159 when looking at merge conflicts

feat: no tx migration

---

sqlx-postgres/src/types/int.rs

fix(postgres) : int type conversion while decoding

---

sqlx-postgres/src/copy.rs
tests/postgres/postgres.rs

While using COPY and transactions I kept running into errors.
This PR includes a test case that triggers that error, it fails with:
Error: encountered unexpected or invalid data: expecting ParseComplete but received CommandComplete
The second commit contains the actual fix
~fixes~validates error of #3139

PostgreSQL Bugfix: Ensure connection is usable after failed COPY inside a transaction

---

Cargo.lock
sqlx-core/src/any/type_info.rs
sqlx-core/src/any/value.rs
sqlx-core/src/types/mod.rs

fix: Option decoding in any driver

---

Cargo.lock
sqlx-postgres/src/row.rs

fixes #150
Adds partial `Debug` impl for `PgRow`. Utilises a mapping between `PgType` variants and types. For the variants for which the mapping is not defined falls back to string or binary representation.

Add Debug impl for PgRow

---

sqlx-mysql/src/any.rs

When using the 'Any' driver with MySQL backend, fetch_optional does not return the connection to the pool if no results are returned from the query. This is due to not all of the packets being read from the underlying stream.
This fix continues to read result packets from the stream until they have all been exhausted (just like the normal MySql drivers implementation of fetch_optional). In general, a better refactoring would be to call the MySQL fetch_optional code in the Any driver, rather than re-implementing and duplicating code.
fixes #(2647)

Fix leaking connections in fetch_optional (#2647)

---

Cargo.lock
sqlx-core/Cargo.toml

This fixes security issue RUSTSEC-2024-0336 [1].
[1] https://rustsec.org/advisories/RUSTSEC-2024-0336

security: bump rustls to 0.21.11

---

sqlx-sqlite/src/options/mod.rs

Make `get_filename` usable? Unless I was missing how to use it.

fix: get_filename should not consume self

---

sqlx-sqlite/src/options/mod.rs

Setting the auto_vacuum pragma must come before setting the journal mode otherwise it won't apply.
Simple test app:
```rust
use sqlx::sqlite::SqliteAutoVacuum;
use sqlx::sqlite::SqliteJournalMode;
use sqlx::sqlite::SqliteSynchronous;
use sqlx::Connection;
use sqlx::SqliteConnection;
#[tokio::main]
async fn main() {
let options = sqlx::sqlite::SqliteConnectOptions::new()
.create_if_missing(true)
.filename("./test.sqlite")
.synchronous(SqliteSynchronous::Off)
.auto_vacuum(SqliteAutoVacuum::Full)
.journal_mode(SqliteJournalMode::Wal);
let mut conn = SqliteConnection::connect_with(&options).await.unwrap();
let auto_vacuum: u8 = sqlx::query_scalar("PRAGMA auto_vacuum")
.fetch_one(&mut conn)
.await
.unwrap();
println!("auto_vacuum = {auto_vacuum}");
}
```
In current git main, if `journal_mode` …

fix: sqlite pragma order for auto_vacuum

---

sqlx-core/src/migrate/source.rs
sqlx-macros-core/src/migrate.rs

When using `--cfg=sqlx_macros_unstable` the codepath taken uses the `path` variable which was taken earlier by `resolve_blocking`; this is solved by having `resolve_blocking` take a reference, as it is more convenient than cloning.
Yes (however I did not create an issue here).
I was trying to get the effect of triggering recompilation on migration changes by setting the nightly flag as described here: https://docs.rs/sqlx/latest/sqlx/macro.migrate.html#nightly-rust-cfg-flag
But when adding to `.cargo/config.toml`:
```
[build]
rustflags = ["--cfg=sqlx_macros_unstable"]
```
and having the `sqlx::migrate!` macro in the code, the following error appears while compiling `sqlx-macros-core`:
```
error[E0382]: borrow of moved value: `path`
|
98  |     let path = path.canonicalize().map_err(|e| { …
```

fix: resolve `path` ownership problems when using `sqlx_macros_unstable`

---

sqlx-sqlite/src/options/mod.rs

SqliteConnectOptions::filename() memory fix (#3136)

---

sqlx-sqlite/src/connection/explain.rs
sqlx-sqlite/src/connection/intmap.rs
sqlx-sqlite/src/connection/mod.rs
sqlx-sqlite/src/logger.rs
tests/sqlite/describe.rs

Improve diagnostic log message of sqlite explain processing to illustrate HOW the explain planner arrives to the output data types it finds. Then add a few simple fixes found with the improved diagnostic view.
Example command to get the dot format graphviz:
``` 
RUST_LOG="sqlx::explain=trace" DATABASE_URL=sqlite://tests/sqlite/sqlite.db cargo test --features sqlite,runtime-tokio,tls-rustls,chrono -- --nocapture update
```
Then the graphviz markup can be copy-pasted into the graphviz renderer/editor of choice. The process isn't elegant, but it works.
**Warning**: this only actually works when running a program which directly uses the 'describe' operation (such as sqlx's sqlite unit tests). Logger output is not available when compiling a library USING sqlx (the output is ignored - probably …

Sqlite explain graph

---

sqlx-macros-core/src/derives/decode.rs
sqlx-macros-core/src/derives/encode.rs

fix: Decode and Encode derives (#1031)

---

sqlx-core/Cargo.toml
sqlx-core/src/types/mod.rs
sqlx-core/src/types/non_zero.rs

This commits adds `Type`, `Encode`, and `Decode` impls for all the `NonZero*` types from the standard library. They are implemented as direct proxies to their primitive counterparts, except that when decoding, the values are checked to not be zero.
fixes #1926

feat: support `NonZero*` scalar types

---

.github/workflows/sqlx.yml

With MariaDB upstream fixing the TLS issue (about to be confirmed in the CI test), adding back 11.4 (now GA/stable) and verylatest - now 11.5rc.
fixes: #3091

ci: MariaDB - add back 11.4 and add 11.5

---

sqlx-mysql/src/connection/establish.rs
sqlx-mysql/src/connection/executor.rs
sqlx-mysql/src/connection/mod.rs
sqlx-mysql/src/options/connect.rs
sqlx-mysql/src/transaction.rs

This could be helpful in reducing Future sizes when `MySqlPool` is being used.
On my platform size of `MySqlConnection` is 272 bytes. `MySqlPool` returns it by value, then it may be passed around within application's code as well. Mainly this is noticeable due to Future sizes quickly growing. Not a big problem, considering it's easy to `.boxed()` them as necessary, but seems like there's an easy improvement that can be made on `sqlx` side by putting contents of `MySqlConnection` inside of a `Box` internally, which reduces connection size to just 8 bytes.
Example:
```rust
async fn query(pool: Option<&sqlx::MySqlPool>) -> u64 {
let mut conn = pool.unwrap().acquire().await.unwrap();
sqlx::query_scalar("SELECT * FROM table")
.fetch_one(&mut *conn)
.await
.unwrap()
}
fn main() {
let fut = …
```

perf: box `MySqlConnection` to reduce sizes of futures

---

sqlx-postgres/src/lib.rs

Currently you can call `begin()` on a postgres transaction without causing an error.
This causes errors such as:
```rust
let url = "postgres://dario@localhost/sqlx".parse().unwrap();
let opts: PgConnectOptions = ConnectOptions::from_url(&url).unwrap();
let pool = PgPoolOptions::new()
.max_connections(10)
.connect_with(opts)
.await
.expect("PgPool");
sqlx::query("drop table if exists sqlx_issue").execute(&pool).await.unwrap();
sqlx::query("create table sqlx_issue (name varchar(255))").execute(&pool).await.unwrap();
sqlx::query("insert into sqlx_issue (name) values ('issue')").execute(&pool).await.unwrap();
{
let mut trans: Transaction<'static, Postgres> = pool.begin().await.unwrap();
// Call begin again()
trans.begin().await.unwrap();
sqlx::query("delete from sqlx_issue").execute(&mut …
```

fix: hide `sqlx_postgres::any`

---

sqlx-sqlite/src/connection/establish.rs
sqlx-sqlite/src/connection/mod.rs
sqlx-sqlite/src/lib.rs
sqlx-sqlite/src/statement/mod.rs
tests/sqlite/sqlite.rs

Fixes #3114 
This is an initial pass at exposing the Sqlite update hook.  I used set_progress_handler as a guide.  This allows the consuming code to register a callback on the connection and receive the operation, database name, table name, and rowid of the affected record.
I'm in the process of adding listener functionality in my own code which will use channels to publish data changes but thought that may be out of scope for sqlx itself.

feat: Add set_update_hook on SqliteConnection

---

sqlx-sqlite/src/types/mod.rs

https://www.sqlite.org/lang_datefunc.html

docs(sqlite): fix typo - unixtime() -> unixepoch()

---

sqlx-postgres/src/options/parse.rs

The names for the SSL mode options were incorrect, added test for making sure the built url can be parsed to ensure internal consistency at least. Also changed "ssl-mode" to "sslmode" (as well as other ssl properties) as it seems more standard and sqlx can parse both.
fixes #3255

fix: use correct names for sslmode options

---

sqlx-mysql/src/protocol/text/column.rs
sqlx-mysql/src/type_info.rs
sqlx-mysql/src/types/bool.rs
sqlx-mysql/src/types/str.rs
sqlx-mysql/src/types/uint.rs

Compatibility check in`<str as sqlx::Type<sqlx::MySql>>::compatible(tv)` for collation is not necessary because collation does not affect to output string.
RELATE: #1241

MySQL: Remove collation compatibility check for strings

---

sqlx-postgres/src/any.rs

This `PgType::Bool` type is now mapped to the `Any` type `Bool`.
fixes #3290

feat: support the Postgres Bool type for the Any driver

---

Cargo.lock
Cargo.toml
sqlx-core/Cargo.toml
sqlx-core/src/ext/ustr.rs
sqlx-core/src/lib.rs
sqlx-core/src/type_info.rs
sqlx-core/src/types/mod.rs
sqlx-macros-core/src/derives/type.rs
sqlx-postgres/Cargo.toml
sqlx-postgres/src/arguments.rs
sqlx-postgres/src/connection/describe.rs
sqlx-postgres/src/connection/establish.rs
sqlx-postgres/src/connection/executor.rs
sqlx-postgres/src/connection/mod.rs
sqlx-postgres/src/type_info.rs
sqlx-postgres/src/types/array.rs
sqlx-sqlite/src/connection/explain.rs
tests/migrate/macro.rs
tests/postgres/derives.rs
tests/postgres/setup.sql

Potential breaking change: `PgTypeInfo::with_name()` infers types that start with `_` to be arrays of the un-prefixed type. Wrap type names in quotes to bypass this behavior.

fix: correct handling of arrays of custom types in Postgres

---

examples/postgres/axum-social-with-tests/tests/common.rs
examples/postgres/files/src/main.rs
examples/postgres/listen/src/main.rs

Fix causes of some of the `cargo check` warnings getting flagged in CI jobs.
This set is all in the `postgres` examples.
`#[track_caller]` is not supported on `async` functions. The rest are unused imports.

refactor: Resolve cargo check warnings in postgres examples

---

.github/workflows/sqlx.yml
Cargo.toml
sqlx-core/Cargo.toml
sqlx-mysql/Cargo.toml
sqlx-mysql/src/types/chrono.rs
sqlx-postgres/Cargo.toml
sqlx-sqlite/Cargo.toml

Prevents future occurrences of situations similar to https://github.com/launchbadge/sqlx/issues/3118, where a change was made to `sqlx` to resolve a deprecation warning, the change is not supported by the dependency version declared in `Cargo.toml`, and the lock file has a newer version than what is declared `Cargo.toml`.
New CI job forces a downgrade of all dependencies to their minimum versions (ignoring the committed lock file), and attempts to compile the crate and its tests.
In `Cargo.toml`, the `chrono` and `log` crates were both upgraded to the oldest version that allowed the `sqlx` crate to build. This did not impact the lock file, which has newer versions of both.

ci: Add job to check that sqlx builds with its declared minimum dependencies

---

sqlx-macros-core/src/test_attr.rs

Invert boolean for `migrate` error message. (#3275)

---

sqlx-core/src/any/arguments.rs
sqlx-core/src/any/mod.rs
sqlx-core/src/any/row.rs
sqlx-core/src/any/value.rs
sqlx-sqlite/src/any.rs

This PR fixes an issue occurring when:
- A value `None : Option<T>` is bound to a query, and that query executed.
- The same query is later executed with a value `Some(t: T) : Option<T>`.
Since queries are cached by default, the type of value considered for the bound parameter is `Option::<i32>::None`.
This will raise a Postgres error on the second execution `"incorrect binary data format in bind parameter <n>"`.
The fix consists in storing the value type of null values (using the result of the `encode` function to determine if the value is null), and then using a `None` value with the correct type (for example `Option::<String>::None` to persist a nullable `TEXT` value).
I am quite new to the `sqlx` library and there might be a better implementation but this one seems to be quite …

Track null arguments in order to provide the appropriate type when converting them.

---

sqlx-core/src/any/connection/backend.rs
sqlx-core/src/any/connection/executor.rs
sqlx-mysql/src/any.rs
sqlx-postgres/src/any.rs
sqlx-sqlite/src/any.rs

This PR passes the `query.persistent()` value to the `fetch_many` and `fetch_optional` function so that they can use it to cache prepared queries.
Note I have kept the existing logic for the SQLite driver where persisting queries requires both the persistent flag _and_ the existence of arguments.

Pass the `persistent` query setting when preparing queries with the `Any` driver

---

sqlx-postgres/src/message/response.rs

This has been observed with an old version of PostgreSQL (11.0.4) running on Windows Server 2016 with windows-1252 encoding and French locale.
This change replaces invalid UTF-8 fields with a default string, so the other fields can still be read if they are valid.
fixes #3345

fix(postgres): don't panic if `M` or `C` Notice fields are not UTF-8

---

sqlx-core/src/type_checking.rs

no, basically it is just a typo I came across during trying to debugg https://github.com/launchbadge/sqlx/issues/3316
The `$crate::` is currently not nessesary, but future refactorings might get tripped up if the typo is not fixed

chore: fixed one usage of `select_input_type!()` being unhygenic

---

sqlx-postgres/src/types/int.rs

Implements `PgHasArrayType` for `NonZeroI16`, `NonZeroI32` and `NonZeroI64`

add array support for NonZeroI* in postgres

---

sqlx-macros-core/Cargo.toml

As discussed (or more accurately missed by me), the `json` feature should also activate the postgres' related `json` feature.
(I thought that you might like this as a PR as this is simpler for you to accept. If you want your commit in your name, that is fine too ^^)
| Before | After |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/52a0bbdc-81a5-4baf-972b-cff6bcc0e730) | ![image](https://github.com/user-attachments/assets/4f0e490c-5bfa-4f17-b202-e92851c7b3dc) | 
Fixes https://github.com/launchbadge/sqlx/issues/3316

fix:the `json`-feature should activate `sqlx-postgres?/json` as well

---

sqlx-postgres/src/types/hstore.rs
sqlx-postgres/src/types/mod.rs

Adds support for postgres hstore data type by mapping it to a BTreeMap<String, Option>. Using a BTreeMap rather than a HashMap ensures that the keys remain sorted. This is helpful for auto generated history data. Previously discussed as #151.

Add support for PostgreSQL HSTORE data type

---

sqlx-cli/src/migrate.rs

When generating the build script, it will fail `cargo fmt -- --check` because it is missing a new line at the end of the file.
There is no existing issue for this, I thought the fix was easy enough that it was best discussed in a MR :) I'm happy to create an issue for this to link to if that is preferable.
When running `sqlx migrate build-script` CLI, it fails cargo-fmt. cargo-fmt suggests adding a newline at EOF. This was found because our CI runs `cargo fmt` as a CI step and it failed :)
Existing behaviour:
```bash
~/Projects/sqlx/sqlx-cli $ cargo run -- migrate build-script                      
Compiling sqlx-cli v0.8.0-alpha.0 (/Users/jahrens/Projects/sqlx/sqlx-cli)
Finished `dev` profile [unoptimized + debuginfo] target(s) in 2.36s
Running …
```

fix: build script new line at eof

---

Cargo.lock
Cargo.toml
sqlx-cli/Cargo.toml
sqlx-cli/tests/add.rs
sqlx-macros-core/Cargo.toml

During https://github.com/launchbadge/sqlx/issues/3348 I noticed that there is no testcase for the `sqlx migrate add ...` command. This PR proposes such a testcase.
I don't know how usefull this testcase is (as the testcase is working and has not found any bugs..).
Rejecting this PR because this is not worth your time is fine by me ^^

chore:added a testcase for `sqlx migrate add ...`

---

sqlx-macros-core/src/derives/row.rs
src/lib.rs
src/spec_error.rs
tests/postgres/derives.rs

fixes #3344 
Breaking because `#[sqlx(default)]` on an individual field or the struct itself would have previously suppressed the error. This doesn't seem like good behavior as it could result in some potentially very difficult bugs.
Instead of using `TryFrom` for these fields, just implement `From` and apply the default explicitly.

breaking: fix name collision in `FromRow`, return `Error::ColumnDecode` for `TryFrom` errors

---

sqlx-core/src/any/connection/backend.rs
sqlx-core/src/any/mod.rs
sqlx-core/src/database.rs
sqlx-core/src/executor.rs
sqlx-core/src/from_row.rs
sqlx-core/src/pool/mod.rs
sqlx-mysql/src/options/mod.rs
sqlx-mysql/src/types/mod.rs
sqlx-mysql/src/types/mysql_time.rs
sqlx-postgres/src/advisory_lock.rs
sqlx-postgres/src/copy.rs
sqlx-postgres/src/types/lquery.rs
sqlx-postgres/src/types/ltree.rs
sqlx-postgres/src/types/money.rs
sqlx-sqlite/src/options/mod.rs

There seemed to be many broken links and intra-doc links in the rust docs, fixed a bunch of them along with a few other warnings.
However I am not able to fix some intra-doc links and I don't known if they are possible to fix. 
They have in common in that they are links in sqlx-core and they need to reference an item from the other libraries, for example in [pool](https://github.com/launchbadge/sqlx/blob/0eb2ee93650eaf10d9cadc107a88bfabfdf377a7/sqlx-core/src/pool/mod.rs#L19-L22), but since they are not dependencies of sqlx-core i don't seem to be able to reference them (if they were dependencies it would cause a cyclic dependency however).

doc: Minor rust docs fixes

---

sqlx-core/src/transaction.rs

fixes #2699 by providing an example on how to use a transaction as an executor when trying to execute queries with it.

Add example on how to use Transaction as Executor

---

sqlx-sqlite/src/connection/mod.rs

Use "c_char" instead of "i8" as it resolves to the correct string type on different architectures.
Fixes: #3287

fix: sqlite update_hook char types

---

Cargo.lock
Cargo.toml
sqlx-macros-core/src/derives/type.rs
sqlx-mysql/src/type_info.rs
sqlx-test/Cargo.toml
tests/mysql/derives.rs

Fix encoding and decoding of MySQL enums in `sqlx::Type`

---

src/lib.rs

The `spec_error` module implements the autoref specialization hack that's used in a single place in the derive macros. It wasn't meant to be a public API.
Given how arcane it must appear, I doubt anyone's tried using it outside of this project anyway.

doc: hide `spec_error` module

---

Cargo.lock
examples/mysql/todos/Cargo.toml
examples/mysql/todos/src/main.rs
examples/postgres/json/Cargo.toml
examples/postgres/json/src/main.rs
examples/postgres/mockable-todos/Cargo.toml
examples/postgres/mockable-todos/src/main.rs
examples/postgres/todos/Cargo.toml
examples/postgres/todos/src/main.rs
examples/sqlite/todos/Cargo.toml
examples/sqlite/todos/src/main.rs

Replaces structopt with clap in examples.

chore: replace structopt with clap in examples

---

Cargo.lock
sqlx-cli/Cargo.toml

docs.rs for this package currently does not build due to yanked dependencys
=> This is a yanked dependency https://docs.rs/cargo_metadata/0.14.3/cargo_metadata/index.html
I have followed the commit trail from https://github.com/oli-obk/cargo_metadata/blame/d7d326f8458bf7dbc7af380c454e922a5661898d to https://github.com/oli-obk/cargo_metadata/blame/709d508c54593e4ee0ef00e94dd04a6158e6e5d7/Cargo.toml and have not found things which are breaking for our usage

fix(dependencys):bumped cargo_metadata to `v0.18.1` to avoid yanked `v0.14.3`

---

tests/postgres/types.rs
tests/sqlite/types.rs

During looking into why that one testcase in https://github.com/launchbadge/sqlx/pull/3382 is not passing, I noticed that there are quite some deprectations for testcases.
This PR resolves some simple ones => reducing the noise

chore(tests): fixed deprecation warnings

---

Cargo.lock
examples/postgres/chat/Cargo.toml
examples/postgres/chat/src/main.rs

Currently, the `postgres/chat` example uses `tui`. Said library is unmaintained and switching to ratatui is recomended.
Advisory: https://rustsec.org/advisories/RUSTSEC-2023-0049
Proof that this still works:

chore(examples):Migrated the pg-chat example to ratatui

---

sqlx-sqlite/src/any.rs
sqlx-sqlite/src/connection/executor.rs
sqlx-sqlite/src/connection/mod.rs
sqlx-sqlite/src/connection/worker.rs

Fixes #3120
As far as I can tell, this fixes https://github.com/launchbadge/sqlx/issues/2099 (and I think https://github.com/launchbadge/sqlx/issues/3120, which appears to be the same)
My minimal reproduction looks like this (which is adapted from the example in https://github.com/launchbadge/sqlx/issues/2099):
```rust
use sqlx::sqlite::SqlitePoolOptions;
#[tokio::main]
async fn main() {
let sqlite_options = sqlx::sqlite::SqliteConnectOptions::new()
.filename("test.db")
.busy_timeout(std::time::Duration::from_secs(5))
.journal_mode(sqlx::sqlite::SqliteJournalMode::Wal)
.create_if_missing(true);
let db = SqlitePoolOptions::new()
.acquire_timeout(std::time::Duration::from_secs(5))
.max_connections(5)
.min_connections(5)
.connect_with(sqlite_options)
.await
.unwrap();
sqlx::query("create …
```

sqlite: fix inconsistent read-after-write

---

sqlx-cli/src/lib.rs
sqlx-cli/src/opt.rs
sqlx-cli/src/prepare.rs

Fix `cargo sqlx prepare --workspace` running `cargo clean -p sqlx` unnecessarily. 
See https://github.com/launchbadge/sqlx/issues/2785
This should be a non-breaking change. It shouldn't affect in-workspace dependencies that happen to be named `sqlx` either.
- Checkout this branch and install `sqlx-cli`.
```sh
cargo install -f --path ./sqlx-cli
```
- Run `cargo sqlx prepare --workspace` in a project with crates that use `query!` macros.  
The timing difference is quite significant in a larger workspace, saves ~40 seconds on an incremental build.
**BEFORE:**
```bash
$ time cargo sqlx prepare --database-url "postgresql://postgres:password@localhost/example" --workspace -- --all-targets --all-features
Cleaning [=============================] 1/1: sqlx, 0 files/folders cleaned 
...
Finished …
```

fix(sqlx-cli): do not clean sqlx during prepare

---

.github/workflows/sqlx.yml
Cargo.lock
Cargo.toml
README.md
sqlx-core/Cargo.toml
sqlx-core/src/net/tls/tls_rustls.rs
sqlx-macros-core/Cargo.toml
sqlx-macros/Cargo.toml
src/lib.md

Upgrade rustls to 0.23.x. The tricky part here is that rustls since 0.22 exposes two `CryptoProvider` implementations here. So far I've exposed separate features for each, but this still runs the risk that a project that ends up with crates selecting rustls with different crypto providers picks an unexpected one. I guess there's not much of a solution for that, but open to feedback about what you think the right direction is for sqlx.

Upgrade to rustls 0.23

---

sqlx-mysql/src/options/connect.rs
sqlx-mysql/src/options/mod.rs

no_engine_subsitution is named wrongly. giving a lot of issues when working with ai.
replaced
no_engine_subsitution
to 
no_engine_substitution

correct spelling of `MySqlConnectOptions::no_engine_substitution()`

---

sqlx-core/src/types/json.rs

fixes #3153 by providing an example on how to use the `Json` adapter by using type override syntax.

Clarify usage of Json/Jsonb in query macros

---

sqlx-macros-core/src/query/mod.rs
sqlx-macros-core/src/query/output.rs

This fixes a rust-analyzer warning when a query has a non snake-case name. It simply adds a `#[allow(non_snake_case)]` lint to the generated struct and variables.
Fixes: #3361

fix: non snake case warning

---

sqlx-postgres/src/types/cube.rs
sqlx-postgres/src/types/hstore.rs

Resolves #3461
Resolves #3460
Replaces #3457
Replaces #3456
The Postgresql cube type fails to compile in version 0.8.1:
```
.../sqlx-postgres-0.8.1/src/types/cube.rs:307:33
|
307 |     const PACKED_WIDTH: usize = size_of::<u32>();
|                                 ^^^^^^^ not found in this scope
|
help: consider importing one of these items
|
1   + use core::mem::size_of;
|
1   + use std::mem::size_of;
```
The PR includes a patch for this as well as a scoping change for the hstore type to keep it consistent with the others.

Pgsql cube type compile fail

---

sqlx-postgres/src/connection/executor.rs
sqlx-postgres/src/message/bind.rs
sqlx-postgres/src/message/parameter_description.rs
sqlx-postgres/src/message/parse.rs
tests/postgres/query_builder.rs

fix(postgres): max number of binds is 65535, not 32767 (regression)

---

sqlx-core/src/net/socket/buffered.rs
sqlx-core/src/pool/connection.rs
sqlx-postgres/src/connection/stream.rs
sqlx-postgres/src/listener.rs

fixes #3419
fixes #2956 
fixes #886

fix cancellation issues with `PgListener`, `PgStream::recv()`

---

sqlx-postgres/src/types/chrono/datetime.rs

https://github.com/launchbadge/sqlx/issues/703#issuecomment-2272616894
Fix inspired by https://github.com/launchbadge/sqlx/pull/1618/files

fix: Use rfc3339 to decode date from text

---

CHANGELOG.md
Cargo.lock
Cargo.toml
FAQ.md
rust-toolchain.toml
sqlx-mysql/src/io/buf_mut.rs

Refines MSRV policy to prevent accidental breakage during a release cycle while still allowing us to use newer language/stdlib features.
Fixes #3472

Release 0.8.2

---

sqlx-postgres/src/column.rs
sqlx-postgres/src/message/row_description.rs

I'm building a tool that does introspection on queries that requires reading relation_id and attribute number from postgres queries. Today, sqlx keeps those fields private.
This PR exposes those fields, along with a small data type correction to relation_id - it's an Oid, which is a u32, not a i32.

expose relation_id and relation_attribution_no on PgColumn

---

sqlx-sqlite/src/types/mod.rs

doc(sqlite): document behavior for zoned date-time types

---

sqlx-sqlite/src/connection/establish.rs
sqlx-sqlite/src/connection/mod.rs
tests/sqlite/sqlite.rs

This PR adds the sqlite commit and rollback hooks which is useful in conjunction with the sqlite update hook when using transactions.  The sqlite update hook fires before a transaction is committed or rolled back.  Using the commit and rollback hooks allows clients to queue update notifications and process them appropriately when the transaction is complete.

Add sqlite commit and rollback hooks

---

tests/mysql/mysql.rs
tests/mysql/setup.sql

This isn't a solution for #3484, as that seems to be an issue with privileges on the user's side. However, in the process of figuring that out, I realized we never explicitly test password-less auth.

chore(mysql): create test for passwordless auth (#3484)

---

sqlx-sqlite/src/options/mod.rs

It took me 15 minutes of messing around and googling to find `.connect_with()`.
Took me also a couple of minutes to find the SqliteConnectOptions, but I wouldn't know where to mention that in the docs.

doc(sqlite): show how to turn options into a pool

---

Cargo.lock
sqlx-cli/Cargo.toml
sqlx-core/Cargo.toml
sqlx-postgres/Cargo.toml

There are quite some unused dependencies in sqlx-core and sqlx-cli. And one crate from sqlx-postgres.
Cargo builds with all features after removing these dependencies.

Remove unused dependencies from sqlx-core, sqlx-cli and sqlx-postgres

---

sqlx-macros-core/src/test_attr.rs
tests/postgres/test-attr.rs

fixes #3534
This fixes a regression in the `sqlx::test` macro, this pr makes it work inside macro's. The error message seems to also have been changed by accident between version `0.7.4` and `0.8.0` so I changed it back.

fix: using sqlx::test macro inside macro's

---

sqlx-postgres/src/connection/describe.rs
sqlx-postgres/src/connection/establish.rs
sqlx-postgres/src/connection/executor.rs
sqlx-postgres/src/connection/mod.rs
sqlx-postgres/src/copy.rs
sqlx-postgres/src/listener.rs
sqlx-postgres/src/transaction.rs

This boxes the fields of `PgConnection` to make it cheaper to move around just like in #3265.

Box Pgconnection fields

---

.github/workflows/sqlx.yml
Cargo.toml
README.md
sqlx-cli/Cargo.toml
sqlx-cli/README.md
sqlx-cli/src/database.rs
sqlx-cli/src/opt.rs
sqlx-core/src/any/kind.rs
sqlx-macros-core/Cargo.toml
sqlx-macros-core/src/database/impls.rs
sqlx-macros-core/src/database/mod.rs
sqlx-macros-core/src/derives/decode.rs
sqlx-macros-core/src/derives/type.rs
sqlx-macros-core/src/lib.rs
sqlx-macros/Cargo.toml
sqlx-sqlite/Cargo.toml
sqlx-sqlite/src/lib.rs
src/any/mod.rs
src/lib.rs
tests/ui-tests.rs

fixes #191 as suggested in https://github.com/launchbadge/sqlx/issues/191#issuecomment-2351342278.

Add a "sqlite-unbundled" feature that dynamically links to system libsqlite3.so library

---

sqlx-postgres/src/type_checking.rs
sqlx-postgres/src/types/hstore.rs
tests/postgres/macros.rs
tests/postgres/migrations/4_hstore.sql
tests/postgres/setup.sql

This allows the use of `PgHstore` in the query macros.
Fixes: #3488

Support PgHstore by default in macros

---

Cargo.lock
sqlx-core/Cargo.toml
sqlx-core/src/logger.rs
sqlx-sqlite/src/logger.rs
src/ty_match.rs

…rmatOptions
Yes
"fixes #3544 "

fix: remove `sqlformat`

---

sqlx-postgres/src/options/pgpass.rs

As per the discussion in that issue, let's make this a `debug` warning. And I hope @jajcus doesn't mind me jumping on this - but I noticed it yesterday, and had to submit a PR. :)
Fixes #3531

Demote `.pgpass` file warning to a debug message.

---

sqlx-postgres/src/type_checking.rs

```
error: unsupported type INTERVAL[] of column #2 ("event_offsets")
```
Hello, I'm querying array of intervals, but sqlx give that error. 
That PR fixes it

Fix: Cannot query Postgres `INTERVAL[]`

---

sqlx-mysql/src/types/mod.rs
sqlx-mysql/src/types/uuid.rs

doc(mysql): document difference between `Uuid` and `uuid::fmt::Hyphenated`

---

sqlx-postgres/src/connection/describe.rs

Instead of generating nullable query using `VALUES`, use `UNION ALL` syntax.
Current query:
```
SELECT NOT attnotnull FROM (
VALUES
( $1::int4, $2::int4, $3::int2 ),
( $3::int4, $4::int4, $5::int2 ),
) AS col(idx, table_id, col_idx) ...
```
Becomes:
```
SELECT NOT attnotnull FROM (
( SELECT $1::int4 AS idx, $2::int4 AS table_id, $3::int2 AS col_idx )
UNION ALL ( SELECT $1::int4, $2::int4, $3::int2 )
) AS col ...
```
This change allows better support for databases that support a `pgwire` interface but with limited SQL syntax. In particular, timeseries databases such as QuestDB and kdb are unsupported.

Use `UNION ALL` instead of `UNION` in nullable check

---

Cargo.lock
sqlx-core/Cargo.toml
sqlx-macros-core/Cargo.toml
sqlx-sqlite/Cargo.toml

fixes #3589
(I verified that `rustup default 1.80; cargo update -p url --precise 2.5.3; cargo check`) fails without this changeset and succeeds with it.)

Remove default-features = false from url

---

sqlx-postgres/src/type_checking.rs
sqlx-postgres/src/types/geometry/mod.rs
sqlx-postgres/src/types/geometry/point.rs
sqlx-postgres/src/types/mod.rs
sqlx-test/src/lib.rs
tests/postgres/types.rs

Part 1 of fixing https://github.com/launchbadge/sqlx/issues/166

feat: point

---

sqlx-postgres/src/options/parse.rs

Connecting to databases with non-standard characters in the db name fails.
```rust
let connection_uri = "postgres://postgres:postgres@localhost:5432/test db";
let mut connection = PgConnection::connect(connection_uri).await?;
let results = sqlx::query("SELECT * FROM test")
.fetch_all(&mut connection)
.await?;
```
Fails with `database "test%20db" does not exist`
Creating a connection configuration, and then setting the db name explicitly, fixes the issue:
```rust
let connection_uri = "postgres://postgres:postgres@localhost:5432/test db";
let connect_options = PgConnectOptions::from_url(&connection_uri.parse()?)?;
let connect_options = connect_options.database("test db");
let mut connection = PgConnection::connect_with(&connect_options).await?;
let results = sqlx::query("SELECT * FROM …
```

fix: URL decode database name when parsing connection url

---

sqlx-core/src/query_as.rs

query_as.rs: 230 mismatched bracket.
query_as.rs: 230 move TIMESTAMP to TIMESTAMPTZ to match type time::OffsetDateTime.
query_as.rs: 241, 251, 260 move i64 to i32 to match postgres type `INT4`.
fixes #3557

fix: fix example code of `query_as`

---

sqlx-postgres/src/listener.rs

When `PgListener`'s underlying connection is closed, `try_recv()` will return `Ok(None)` and reconnect on the next call. In this case, user code is supposed to reload its state from the database (or otherwise handle potentially missing messages). However, if the user code uses another database connection to do so then there is a period between when the state is reloaded and `PgListener`'s connection is re-established where notifications are lost without any indication that this has happened.
This commit changes `PgListener` to eagerly reconnect by default. At the suggestion of @abonander on discord, I have also included an option to switch back to the old behaviour in the case where someone was depending on it.
Now, if the connection is closed then, by default, user code can do whatever …

Eagerly reconnect in `PgListener::try_recv`

---

sqlx-postgres/src/listener.rs
tests/postgres/postgres.rs

Hello! I wanted to support batch processing of notifications when there is a lot of them, so it made sense to grab whatever notifications might be readily available. `try_next()` is unsuitable for that, since if the buffer is empty, I don't want to wait for a new NOTIFY to happen before progressing with the batch. So, it seemed to make sense to add a new non-async method that is essentially the first buffer check of `try_recv()`, and then call that in a loop to build up a batch until it returns None (or a batch limit is released).
I updated `try_recv()` to call the new function, just to make things as DRY as possible, but it isn't a huge improvement. Happy to revert that part if you prefer.
Also happy to bikeshed the new method's name/interface. A couple options I considered were:
```rust …
```

Add PgListener::next_buffered(), to support batch processing of notifications

---

sqlx-mysql/src/options/parse.rs

Identify the timezone when parsing the url and set it by `MySqlConnectOptions::timezone`.
For example: `mysql://user:pass@host/db?timezone=+08:00`

parse timezone parameter in mysql connection url

---

sqlx-postgres/src/types/interval.rs
sqlx-postgres/src/types/range.rs

I looked for them in `sqlx-postgres`, `sqlx-mysql`, `sqlx-sqlite` and `sqlx-core`.
I would assume this change is desirable.

Derive Copy where possible for database-specific types

---

Cargo.lock
Cargo.toml
README.md
sqlx-core/Cargo.toml
sqlx-core/src/net/tls/tls_rustls.rs
sqlx-macros-core/Cargo.toml
sqlx-macros/Cargo.toml

This adds an alternative TLS configuration that relies on `rustls-native-certs`, for users who cannot bundle the MPL-licensed `webpki-roots`.
The approach is copied from `reqwest`:
* https://github.com/seanmonstar/reqwest/blob/3ad6e02cd/Cargo.toml#L48
* https://github.com/seanmonstar/reqwest/blob/3ad6e02cd/src/async_impl/client.rs#L513
— except error handling is relaxed to accommodate for `tls_config.root_cert_path`.

Support building with rustls but native certificates

---

sqlx-postgres/src/types/lquery.rs

An lquery array can be used with the `?` operator for "Does ltree match any lquery in array?"
Documentation: https://www.postgresql.org/docs/current/ltree.html#LTREE-OPS-FUNCS
fixes #2246

Add support for Postgres lquery arrays

---

Cargo.lock
sqlx-core/src/net/socket/mod.rs
sqlx-core/src/net/tls/mod.rs
sqlx-mysql/src/connection/establish.rs
sqlx-mysql/src/connection/tls.rs
sqlx-postgres/src/connection/describe.rs
sqlx-postgres/src/connection/stream.rs
sqlx-postgres/src/connection/tls.rs

* Since rust 1.77 recursion in async functions is supported. This pr removes a few `BoxFuture`'s now that these are not necessary anymore.
* Also removes `BoxFuture`'s in the `WithSocket` trait which should not be a breaking change.

chore: remove BoxFuture's (non-breaking)

---

Cargo.lock
sqlx-postgres/src/type_checking.rs
sqlx-postgres/src/types/geometry/line.rs
sqlx-postgres/src/types/geometry/mod.rs
sqlx-postgres/src/types/mod.rs
sqlx-test/src/lib.rs
tests/postgres/types.rs

Part 2 of fixing https://github.com/launchbadge/sqlx/issues/166

feat: add geometry line

---

.github/workflows/sqlx.yml
tests/docker-compose.yml
tests/x.py

This drops Postgres 11 and 12, which are EOL, and brings in 16 and 17 into the test suite.
I haven't tried running the tests locally yet

Roll PostgreSQL 11..=15 tests to 13..=17

---

sqlx-postgres/src/connection/describe.rs

QuestDB has the same limitation as Materialize and CockroachDB when parsing `EXPLAIN` statements.
This PR applies the same fix as in https://github.com/launchbadge/sqlx/pull/1386 and https://github.com/launchbadge/sqlx/pull/2282.
This change makes the new 8.2.0 release of QuestDB and `sqlx` minimally compatible.

Dont use `EXPLAIN` in nullability check for QuestDB

---

sqlx-postgres/src/listener.rs

This PR handles `TimedOut` and `BrokerPipe` errors that could be returned by [tcp](https://man7.org/linux/man-pages/man7/tcp.7.html) layer:
```
EPIPE  The other end closed the socket unexpectedly or a read is
executed on a shut down socket.
ETIMEDOUT
The other end didn't acknowledge retransmitted data after
some time.
```
In these cases it makes sense to close listener connection proactively.

close listener connection on TimedOut and BrokenPipe errors

---

sqlx-mysql/src/lib.rs
sqlx-postgres/src/lib.rs
sqlx-sqlite/src/lib.rs
src/lib.rs

This pr adds `Transaction` type aliases. I feel like this would make sense since there are also aliases for `Pool`, `Executor` and `PoolOptions` and this is something I often try and reach for.

feat: add Transaction type aliases

---

sqlx-cli/tests/add.rs

This fixes a regression introduced by #3352 that make tests fail to build on 32 bit platforms, caused by this function [^1] trying to compare a number bigger than what `usize` can represent on those platforms.
I've also suggested clippy add a lint [^2] for this kind of things.
[^1]: https://github.com/launchbadge/sqlx/blob/9d74aeae5253a5bcdf07c5e3f581a6282e609eac/sqlx-cli/tests/add.rs#L36-L46
[^2]: https://github.com/rust-lang/rust-clippy/issues/13943

fix(cli): running tests on 32bit platforms

---

sqlx-core/src/row.rs

Row::get should track caller for a better development experience.
the reason for that is that if I have a code like this
my_file.rs
```
10 |    row.get("non_existing_col")
```
I would get error message like
```
thread panicked at 
/../sqlx-core-0.7.4/src/row.rs:72:37:
called `Result::unwrap()` on an `Err` value: ColumnNotFound("non_existing_col")
```
if I have #[track_caller] I would get error like:
```
thread panicked at 
/../my_crate/src/my_file.rs:10:37:
called `Result::unwrap()` on an `Err` value: ColumnNotFound("non_existing_col")
```
Which helps debugging because backtraces are difficult to deal with and are disabled by default in rust.
no, as far as my search

add `#[track_caller]` to `Row::get()`

---

sqlx-core/src/type_checking.rs

fixes #3683
Prints `NULL` in the debug impl for `Row` when an `UnexpectedNullError` is encountered.
A query like
```sql
SELECT NULL::TEXT, 'test'
```
Prints
`Row {text: NULL, ?column?: "test"}`

fix: handle nullable values by printing NULL instead of panicking

---

Cargo.lock
sqlx-postgres/src/copy.rs

While looking into #3696 I noticed that `CopyData` uses an `i32` to represent the length prefix. However, the `AsyncRead` impl uses an `u32`. https://github.com/launchbadge/sqlx/blob/a83395a360296db1251e6e4138b6e6331912c3d4/sqlx-postgres/src/copy.rs#L233

fix(postgres) use signed int for length prefix in `PgCopyIn`

---

sqlx-postgres/src/arguments.rs
sqlx-postgres/src/type_info.rs

As for https://github.com/launchbadge/sqlx/pull/1736, this allows to reuse them in retry loops with query_with.
Closes #3695

Derive clone and debug for postgresql arguments

---

sqlx-sqlite/src/connection/worker.rs

Unfortunately this fix could not be one line because the order of the expressions matter.
Fixes #3662

fix(Sqlite): stop sending rows after first error

---

sqlx-postgres/src/type_checking.rs
sqlx-postgres/src/types/geometry/line_segment.rs
sqlx-postgres/src/types/geometry/mod.rs
sqlx-postgres/src/types/mod.rs
tests/postgres/types.rs

Does your PR solve an issue?
Part 3 of fixing https://github.com/launchbadge/sqlx/issues/166

feat: add postres geometry line segment

---

sqlx-postgres/src/copy.rs
sqlx-postgres/src/lib.rs
tests/postgres/postgres.rs

Sends the data of `PgCopyIn` in chunks of `((1 GiB - 1) - 1) - 4`.
As for #3701, it looks like the data length will only be `8192` or smaller because that's the capacity of the `Vec<u8>` in `WriteBuffer` so no need to change anything there.
Fixes #3696

fix(Postgres) chunk pg_copy data

---

sqlx-mysql/src/connection/executor.rs

Removes an unnecessary call to `Box::pin` in the `MySql` driver.

chore(MySql): Remove unnecessary box

---

sqlx-postgres/src/types/record.rs
tests/postgres/derives.rs

fixes #1672 - or at least [my last comment](https://github.com/launchbadge/sqlx/issues/1672#issuecomment-2483639488) on the ticket, as I now realise the person originally reported a decoding issue, and this is about encoding, as decoding already worked fine. My specific scenario has been added to the test suite to confirm this fixes it.
This fix is inspired by this similar bit of code:
https://github.com/launchbadge/sqlx/blob/82d332f4b487440b4c2bd5d54a5f17dcc1abc92c/sqlx-postgres/src/types/array.rs#L168-L175
With this fix in, it's now perfectly fine to store (and retrieve) nested structures in Postgres, without any additional boilerplate, such as:
```rust
#[derive(Debug, sqlx::Type)]
#[sqlx(type_name = "http_response")]
struct HttpResponseRecord {
status_code: i16,
headers: …
```

Added missing special casing for encoding embedded arrays of custom types

---

sqlx-core/src/from_row.rs
sqlx-macros-core/src/derives/attributes.rs
sqlx-macros-core/src/derives/row.rs
tests/mysql/macros.rs

fixes #2849
This MR introduces a `#[sqlx(json(nullable))]` attribute which allows for the correct behaviour on
```rust
#[derive(Serialize, Deserialize)]
enum Foo {
Bar,
Baz
}
struct Test {
#[sqlx(json(nullable))]
hello: Option<Foo>
}
```
by allowing the underlying row value to be null

Add json(nullable) macro attribute

---

tests/postgres/postgres.rs

In #3699 an issue was opened that stated that a `PgConnection` is left in a broken state if a `copy_in_raw` returns an error. There is a PR linked (https://github.com/sqlpage/sqlx-oldapi/commit/0310a7b91ddd50bc06b85f6f1348fc1829bcdf58) that fixes this error for `sqlx_oldapi`. I tried reproducing this issue with the regression tests in the PR but could not get an error with `SQLx` version `0.8.3`.
I tested multiple versions and found out that versions `0.6.3` and older have this issue but newer versions are fixed. In this PR I added the regression tests from `sqlx_oldapi` so issue can't come back.
Fixes #3699

chore: add pg_copy regression tests

---

sqlx-postgres/src/type_checking.rs
sqlx-postgres/src/types/geometry/box.rs
sqlx-postgres/src/types/geometry/mod.rs
sqlx-postgres/src/types/mod.rs
tests/postgres/types.rs

Part 4 of fixing https://github.com/launchbadge/sqlx/issues/166

feat(postgres): add geometry box

---

sqlx-core/src/from_row.rs

The `try_from` and `json` sections are "Field attributes" so they should probably be part of the corresponding section instead of subsections of "Manual implementation". `flatten` should be H4 instead of H3, since "Field attributes" is H3 and all other field attribute sections are H4 too.

FromRow: Fix documentation order

---

README.md

The readme previously stated that the uuid feature is only for postgres but it actually also gates the functionality in mysql and sqlite.

Fix readme: uuid feature is gating for all repos

---

sqlx-core/src/io/write_and_flush.rs
sqlx-core/src/net/socket/mod.rs
sqlx-core/src/net/tls/util.rs
sqlx-core/src/pool/inner.rs
sqlx-core/src/pool/mod.rs
sqlx-mysql/src/any.rs
sqlx-mysql/src/connection/executor.rs
sqlx-postgres/src/any.rs
sqlx-postgres/src/connection/executor.rs
sqlx-sqlite/src/any.rs
sqlx-sqlite/src/connection/executor.rs
tests/postgres/postgres.rs

This small refactor replaces:
1. `pin_mut!` from `futures-util` with `std::pin::pin!`
2. `ready!` from `futures-core` / `futures-util` with `std::task::ready!`
3. `Future` re-export from `futures-util` with direct import from `std`
4. `poll_fn` from `futures-util` with `std::future::poll_fn`

Replace some `futures-core` / `futures-util` APIs with `std` variants

---

sqlx-cli/src/bin/cargo-sqlx.rs
sqlx-cli/src/bin/sqlx.rs
sqlx-cli/src/opt.rs

https://github.com/launchbadge/sqlx/issues/3722
Automatic loading of `.env` files can be dangerous (and destructive).  It is possible to run an sqlx database command against a database that you did not expect just by virtue of there being a hidden `.env` file in the directory from which you ran the command.
This PR adds a top-level switch to the `sqlx` CLI `--no-dotenv` which will disable the automatic loading of `.env` files.  This makes it safer to use in scripts and allows developers to make loading `.env` files explicit if they want.

feat(sqlx-cli): Add flag to disable automatic loading of .env files

---

Cargo.toml
sqlx-core/src/types/mod.rs

This was removed in #2039, so I'm not sure if the feature should be removed completely or was forgotten about. This pr exposes the feature so it can be used, if it should be removed I'll update this pr.
Fixes #3702

chore: expose bstr feature

---

Cargo.lock
sqlx-core/Cargo.toml
sqlx-core/src/net/tls/tls_rustls.rs

Replaces rustls-pemfile crate with rustls-pki-types api.

chore: replace rustls-pemfile with rustls-pki-types

---

Cargo.lock
sqlx-core/src/query_builder.rs

QueryBuilder: add debug_assert when `push_values` is passed an empty set of tuples

---

sqlx-mysql/src/testing/mod.rs
sqlx-postgres/src/testing/mod.rs
sqlx-postgres/src/types/cube.rs
sqlx-postgres/src/types/mod.rs

very minor but noticed some backticks were not properly delimited in the docs for `sqlx_postgres`, so this fixes that formatting.
running ``rg -P '^[^`]*\`[\`]*$'`` found a few more places that should likely have delimiting backticks, so fixed up those as well.

docs: add some missing backticks

---

sqlx-postgres/src/testing/mod.rs

We use serverless Postgres provider [Neon](https://neon.tech/home), which limits the privileges available for security reasons. This means that locking `pg_namespace` as is currently done isn't possible, and so it is impossible to use `sqlx::test` with Neon (likely other providers are similar).
Fortunately, this lock exists to avoid a race condition when setting up the test environment, and it can be replaced with an advisory lock. This is also suggested by [a more recent StackOverflow answer to the referenced question](https://stackoverflow.com/a/75698561).
The downside of this approach is that other code (including older sqlx versions) will not honor the lock when trying to make `_sqlx_test` objects. This seems unlikely, and is both data-safe and ephemeral when it happens (it just …

Avoid privilege requirements by using an advisory lock in test setup (postgres).

---

Cargo.lock
sqlx-cli/Cargo.toml
sqlx-cli/src/database.rs
sqlx-cli/src/lib.rs

Turns out #3665 didn't fully fix the build for loongarch64 and s390x because the `promptly` crate depends on an old version of `nix`. While looking more into it I found that `promptly` is unmaintained and is used very little (judging by the reverse dependencies on crates.io and number of downloads). I've decided to replace it with `dialoguer`, maintained by `console-rs` org from which other crates sqlx-cli is already depending on.
This also happens to reduce the number of indirect dependencies, which is nice.

refactor(cli): replace promptly with dialoguer

---

.github/workflows/examples.yml
.github/workflows/sqlx-cli.yml
.github/workflows/sqlx.yml

* Fix breakage from Rustup 1.28 <https://blog.rust-lang.org/2025/03/02/Rustup-1.28.0.html>
* Let `Swatinem/rust-cache` generate cache keys
* Upgrade Ubuntu jobs to 24.04

fix(ci): breakage from Rustup 1.28

---

sqlx-postgres/src/type_checking.rs
sqlx-postgres/src/types/geometry/box.rs
sqlx-postgres/src/types/geometry/circle.rs
sqlx-postgres/src/types/geometry/line.rs
sqlx-postgres/src/types/geometry/line_segment.rs
sqlx-postgres/src/types/geometry/mod.rs
sqlx-postgres/src/types/geometry/path.rs
sqlx-postgres/src/types/geometry/point.rs
sqlx-postgres/src/types/geometry/polygon.rs
sqlx-postgres/src/types/mod.rs
tests/postgres/types.rs

Part 7 of fixing https://github.com/launchbadge/sqlx/issues/166
fixes https://github.com/launchbadge/sqlx/issues/166
No, it is adding a new type without changing or modifying existing types or features.

feat(postgres): add geometry circle

---

sqlx-mysql/src/options/mod.rs

I suspect this is a copy-paste error, it's meant to say username, not port.
Haven't checked, but I expect if anyone noticed, they'd just fix it rather than open an issue.
No, documentation only.

Fix a copy-paste error on get_username docs

---

Cargo.toml

Fixes #3797 to ensure json type is imported even when a database feature isn't enabled. This is not a breaking change.

Fix: Enable Json type when db feature isn't enabled

---

Cargo.toml
sqlx-macros-core/src/query/data.rs
sqlx-macros-core/src/query/mod.rs

fixes #3738
no.
This PR updates the metadata cache to be a `HashMap` that stores a `Metadata` with `CARGO_MANIFEST_DIR` as the key as mentioned in https://github.com/launchbadge/sqlx/issues/3738#issuecomment-2784662051.
The lock on the metadata can be release earlier but that would require some more code changes. (For example the lifetime on `QueryDataSource` has to be removed.)

fix(macros): cache macro metadata based on `CARGO_MANIFEST_DIR`

---

sqlx-sqlite/src/connection/establish.rs

I have encountered this issue when trying to package a downstream project where the in-memory sqlite database was simply gone at subsequent accesses. The issue is that URI format is implicitly used, but the flag is never set
https://github.com/launchbadge/sqlx/blob/1388fc8acc07b41ab38f4dc096f03ba9c7b851f8/sqlx-sqlite/src/options/parse.rs#L18-L23
This issue was not detected because only the bundled `libsqlite3-sys` version is tested which has the `USE_URI` compile flag enabled. On distros, however this is not yet enabled, and it is just started to be investigated [^1]
Related to:
- https://github.com/launchbadge/sqlx/issues/2510
- https://github.com/launchbadge/sqlx/issues/362#issuecomment-636661146
[^1]: https://bugzilla.redhat.com/show_bug.cgi?id=2291157

Always set `SQLITE_OPEN_URI` on in-memory sqlite

---

sqlx-postgres/src/options/mod.rs

Note I'm PRing this to document the *current* behavior, I'm not sure if it was the intention of the original author to support MORE behavior than `libpq` offers.
If I look at `pub fn ssl_client_key(self, key: impl AsRef<Path>) -> PgConnectOptions` there is no way to "set" the inline version of `CertificateInput`, it only accepts the file version. This potentially should be lifted for symmetry with the environment variables.
This may not be the intention? But also I seen no reason to artificially constrain `sqlx-postgres` to libpq behavior, in lots of scenarios (single file lambda binary) its much better to be able to set the certificate inline.
Regardless of what the desired final behavior is: This PR just documents the status quo, even if we wish to change it in the future.
no

fix: PgConnectOptions docs

---

sqlx-macros-core/Cargo.toml

No. I've just realized that my project depends on `tempfile` via `sqlx-macros-core`. `tempfile` is only needed for sqlx tests, so it's not necessary for the normal build to work.
No

build: drop unused `tempfile` dependency

---

sqlx-core/src/from_row.rs

Fixes a tiny typo in the `FromRow` trait documentation that I noticed as I was reading it.
Much love for this fantastic crate!

fix `attrubute` typo in doc

---

sqlx-core/src/from_row.rs
sqlx-core/src/types/mod.rs
src/macros/mod.rs

fixes #3864
No, documentation only.

chore(doc): clarify compile-time verification and case conversion behavior

---

sqlx-macros-core/src/query/args.rs
sqlx-macros-core/src/query/output.rs

This PR makes a small improvement to the "unsupported type" error message to suggest a potential solution to the user.
I just spent a couple hours on an issue forgetting that type overrides exist and I wished that the message nudged me in that direction. 
Perhaps the message could be made even more intelligent.
No. It's a minor DX improvement.

fix(macros): slightly improve unsupported type error message

---

sqlx-macros-core/src/query/mod.rs

This PR fixes a regression I created in #3815. Now, environment variables are read or fall back to the `.env` file instead of mutating them before expanding the `query` macro's.
fixes #3836

fix(macros): don't mutate environment variables

---

sqlx-postgres/src/connection/executor.rs
sqlx-postgres/src/message/parse.rs
tests/postgres/postgres.rs

This change makes Postgres use the unnamed statement when preparing statements and `persistent = false`.
This means Postgres will automatically close the prepared statement when another query is run – as per the [docs](https://www.postgresql.org/docs/13/protocol-flow.html) – avoiding a memory leak.
fixes #3850
No.
it fixes a bug, and makes it behave as documented.

Use unnamed statement in pg when not persistent

---

sqlx-sqlite/Cargo.toml

The documentation of (at least) `sqlx-sqlite` is [not been available on docs.rs](https://docs.rs/crate/sqlx-sqlite/0.8.5) - it also doesn't work to run `cargo doc` without specifying features locally.
This patch fixes the docs.rs issue.

Fix docs.rs build of sqlx-sqlite

---

sqlx-postgres/src/options/mod.rs

Properly escape PostgreSQL options containing spaces and backslash characters as specified under https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNECT-OPTIONS.
Fixes #2027 
~~No, this change fixes behavior that I consider a minor edge case.~~
Yes,
> anyone who's already manually escaping options will get different, likely incorrect, results after this patch

Escape PostgreSQL options

---

sqlx-core/src/pool/inner.rs

Logging of slow connection acquires was added with https://github.com/launchbadge/sqlx/pull/3073 and included tracing fields. One of those fields has an incorrect spelling of `acquire` in its name; this PR corrects the spelling.
Some users of the crate were interested in collecting metrics or building alerts based on this and related tracing fields. If we simply rename the field, this would be a breaking change. @abonander has mentioned he is open to including both the old spelling and the corrected spelling if there is concern about a breaking change to the log field naming.
Due to previous interest in this or https://github.com/launchbadge/sqlx/pull/3004:
cc @jqphu / @Matthias247 / @kukabi

fix(logs): Correct spelling of aquired_after_secs tracing field

---

sqlx-core/src/decode.rs
sqlx-core/src/encode.rs
sqlx-core/src/types/mod.rs
sqlx-mysql/src/types/bytes.rs
sqlx-mysql/src/types/str.rs
sqlx-postgres/src/types/bytes.rs
sqlx-postgres/src/types/str.rs
sqlx-sqlite/src/types/bytes.rs
sqlx-sqlite/src/types/str.rs
tests/mysql/types.rs
tests/postgres/types.rs
tests/sqlite/types.rs

fixes #3100
Implements `Decode`, `Encode` and `Type` for `Box<T>`, `Arc<T>`, `Cow<'_,T>` and `Rc<T>`. I left out the `Decode` impl for `Rc<T>` because of the `Send` trait bounds in `QueryAs` and `QueryScalar` (which makes it impossible to use `Rc`).

Implement `Decode`, `Encode` and `Type` for `Box`, `Arc`, `Cow` and `Rc`

---

sqlx-core/src/raw_sql.rs
tests/sqlite/sqlite.rs

fixes #3150
fixes #3581 
fixes #3591
TODO:
Strictly speaking, this is a breaking change because it adds the `DB` type parameter to all methods.

fix: `RawSql` lifetime issues

---

sqlx-core/src/migrate/migrator.rs

This allows the migrator methods to be chained.
~Fixes #1788~ (edit: does not)

Return &mut Self from the migrator set_ methods

---

Cargo.lock
sqlx-macros-core/src/database/mod.rs
sqlx-postgres/src/connection/describe.rs

Currently when using the `query!` and `query_as!` macro's sqlx uses `explain (verbose, format json) execute {statement_id}` to get the query plan of a prepared statement/query. Then looks through the plans and tries to be more accurate with the type inference.
If a prepared statement has query parameters it needs to fill then in with a valid argument and uses [`NULL`](https://github.com/launchbadge/sqlx/blob/19f40d87a669e41081a629a469359d341c9223d6/sqlx-postgres/src/connection/describe.rs#L525-L539) for every one because it is always a valid argument.
This causes the query planner to give a query plan back that is optimized when the function arguments are all `NULL`, this is not always correct.
This pr forces postgres to use a generic execution plan when describing a prepared statement …

Postgres: force generic plan for better nullability inference.

---

sqlx-mysql/src/connection/executor.rs
sqlx-mysql/src/protocol/response/ok.rs

As per the Mysql documentation, OK and EOF packets have the following structure
OK: header = 0 and length of packet >= 7
EOF: header = 0xfe and length of packet < 8
Right now we are checking to see if the packet is smaller than 9 which is fine for most cases however there are some projects that implement the MySQL protocol which include information in the packet (e.g query speed, rows returned in human readable text)
https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_basic_ok_packet.html
For example in the project manticore https://github.com/manticoresoftware/manticoresearch (Which is why I found this bug) their ok packet to designate the end of the data will include more information. This would result in sqlx treating the the OK packet as a text field due to the fact that …

feat(ok): add correct handling of ok packets in MYSQL implementation

---

sqlx-cli/src/bin/cargo-sqlx.rs
sqlx-cli/src/bin/sqlx.rs
sqlx-cli/src/lib.rs
sqlx-macros-core/src/database/mod.rs
sqlx-macros-core/src/lib.rs

Not on this repo, but it would solve an issue for the `sqlx-exasol` driver: https://github.com/bobozaur/sqlx-exasol/issues/9.
With the changes here, the compile-time macros can be redefined by external drivers through usage of `sqlx_macros_core::query::expand_input()` with a custom `QueryDriver`. Furthermore, a `sqlx-cli` like binary can be exposed as well, since the `install_default_drivers()` call was moved to the `sqlx-cli` binaries. With these changes, the custom driver binary (that depends on `sqlx-cli` as a library) can install its own driver (this would panic with the current state of things).
Nope, it's internal only. Should not affect anything else at all.

Compile-time support for external drivers

---

Cargo.lock
sqlx-core/Cargo.toml
sqlx-core/src/net/tls/tls_rustls.rs

From [Rustls 0.23.24 release](https://github.com/rustls/rustls/releases/tag/v%2F0.23.24):
> New feature: More detailed and helpful error reporting for common certificate errors, such as name mismatches and certificate expiry. Users who std::fmt::Display the rustls Error type will take advantage of this automatically. Users handling CertificateError variants individually should note the new variants, such as CertificateError::NotValidForNameContext (compare CertificateError::NotValidForName).
This fixes the `NoHostnameTlsVerifier` by also matching on this new variant.
Fixes #3793

Fix NoHostnameTlsVerifier for rustls 0.23.24 and above

---

sqlx-mysql/src/connection/executor.rs
tests/mysql/error.rs

fixes #3774
No. This PR adds proper error handling when the number of parameters provided doesn't match the number expected by a prepared statement in MySQL.

fix(mysql): validate parameter count for prepared statements

---

sqlx-postgres/src/types/rust_decimal.rs

This was discovered while reading very large negative numbers in a production PostgreSQL Database.
Without the fix the library will panic. Please see attached testcase.
I didn't find an open issue for this.
No. But before this change consumers of the library will panic.

fix[sqlx-postgres]: do a checked_mul to prevent panic'ing

---

sqlx-core/src/error.rs
sqlx-postgres/src/error.rs
tests/postgres/error.rs
tests/postgres/setup.sql

A rather trival addition, though there are other error codes which could probably be considered aswell. It seems as though the selection of error kinds has been kept small for a reason, i.e. only add error kind for the most "normal" errors a user would want to programmatically handle, do something with. For my usecase, the exclusion violation fits this premise, and I would say it's destinct enough from the unique violation to deserve it's own kind. Anyhow, thank you for a great library, and feel free to do with this PR what you want! 😄  
No.
No, the enum is marked as `non_exhaustive`, so adding a variant is backwards compatible.

Feature: Add exclusion violation error kind

---

sqlx-mysql/src/testing/mod.rs

While working on #3723 I noticed a bug in the `MySql` implementation of `TestSupport::cleanup_test_dbs` and didn't want to bury it into the massive pr. A part of the old implementation is still used to get the test db name. The code isn't used anywhere in SQLx but is part of the public API.
I can't find a way to add a regression test for this since this should be ran when all the tests are done running.

sqlx-mysql: Fix bug in cleanup test db's.

---

sqlx-core/src/row.rs
sqlx-mysql/src/row.rs
sqlx-postgres/src/row.rs
sqlx-sqlite/src/row.rs

In a personal code base I currently maintain a `Row` implementation called `DebugRow` as a catch-all type for queries so that I can use its `Debug` implementation for snapshot testing (using the great [insta](https://lib.rs/crates/insta) crate). 
While upgrading the version of sqlx I noticed there was now a useful `Debug` implementation for `PgRow` (#2917) which had me hoping there was an equivalent for `SqliteRow`, but after digging through the code I found out
- `PgRow` has a custom `Debug` which prints out the contents of the row using `debug_map()`
- `MySqlRow` uses a derived `Debug`
- `SqliteRow` does not implement `Debug`
Rather than implement similar logic to `PgRow` for `SqliteRow` I figured it might be better to unify the implementations as the various traits (e.g. `Row`, …

feat: Unify `Debug` implementations across `PgRow`, `MySqlRow` and `SqliteRow`

---

sqlx-core/src/logger.rs
sqlx-mysql/src/connection/executor.rs
sqlx-postgres/src/connection/executor.rs

In #3723 I moved the `QueryLogger` around in the mysql and postgres drivers but that also delays the start of the logger. This pr moves them back to where they were before.

Move `QueryLogger` back

---

tests/sqlite/error.rs
tests/sqlite/types.rs

The `git2` feature was removed by https://github.com/launchbadge/sqlx/pull/2039 for the `0.7.0` release but a test enabled by that feature still remains in the `sqlite` test suite.
* Remove the test of the removed feature
* Misc unused import warning cleanup
No - only makes a change to test code, not implementation code.

chore(sqlite): Remove unused test of removed git2 feature

---

sqlx-postgres/src/options/doc.md

pretty self-explanatory, I think someone forgot something here

fix documentation for rustls native root certificates

---

.github/workflows/examples.yml
.github/workflows/sqlx-cli.yml
.github/workflows/sqlx.yml

Occasionally a CI job will hang infinitely, recently observed with one of the Postgres 13 CI jobs running well over an hour. In that example, a test was hung: `test test_pg_listener_allows_pool_to_close has been running for over 60 seconds` causing the job to not make progress after 1h 45m.
https://github.com/launchbadge/sqlx/actions/runs/16864658928/job/47769903098?pr=3958
Fails CI jobs that are hung.
No - only changes CI configuration

chore(ci): Add timeouts to ci jobs

---

Cargo.lock
Cargo.toml

See [the release notes](https://github.com/achanda/ipnetwork/releases/tag/v0.21.0).

Bump ipnetwork to v0.21.1

---

examples/postgres/listen/src/main.rs
sqlx-core/src/pool/inner.rs

Fixes https://github.com/launchbadge/sqlx/issues/3217.
Supersedes https://github.com/launchbadge/sqlx/pull/3299.
I'm taking into consideration the discussion that already happened in https://github.com/launchbadge/sqlx/pull/3299, and then I just rebase it on the latest `main` and add one commit on top of that to address the problem with child pools. The solution turned out to be pretty simple.

`Pool.close`: close all connections before returning

---

sqlx-macros-core/src/derives/attributes.rs
sqlx-macros-core/src/derives/decode.rs
sqlx-macros-core/src/derives/encode.rs
sqlx-macros-core/src/derives/type.rs
tests/mysql/derives.rs
tests/postgres/derives.rs
tests/sqlite/derives.rs

This more closely matches the criteria for e.g. `#[repr(transparent)]` and `#[serde(transparent)]`.
TODO, if this is deemed a desirable change:
Couldn't find an issue filed already.
No, code that previously compiled is unchanged, only code that used to be a compile error now does compile.

Allow single-field named structs to be transparent

---

sqlx-sqlite/src/value.rs
tests/sqlite/sqlite.rs
tests/sqlite/types.rs

fix(sqlite): regression when decoding nulls

---

sqlx-core/src/query.rs

The docstring for `Query::try_bind` is incorrect and misleading:
* Incorrect - should reference the `bind` function just above it; references itself instead
* Unclear - says error is returned for encoding the given bind argument value; actual behavior is to return an error if a prior  bind argument value had failed encoding or the current bind argument failed encoding
No; documentation only

chore(core): Fix docstring for Query::try_bind

---

sqlx-postgres/src/types/ltree.rs

The title should be self-describing.
fixes #3948 .
Yes, it affects trait resolution and type inference. See [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&gist=1a555189191bbd7aa087b4b45aa9d4e5).

Postgres: move `PgLTree::from` to `From<Vec<PgLTreeLabel>>` implementation

---

.github/workflows/sqlx.yml
Cargo.toml
tests/sqlite/macros.rs

Resolves this `cargo` warning:
```
warning: ./Cargo.toml: file `./tests/sqlite/macros.rs` found to be present in multiple build targets:
* `integration-test` target `sqlite-macros`
* `integration-test` target `sqlite-unbundled-macros`
```
Merges the two target definitions in `Cargo.toml` and moves the `sqlite` vs `sqlite-unbundled` feature check to the top of the `macros.rs` module.
No; only affects test target configuration.

refactor(sqlite): Resolve duplicate test target warning for macros.rs

---

sqlx-core/src/types/json.rs
tests/postgres/derives.rs
tests/postgres/setup.sql

This cleans up 2 of my tests that were added in previous PRs.
The first commit is a unit tests from #3641.It was also mentioned in https://github.com/launchbadge/sqlx/issues/3996#issuecomment-3221971241 but 0 is not positive.
The second is from #3453, for some reason I put it in dutch not english.
Edit: This pr also removes a duplicate `sqlx::Type` impl for `Box<serde_json::value::RawValue>` that slipped in after #3859 was merged.

sqlx-postgres(tests): cleanup 2 unit tests.

---

.github/workflows/sqlx.yml
tests/postgres/types.rs

Resolves a deprecation warning caused by the `chrono` crate deprecating its `Date` type and the `ymd` method that returned a `Date` value.
Example of deprecation warning:
```
warning: use of deprecated method `sqlx::types::chrono::TimeZone::ymd`: use `with_ymd_and_hms()` instead
--> tests/postgres/types.rs:355:67
|
355 |             == FixedOffset::east_opt(60 * 60 * 6 + 1800).unwrap().ymd(2019, 1, 2).and_hms_micro_opt(5, 10, 20, 115100).unwrap()
|                                                                   ^^^
|
= note: `#[warn(deprecated)]` on by default
```
No; only changes tests:
* Replace deprecated builder methods with newer ones
* Add `-D warnings` to `RUSTFLAGS` for postgres ci jobs, now that all of the compile warnings are resolved.
There is still a warning about cargo …

chore(deps): Resolve deprecation warning for chrono Date and ymd methods

---

sqlx-macros-core/src/derives/type.rs
tests/postgres/types.rs

fixes #3996
See the issue for the reasoning behind the changes.
Yes. People who use domain types in PostgreSQL have likely already implemented the `PgHasArrayType` trait manually to work around the problem from #3996. In that case, my changes would introduce a duplicate implementation of the trait. The solution would be to either remove the manual implementation or add the `#[sqlx(no_pg_array)]` attribute to the struct.

make `#[derive(sqlx::Type)]` automatically generate `impl PgHasArrayType` by default for newtype structs

---

sqlx-sqlite/src/migrate.rs
tests/sqlite/migrate.rs
tests/sqlite/migrations_no_tx_reversible/0_vacuum.down.sql
tests/sqlite/migrations_no_tx_reversible/0_vacuum.up.sql

None created yet.
No, it's a bug fix.
Migration reverts using `no-tx` in SQLite  currently try to reapply (and fail) migrations, instead of reverting/downgrading.

fix(sqlite) Migrate revert with no-transaction
